/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-16 21:19:35
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "event.h"

#include "event.h"
static void kleva_stub_EventCallback(const Event *e, void *ctx) {
    (void)e;
    (void)ctx;
}

static void test_queue_create_valid_tv001(void) {
    EventQueue * out_ret = event_queue_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 1); /* EVA-proven oracle */
    if (out_ret) event_queue_free(out_ret);
    printf("PASS test_queue_create_valid_tv001\n");
}

static void test_queue_free_null_tv001(void) {
    event_queue_free(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_queue_free_null_tv001\n");
}

static void test_queue_free_valid_tv001(void) {
    EventQueue *eq = event_queue_create(64);
    assert(eq != NULL);
    event_queue_free(eq);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_queue_free_valid_tv001\n");
}

static void test_queue_push_valid_tv001(void) {
    EventQueue *eq = event_queue_create(64);
    assert(eq != NULL);
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    int out_ret = event_queue_push(eq, e);
    assert(out_ret == 0); /* EVA-proven oracle */
    event_queue_free(eq);
    event_free(e);
    printf("PASS test_queue_push_valid_tv001\n");
}

static void test_queue_pop_valid_tv001(void) {
    EventQueue *eq = event_queue_create(64);
    assert(eq != NULL);
    Event * out_ret = event_queue_pop(eq);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    event_queue_free(eq);
    printf("PASS test_queue_pop_valid_tv001\n");
}

static void test_queue_peek_valid_tv001(void) {
    EventQueue *eq = event_queue_create(64);
    assert(eq != NULL);
    Event * out_ret = event_queue_peek(eq);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    event_queue_free(eq);
    printf("PASS test_queue_peek_valid_tv001\n");
}

static void test_queue_is_empty_valid_tv001(void) {
    EventQueue *eq = event_queue_create(64);
    assert(eq != NULL);
    int out_ret = event_queue_is_empty(eq);
    assert(out_ret == 1); /* EVA-proven oracle */
    event_queue_free(eq);
    printf("PASS test_queue_is_empty_valid_tv001\n");
}

static void test_create_valid_tv001(void) {
    Event * out_ret = event_create(0, 0, NULL, NULL, NULL, NULL);
    int out_ret_nonnull = (out_ret != NULL);
    int out_type_same = (out_ret != NULL && out_ret->type == 0);
    uint64_t out_timestamp = out_ret ? out_ret->timestamp : 0;
    int out_packet_same = (out_ret != NULL && out_ret->packet == NULL);
    int out_data_same = (out_ret != NULL && out_ret->data == NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_type_same == 1); /* EVA-proven oracle */
    assert(out_timestamp == 0); /* EVA-proven oracle */
    assert(out_packet_same == 1); /* EVA-proven oracle */
    assert(out_data_same == 1); /* EVA-proven oracle */
    if (out_ret) event_free(out_ret);
    printf("PASS test_create_valid_tv001\n");
}

static void test_create_callback_valid_tv001(void) {
    Event * out_ret = event_create_callback(0, 0, NULL, NULL, NULL, NULL, kleva_stub_EventCallback, NULL);
    int out_ret_nonnull = (out_ret != NULL);
    int out_type_same = (out_ret != NULL && out_ret->type == 0);
    uint64_t out_timestamp = out_ret ? out_ret->timestamp : 0;
    int out_packet_same = (out_ret != NULL && out_ret->packet == NULL);
    int out_data_same = (out_ret != NULL && out_ret->data == NULL);
    int out_handler_same = (out_ret != NULL && out_ret->handler == kleva_stub_EventCallback);
    int out_handler_ctx_same = (out_ret != NULL && out_ret->handler_ctx == NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_type_same == 1); /* EVA-proven oracle */
    assert(out_timestamp == 0); /* EVA-proven oracle */
    assert(out_packet_same == 1); /* EVA-proven oracle */
    assert(out_data_same == 1); /* EVA-proven oracle */
    assert(out_handler_same == 1); /* EVA-proven oracle */
    assert(out_handler_ctx_same == 1); /* EVA-proven oracle */
    printf("PASS test_create_callback_valid_tv001\n");
}

static void test_free_null_tv001(void) {
    event_free(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_free_null_tv001\n");
}

static void test_free_valid_tv001(void) {
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    event_free(e);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_free_valid_tv001\n");
}

int main(void) {
    test_queue_create_valid_tv001();
    test_queue_free_null_tv001();
    test_queue_free_valid_tv001();
    test_queue_push_valid_tv001();
    test_queue_pop_valid_tv001();
    test_queue_peek_valid_tv001();
    test_queue_is_empty_valid_tv001();
    test_create_valid_tv001();
    test_create_callback_valid_tv001();
    test_free_null_tv001();
    test_free_valid_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
