/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-07-02 16:39:14
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "scheduler.h"

/* KLEVA native compile note:
 * This generated test includes allocator-failure candidates.
 * Compile the module-under-test with:
 *   -Dmalloc=__kleva_malloc -Dcalloc=__kleva_calloc -Drealloc=__kleva_realloc -Dfree=__kleva_free
 */

#include "scheduler.h"
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#ifdef malloc
#undef malloc
#endif
#ifdef calloc
#undef calloc
#endif
#ifdef realloc
#undef realloc
#endif
#ifdef free
#undef free
#endif
static unsigned char __kleva_alloc_arena[1024u * 1024u];
struct __kleva_alloc_rec {
    void *ptr;
    size_t size;
    int active;
};
static struct __kleva_alloc_rec __kleva_alloc_recs[1024];
static size_t __kleva_alloc_offset;
static long __kleva_alloc_call;
static long __kleva_alloc_fail_at = -1;
static void __kleva_alloc_reset(void) {
    __kleva_alloc_offset = 0;
    __kleva_alloc_call = 0;
    __kleva_alloc_fail_at = -1;
    memset(__kleva_alloc_recs, 0, sizeof(__kleva_alloc_recs));
}
static void __kleva_alloc_record(void *ptr, size_t size) {
    if (!ptr) {
        return;
    }
    for (size_t i = 0; i < sizeof(__kleva_alloc_recs) / sizeof(__kleva_alloc_recs[0]); i++) {
        if (!__kleva_alloc_recs[i].active) {
            __kleva_alloc_recs[i].ptr = ptr;
            __kleva_alloc_recs[i].size = size;
            __kleva_alloc_recs[i].active = 1;
            return;
        }
    }
}
static size_t __kleva_alloc_size_of(void *ptr) {
    for (size_t i = 0; i < sizeof(__kleva_alloc_recs) / sizeof(__kleva_alloc_recs[0]); i++) {
        if (__kleva_alloc_recs[i].active && __kleva_alloc_recs[i].ptr == ptr) {
            return __kleva_alloc_recs[i].size;
        }
    }
    return 0;
}
static void __kleva_alloc_forget(void *ptr) {
    for (size_t i = 0; i < sizeof(__kleva_alloc_recs) / sizeof(__kleva_alloc_recs[0]); i++) {
        if (__kleva_alloc_recs[i].active && __kleva_alloc_recs[i].ptr == ptr) {
            __kleva_alloc_recs[i].active = 0;
            return;
        }
    }
}
static void __kleva_alloc_fail_on(long index) {
    __kleva_alloc_fail_at = __kleva_alloc_call + index;
}
void *__kleva_malloc(size_t size) {
    if (__kleva_alloc_fail_at >= 0 && __kleva_alloc_call == __kleva_alloc_fail_at) {
        __kleva_alloc_call++;
        __kleva_alloc_fail_at = -1;
        return (void *)0;
    }
    __kleva_alloc_call++;
    if (size == 0) {
        size = 1;
    }
    size = (size + 7u) & ~((size_t)7u);
    if (size > sizeof(__kleva_alloc_arena) - __kleva_alloc_offset) {
        return (void *)0;
    }
    void *ptr = __kleva_alloc_arena + __kleva_alloc_offset;
    __kleva_alloc_offset += size;
    __kleva_alloc_record(ptr, size);
    return ptr;
}
void __kleva_free(void *ptr) {
    __kleva_alloc_forget(ptr);
}
void *__kleva_calloc(size_t count, size_t size) {
    size_t total = count * size;
    void *ptr = __kleva_malloc(total);
    if (ptr) {
        memset(ptr, 0, total);
    }
    return ptr;
}
void *__kleva_realloc(void *ptr, size_t size) {
    if (!ptr) {
        return __kleva_malloc(size);
    }
    if (size == 0) {
        __kleva_free(ptr);
        return (void *)0;
    }
    size_t old_size = __kleva_alloc_size_of(ptr);
    void *new_ptr = __kleva_malloc(size);
    if (!new_ptr) {
        return (void *)0;
    }
    if (old_size > 0) {
        size_t copy_size = old_size < size ? old_size : size;
        memcpy(new_ptr, ptr, copy_size);
    }
    __kleva_alloc_forget(ptr);
    return new_ptr;
}
#include "event.h"
#include <stdlib.h>

static void test_create_bad_tv001(void) {
    Scheduler * out_ret = scheduler_create(0);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_create_bad_tv001\n");
}

static void test_create_ok_tv001(void) {
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_create_ok_tv001\n");
}

static void test_create_ir_if_0_capacity_eq_0_tv001(void) {
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_if_0_capacity_eq_0_tv001\n");
}

static void test_create_ir_if_0_false_capacity_ne_0_tv001(void) {
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_if_0_false_capacity_ne_0_tv001\n");
}

static void test_create_ir_alloc_malloc_0_zero_failure_tv001(void) {
    __kleva_alloc_reset();
    __kleva_alloc_fail_on(0);
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_0_zero_failure_tv001\n");
}

static void test_create_ir_alloc_malloc_0_zero_success_tv001(void) {
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_0_zero_success_tv001\n");
}

static void test_create_ir_callee_event_queue_create_zero_failure_tv001(void) {
    __kleva_alloc_reset();
    __kleva_alloc_fail_on(1);
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_create_ir_callee_event_queue_create_zero_failure_tv001\n");
}

static void test_create_ir_callee_event_queue_create_zero_success_tv001(void) {
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_callee_event_queue_create_zero_success_tv001\n");
}

static void test_create_ir_forbidden_value_0_capacity_eq_0_forbidden_tv001(void) {
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_forbidden_value_0_capacity_eq_0_forbidden_tv001\n");
}

static void test_create_ir_forbidden_value_0_capacity_eq_0_allowed_tv001(void) {
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_forbidden_value_0_capacity_eq_0_allowed_tv001\n");
}

static void test_create_ir_diversity_capacity_one_tv001(void) {
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_capacity_one_tv001\n");
}

static void test_create_ir_diversity_capacity_two_tv001(void) {
    Scheduler * out_ret = scheduler_create(2);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_capacity_two_tv001\n");
}

static void test_free_valid_tv001(void) {
    scheduler_free(NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_free_valid_tv001\n");
}

static void test_register_null_tv001(void) {
    scheduler_register(NULL, 0, 0, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_register_null_tv001\n");
}

static void test_register_valid_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    scheduler_register(s, 0, 0, NULL);
    int out_s_eq_nonnull = (s->eq != NULL);
    uint64_t out_s_now = s->now;
    int out_s_running = s->running;
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_s_handlers_type_fn = ((uintptr_t)(s->handlers[0].fn) == (uintptr_t)(0));
    int out_ir_post_s_handlers_type_ctx = ((uintptr_t)(s->handlers[0].ctx) == (uintptr_t)(NULL));
    assert(out_s_eq_nonnull == 1); /* EVA-proven oracle */
    assert(out_s_now == 0); /* EVA-proven oracle */
    assert(out_s_running == 0); /* EVA-proven oracle */
    assert(out_ir_post_s_handlers_type_fn == 1); /* EVA-proven oracle */
    assert(out_ir_post_s_handlers_type_ctx == 1); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_register_valid_tv001\n");
}

static void test_register_ir_if_0_left_left_not_s_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    s = 0;
    scheduler_register(s, 0, 0, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_register_ir_if_0_left_left_not_s_tv001\n");
}

static void test_register_ir_if_0_left_right_type_lt_0_tv001(void) {
    EventType type = (EventType)0ULL;
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    type = ((0) > 0 ? (0) - 1 : 0);
    scheduler_register(s, type, 0, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_register_ir_if_0_left_right_type_lt_0_tv001\n");
}

static void test_register_ir_if_0_right_type_ge_EVT_TYPE_COUNT_tv001(void) {
    EventType type = (EventType)0ULL;
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    type = EVT_TYPE_COUNT;
    scheduler_register(s, type, 0, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_register_ir_if_0_right_type_ge_EVT_TYPE_COUNT_tv001\n");
}

static void test_register_ir_if_0_false_false_not_s_and_false_type_ge_0_and_false_type_lt_EVT_TYPE_COUNT_tv001(void) {
    EventType type = (EventType)0ULL;
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    assert(s != NULL);
    type = 0;
    type = ((EVT_TYPE_COUNT) > 0 ? (EVT_TYPE_COUNT) - 1 : 0);
    scheduler_register(s, type, 0, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_register_ir_if_0_false_false_not_s_and_false_type_ge_0_and_false_type_lt_EVT_TYPE_COUNT_tv001\n");
}

static void test_register_ir_min_guard_0_type_lt_0_too_low_tv001(void) {
    EventType type = (EventType)0ULL;
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    type = 0;
    scheduler_register(s, type, 0, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_register_ir_min_guard_0_type_lt_0_too_low_tv001\n");
}

static void test_register_ir_min_guard_0_type_lt_0_valid_high_tv001(void) {
    EventType type = (EventType)0ULL;
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    type = 1;
    scheduler_register(s, type, 0, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_register_ir_min_guard_0_type_lt_0_valid_high_tv001\n");
}

static void test_schedule_null_tv001(void) {
    int out_ret = scheduler_schedule(NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_schedule_null_tv001\n");
}

static void test_schedule_valid_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    Event * event_create(EventType type, uint64_t timestamp, void * src, void * dst, void * packet, void * data);
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    void event_free(Event *arg0);
    int out_ret = scheduler_schedule(s, e);
    assert(out_ret == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_schedule_valid_tv001\n");
}

static void test_schedule_ir_if_0_left_not_s_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    Event * event_create(EventType type, uint64_t timestamp, void * src, void * dst, void * packet, void * data);
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    void event_free(Event *arg0);
    s = 0;
    int out_ret = scheduler_schedule(s, e);
    assert(out_ret == -1); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_schedule_ir_if_0_left_not_s_tv001\n");
}

static void test_schedule_ir_if_0_right_not_e_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    Event * event_create(EventType type, uint64_t timestamp, void * src, void * dst, void * packet, void * data);
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    void event_free(Event *arg0);
    e = 0;
    int out_ret = scheduler_schedule(s, e);
    assert(out_ret == -1); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_schedule_ir_if_0_right_not_e_tv001\n");
}

static void test_step_valid_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    int out_ret = scheduler_step(s);
    assert(out_ret == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_step_valid_tv001\n");
}

static void test_step_ir_callee_event_queue_pop_zero_failure_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    (s)->eq->count = 0;
    int out_ret = scheduler_step(s);
    assert(out_ret == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_step_ir_callee_event_queue_pop_zero_failure_tv001\n");
}

static void test_step_ir_callee_event_queue_pop_zero_success_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    (s)->eq->count = 1;
    Event * kleva_event_queue_pop_e_0_array[1];
    memset(kleva_event_queue_pop_e_0_array, 0, sizeof(kleva_event_queue_pop_e_0_array));
    (s)->eq->events = kleva_event_queue_pop_e_0_array;
    Event *kleva_event_queue_pop_e_0 = malloc(sizeof(*kleva_event_queue_pop_e_0));
    assert(kleva_event_queue_pop_e_0 != NULL);
    memset(kleva_event_queue_pop_e_0, 0, sizeof(*kleva_event_queue_pop_e_0));
    (s)->eq->events[0] = kleva_event_queue_pop_e_0;
    int out_ret = scheduler_step(s);
    int out_s_eq_nonnull = (s->eq != NULL);
    uint64_t out_s_now = s->now;
    int out_s_running = s->running;
    assert(out_ret == 1); /* EVA-proven oracle */
    assert(out_s_eq_nonnull == 1); /* EVA-proven oracle */
    assert(out_s_now == 0); /* EVA-proven oracle */
    assert(out_s_running == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_step_ir_callee_event_queue_pop_zero_success_tv001\n");
}

static void test_run_valid_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    int out_ret = scheduler_run(s);
    int out_ir_post_s_running = ((uintptr_t)(s->running) == (uintptr_t)(1));
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_ir_post_s_running == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_run_valid_tv001\n");
}

static void test_stop_null_tv001(void) {
    scheduler_stop(NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_stop_null_tv001\n");
}

static void test_stop_valid_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    scheduler_stop(s);
    int out_s_eq_nonnull = (s->eq != NULL);
    uint64_t out_s_now = s->now;
    int out_s_running = s->running;
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_s_running = ((uintptr_t)(s->running) == (uintptr_t)(0));
    assert(out_s_eq_nonnull == 1); /* EVA-proven oracle */
    assert(out_s_now == 0); /* EVA-proven oracle */
    assert(out_s_running == 0); /* EVA-proven oracle */
    assert(out_ir_post_s_running == 1); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_stop_valid_tv001\n");
}

static void test_stop_ir_if_0_truthy_s_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    assert(s != NULL);
    scheduler_stop(s);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_state_s_running_0 = ((uintptr_t)(s->running) == (uintptr_t)(0));
    assert(out_post_state_s_running_0 == 1); /* EVA-proven oracle */
    printf("PASS test_stop_ir_if_0_truthy_s_tv001\n");
}

static void test_stop_ir_if_0_false_truthy_s_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    s = 0;
    scheduler_stop(s);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_stop_ir_if_0_false_truthy_s_tv001\n");
}

static void test_now_null_tv001(void) {
    uint64_t out_ret = scheduler_now(NULL);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_now_null_tv001\n");
}

static void test_now_valid_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    uint64_t out_ret = scheduler_now(s);
    assert(out_ret == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_now_valid_tv001\n");
}

static void test_now_ir_if_0_not_s_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    s = 0;
    uint64_t out_ret = scheduler_now(s);
    assert(out_ret == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_now_ir_if_0_not_s_tv001\n");
}

static void test_now_ir_if_0_false_not_s_tv001(void) {
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    void scheduler_free(Scheduler *arg0);
    assert(s != NULL);
    uint64_t out_ret = scheduler_now(s);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_now_ir_if_0_false_not_s_tv001\n");
}

int main(void) {
    __kleva_alloc_reset();
    test_create_bad_tv001();
    __kleva_alloc_reset();
    test_create_ok_tv001();
    __kleva_alloc_reset();
    test_create_ir_if_0_capacity_eq_0_tv001();
    __kleva_alloc_reset();
    test_create_ir_if_0_false_capacity_ne_0_tv001();
    __kleva_alloc_reset();
    test_create_ir_alloc_malloc_0_zero_failure_tv001();
    __kleva_alloc_reset();
    test_create_ir_alloc_malloc_0_zero_success_tv001();
    __kleva_alloc_reset();
    test_create_ir_callee_event_queue_create_zero_failure_tv001();
    __kleva_alloc_reset();
    test_create_ir_callee_event_queue_create_zero_success_tv001();
    __kleva_alloc_reset();
    test_create_ir_forbidden_value_0_capacity_eq_0_forbidden_tv001();
    __kleva_alloc_reset();
    test_create_ir_forbidden_value_0_capacity_eq_0_allowed_tv001();
    __kleva_alloc_reset();
    test_create_ir_diversity_capacity_one_tv001();
    __kleva_alloc_reset();
    test_create_ir_diversity_capacity_two_tv001();
    __kleva_alloc_reset();
    test_free_valid_tv001();
    __kleva_alloc_reset();
    test_register_null_tv001();
    __kleva_alloc_reset();
    test_register_valid_tv001();
    __kleva_alloc_reset();
    test_register_ir_if_0_left_left_not_s_tv001();
    __kleva_alloc_reset();
    test_register_ir_if_0_left_right_type_lt_0_tv001();
    __kleva_alloc_reset();
    test_register_ir_if_0_right_type_ge_EVT_TYPE_COUNT_tv001();
    __kleva_alloc_reset();
    test_register_ir_if_0_false_false_not_s_and_false_type_ge_0_and_false_type_lt_EVT_TYPE_COUNT_tv001();
    __kleva_alloc_reset();
    test_register_ir_min_guard_0_type_lt_0_too_low_tv001();
    __kleva_alloc_reset();
    test_register_ir_min_guard_0_type_lt_0_valid_high_tv001();
    __kleva_alloc_reset();
    test_schedule_null_tv001();
    __kleva_alloc_reset();
    test_schedule_valid_tv001();
    __kleva_alloc_reset();
    test_schedule_ir_if_0_left_not_s_tv001();
    __kleva_alloc_reset();
    test_schedule_ir_if_0_right_not_e_tv001();
    __kleva_alloc_reset();
    test_step_valid_tv001();
    __kleva_alloc_reset();
    test_step_ir_callee_event_queue_pop_zero_failure_tv001();
    __kleva_alloc_reset();
    test_step_ir_callee_event_queue_pop_zero_success_tv001();
    __kleva_alloc_reset();
    test_run_valid_tv001();
    __kleva_alloc_reset();
    test_stop_null_tv001();
    __kleva_alloc_reset();
    test_stop_valid_tv001();
    __kleva_alloc_reset();
    test_stop_ir_if_0_truthy_s_tv001();
    __kleva_alloc_reset();
    test_stop_ir_if_0_false_truthy_s_tv001();
    __kleva_alloc_reset();
    test_now_null_tv001();
    __kleva_alloc_reset();
    test_now_valid_tv001();
    __kleva_alloc_reset();
    test_now_ir_if_0_not_s_tv001();
    __kleva_alloc_reset();
    test_now_ir_if_0_false_not_s_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
