/* AUTO-GENERATED by scripts/gen_tests.py — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not Python reimplementations.
 * Re-generate: make gen-tests
 * Generated: 2026-05-15 16:23:32
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "../../src/network/packet.h"

static void test_checksum_tv001(void) {
    uint8_t data[4] = {0x00, 0x00, 0x00, 0x00};
    uint16_t cs = packet_checksum(data, 4);
    uint8_t  buf[6];
    memcpy(buf, data, 4);
    buf[4] = (uint8_t)(cs & 0xFF);
    buf[5] = (uint8_t)((cs >> 8) & 0xFF);
    uint16_t verify = packet_checksum(buf, 6);
    assert(cs == 65535); /* EVA-proven oracle */
    /* NOTE: EVA did not prove singleton for 'verify' */
    printf("PASS test_checksum_tv001\n");
}

static void test_checksum_tv002(void) {
    uint8_t data[4] = {0xFF, 0xFF, 0xFF, 0xFF};
    uint16_t cs = packet_checksum(data, 4);
    uint8_t  buf[6];
    memcpy(buf, data, 4);
    buf[4] = (uint8_t)(cs & 0xFF);
    buf[5] = (uint8_t)((cs >> 8) & 0xFF);
    uint16_t verify = packet_checksum(buf, 6);
    assert(cs == 0); /* EVA-proven oracle */
    /* NOTE: EVA did not prove singleton for 'verify' */
    printf("PASS test_checksum_tv002\n");
}

static void test_create_tv001(void) {
    Packet *p = packet_create((size_t)255ULL);
    assert(p != NULL);
    size_t out_len   = p->len;
    size_t out_cap   = p->capacity;
    int    out_layer = p->layer;
    assert(out_len == 0); /* EVA-proven oracle */
    assert(out_cap == 255); /* EVA-proven oracle */
    assert(out_layer == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_create_tv001\n");
}

static void test_prepend_tv001(void) {
    uint8_t hdr[66] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)66ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 66); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv001\n");
}

static void test_prepend_tv004(void) {
    uint8_t hdr[1] = {0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)1ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv004\n");
}

static void test_prepend_tv005(void) {
    uint8_t hdr[2] = {0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)2ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 2); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv005\n");
}

static void test_prepend_tv006(void) {
    uint8_t hdr[3] = {0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)3ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 3); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv006\n");
}

static void test_prepend_tv007(void) {
    uint8_t hdr[5] = {0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)5ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 5); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv007\n");
}

static void test_prepend_tv008(void) {
    uint8_t hdr[4] = {0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)4ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 4); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv008\n");
}

static void test_prepend_tv009(void) {
    uint8_t hdr[6] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)6ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 6); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv009\n");
}

static void test_prepend_tv010(void) {
    uint8_t hdr[7] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)7ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 7); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv010\n");
}

static void test_prepend_tv011(void) {
    uint8_t hdr[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)8ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 8); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv011\n");
}

static void test_prepend_tv012(void) {
    uint8_t hdr[9] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)9ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 9); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv012\n");
}

static void test_prepend_tv013(void) {
    uint8_t hdr[10] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)10ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 10); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv013\n");
}

static void test_prepend_tv014(void) {
    uint8_t hdr[11] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)11ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 11); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv014\n");
}

static void test_prepend_tv015(void) {
    uint8_t hdr[12] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)12ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 12); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv015\n");
}

static void test_prepend_tv016(void) {
    uint8_t hdr[13] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)13ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 13); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv016\n");
}

static void test_prepend_tv017(void) {
    uint8_t hdr[14] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)14ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 14); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv017\n");
}

static void test_prepend_tv018(void) {
    uint8_t hdr[15] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)15ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 15); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv018\n");
}

static void test_prepend_tv019(void) {
    uint8_t hdr[16] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)16ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 16); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv019\n");
}

static void test_prepend_tv020(void) {
    uint8_t hdr[17] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)17ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 17); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv020\n");
}

static void test_prepend_tv021(void) {
    uint8_t hdr[18] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)18ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 18); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv021\n");
}

static void test_prepend_tv022(void) {
    uint8_t hdr[19] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)19ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 19); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv022\n");
}

static void test_prepend_tv023(void) {
    uint8_t hdr[20] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)20ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 20); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv023\n");
}

static void test_prepend_tv024(void) {
    uint8_t hdr[21] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)21ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 21); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv024\n");
}

static void test_prepend_tv025(void) {
    uint8_t hdr[22] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)22ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 22); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv025\n");
}

static void test_prepend_tv026(void) {
    uint8_t hdr[23] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)23ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 23); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv026\n");
}

static void test_prepend_tv027(void) {
    uint8_t hdr[24] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)24ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 24); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv027\n");
}

static void test_prepend_tv028(void) {
    uint8_t hdr[25] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)25ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 25); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv028\n");
}

static void test_prepend_tv029(void) {
    uint8_t hdr[26] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)26ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 26); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv029\n");
}

static void test_prepend_tv030(void) {
    uint8_t hdr[27] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)27ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 27); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv030\n");
}

static void test_prepend_tv031(void) {
    uint8_t hdr[28] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)28ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 28); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv031\n");
}

static void test_prepend_tv032(void) {
    uint8_t hdr[29] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)29ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 29); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv032\n");
}

static void test_prepend_tv033(void) {
    uint8_t hdr[30] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)30ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 30); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv033\n");
}

static void test_prepend_tv034(void) {
    uint8_t hdr[31] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)31ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 31); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv034\n");
}

static void test_prepend_tv035(void) {
    uint8_t hdr[32] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)32ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 32); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv035\n");
}

static void test_prepend_tv036(void) {
    uint8_t hdr[33] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)33ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 33); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv036\n");
}

static void test_prepend_tv037(void) {
    uint8_t hdr[34] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)34ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 34); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv037\n");
}

static void test_prepend_tv038(void) {
    uint8_t hdr[35] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)35ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 35); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv038\n");
}

static void test_prepend_tv039(void) {
    uint8_t hdr[36] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)36ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 36); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv039\n");
}

static void test_prepend_tv040(void) {
    uint8_t hdr[37] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)37ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 37); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv040\n");
}

static void test_prepend_tv041(void) {
    uint8_t hdr[38] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)38ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 38); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv041\n");
}

static void test_prepend_tv042(void) {
    uint8_t hdr[39] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)39ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 39); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv042\n");
}

static void test_prepend_tv043(void) {
    uint8_t hdr[40] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)40ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 40); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv043\n");
}

static void test_prepend_tv044(void) {
    uint8_t hdr[96] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)96ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 96); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv044\n");
}

static void test_prepend_tv045(void) {
    uint8_t hdr[41] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)41ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 41); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv045\n");
}

static void test_prepend_tv046(void) {
    uint8_t hdr[42] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)42ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 42); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv046\n");
}

static void test_prepend_tv047(void) {
    uint8_t hdr[43] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)43ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 43); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv047\n");
}

static void test_prepend_tv048(void) {
    uint8_t hdr[44] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)44ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 44); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv048\n");
}

static void test_prepend_tv049(void) {
    uint8_t hdr[45] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)45ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 45); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv049\n");
}

static void test_prepend_tv050(void) {
    uint8_t hdr[46] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)46ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 46); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv050\n");
}

static void test_prepend_tv051(void) {
    uint8_t hdr[47] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)47ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 47); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv051\n");
}

static void test_prepend_tv052(void) {
    uint8_t hdr[48] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)48ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 48); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv052\n");
}

static void test_prepend_tv053(void) {
    uint8_t hdr[49] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)49ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 49); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv053\n");
}

static void test_prepend_tv054(void) {
    uint8_t hdr[50] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)50ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 50); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv054\n");
}

static void test_prepend_tv055(void) {
    uint8_t hdr[51] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)51ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 51); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv055\n");
}

static void test_prepend_tv056(void) {
    uint8_t hdr[52] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)52ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 52); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv056\n");
}

static void test_prepend_tv057(void) {
    uint8_t hdr[53] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)53ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 53); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv057\n");
}

static void test_prepend_tv058(void) {
    uint8_t hdr[54] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)54ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 54); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv058\n");
}

static void test_prepend_tv059(void) {
    uint8_t hdr[55] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)55ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 55); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv059\n");
}

static void test_prepend_tv060(void) {
    uint8_t hdr[56] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)56ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 56); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv060\n");
}

static void test_prepend_tv061(void) {
    uint8_t hdr[57] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)57ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 57); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv061\n");
}

static void test_prepend_tv062(void) {
    uint8_t hdr[58] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)58ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 58); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv062\n");
}

static void test_prepend_tv063(void) {
    uint8_t hdr[59] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)59ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 59); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv063\n");
}

static void test_prepend_tv064(void) {
    uint8_t hdr[60] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)60ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 60); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv064\n");
}

static void test_prepend_tv065(void) {
    uint8_t hdr[61] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)61ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 61); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv065\n");
}

static void test_prepend_tv066(void) {
    uint8_t hdr[62] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)62ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 62); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv066\n");
}

static void test_prepend_tv067(void) {
    uint8_t hdr[63] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)63ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 63); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv067\n");
}

static void test_prepend_tv068(void) {
    uint8_t hdr[64] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
    Packet *p = packet_create(1024);
    assert(p != NULL);
    int    out_ret = packet_prepend(p, hdr, (size_t)64ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 64); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_tv068\n");
}

static void test_strip_tv001(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)22ULL);
    size_t out_len = p->len;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_len == 20); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv001\n");
}

static void test_strip_tv002(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)0ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 20); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv002\n");
}

static void test_strip_tv003(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)20ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv003\n");
}

static void test_strip_tv004(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)19ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv004\n");
}

static void test_strip_tv005(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)18ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 2); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv005\n");
}

static void test_strip_tv006(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)17ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 3); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv006\n");
}

static void test_strip_tv007(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)16ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 4); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv007\n");
}

static void test_strip_tv008(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)15ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 5); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv008\n");
}

static void test_strip_tv009(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)14ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 6); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv009\n");
}

static void test_strip_tv010(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)13ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 7); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv010\n");
}

static void test_strip_tv011(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)12ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 8); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv011\n");
}

static void test_strip_tv012(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)11ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 9); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv012\n");
}

static void test_strip_tv013(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)10ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 10); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv013\n");
}

static void test_strip_tv014(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)9ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 11); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv014\n");
}

static void test_strip_tv015(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)8ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 12); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv015\n");
}

static void test_strip_tv016(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)7ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 13); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv016\n");
}

static void test_strip_tv017(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)6ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 14); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv017\n");
}

static void test_strip_tv018(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)5ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 15); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv018\n");
}

static void test_strip_tv019(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)4ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 16); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv019\n");
}

static void test_strip_tv020(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)3ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 17); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv020\n");
}

static void test_strip_tv021(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)2ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 18); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv021\n");
}

static void test_strip_tv022(void) {
    uint8_t payload[20] = {0};
    Packet *p = packet_create(128);
    assert(p != NULL);
    packet_prepend(p, payload, 20);
    int    out_ret = packet_strip(p, (size_t)1ULL);
    size_t out_len = p->len;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_len == 19); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_tv022\n");
}

static void test_clone_tv001(void) {
    uint8_t hdr[4] = {0xDE, 0xAD, 0xBE, 0xEF};
    Packet *p = packet_create(64);
    assert(p != NULL);
    packet_prepend(p, hdr, 4);
    p->layer = 2;
    Packet *c = packet_clone(p);
    assert(c != NULL);
    size_t out_clone_len   = c->len;
    int    out_clone_layer = c->layer;
    /* NOTE: EVA did not prove singleton for 'out_clone_len' */
    /* NOTE: EVA did not prove singleton for 'out_clone_layer' */
    packet_free(c);
    packet_free(p);
    printf("PASS test_clone_tv001\n");
}

int main(void) {
    test_checksum_tv001();
    test_checksum_tv002();
    test_create_tv001();
    test_prepend_tv001();
    test_prepend_tv004();
    test_prepend_tv005();
    test_prepend_tv006();
    test_prepend_tv007();
    test_prepend_tv008();
    test_prepend_tv009();
    test_prepend_tv010();
    test_prepend_tv011();
    test_prepend_tv012();
    test_prepend_tv013();
    test_prepend_tv014();
    test_prepend_tv015();
    test_prepend_tv016();
    test_prepend_tv017();
    test_prepend_tv018();
    test_prepend_tv019();
    test_prepend_tv020();
    test_prepend_tv021();
    test_prepend_tv022();
    test_prepend_tv023();
    test_prepend_tv024();
    test_prepend_tv025();
    test_prepend_tv026();
    test_prepend_tv027();
    test_prepend_tv028();
    test_prepend_tv029();
    test_prepend_tv030();
    test_prepend_tv031();
    test_prepend_tv032();
    test_prepend_tv033();
    test_prepend_tv034();
    test_prepend_tv035();
    test_prepend_tv036();
    test_prepend_tv037();
    test_prepend_tv038();
    test_prepend_tv039();
    test_prepend_tv040();
    test_prepend_tv041();
    test_prepend_tv042();
    test_prepend_tv043();
    test_prepend_tv044();
    test_prepend_tv045();
    test_prepend_tv046();
    test_prepend_tv047();
    test_prepend_tv048();
    test_prepend_tv049();
    test_prepend_tv050();
    test_prepend_tv051();
    test_prepend_tv052();
    test_prepend_tv053();
    test_prepend_tv054();
    test_prepend_tv055();
    test_prepend_tv056();
    test_prepend_tv057();
    test_prepend_tv058();
    test_prepend_tv059();
    test_prepend_tv060();
    test_prepend_tv061();
    test_prepend_tv062();
    test_prepend_tv063();
    test_prepend_tv064();
    test_prepend_tv065();
    test_prepend_tv066();
    test_prepend_tv067();
    test_prepend_tv068();
    test_strip_tv001();
    test_strip_tv002();
    test_strip_tv003();
    test_strip_tv004();
    test_strip_tv005();
    test_strip_tv006();
    test_strip_tv007();
    test_strip_tv008();
    test_strip_tv009();
    test_strip_tv010();
    test_strip_tv011();
    test_strip_tv012();
    test_strip_tv013();
    test_strip_tv014();
    test_strip_tv015();
    test_strip_tv016();
    test_strip_tv017();
    test_strip_tv018();
    test_strip_tv019();
    test_strip_tv020();
    test_strip_tv021();
    test_strip_tv022();
    test_clone_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
