/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-07-02 16:36:27
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "packet.h"

/* KLEVA native compile note:
 * This generated test includes allocator-failure candidates.
 * Compile the module-under-test with:
 *   -Dmalloc=__kleva_malloc -Dcalloc=__kleva_calloc -Drealloc=__kleva_realloc -Dfree=__kleva_free
 */

#include "packet.h"
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#ifdef malloc
#undef malloc
#endif
#ifdef calloc
#undef calloc
#endif
#ifdef realloc
#undef realloc
#endif
#ifdef free
#undef free
#endif
static unsigned char __kleva_alloc_arena[1024u * 1024u];
struct __kleva_alloc_rec {
    void *ptr;
    size_t size;
    int active;
};
static struct __kleva_alloc_rec __kleva_alloc_recs[1024];
static size_t __kleva_alloc_offset;
static long __kleva_alloc_call;
static long __kleva_alloc_fail_at = -1;
static void __kleva_alloc_reset(void) {
    __kleva_alloc_offset = 0;
    __kleva_alloc_call = 0;
    __kleva_alloc_fail_at = -1;
    memset(__kleva_alloc_recs, 0, sizeof(__kleva_alloc_recs));
}
static void __kleva_alloc_record(void *ptr, size_t size) {
    if (!ptr) {
        return;
    }
    for (size_t i = 0; i < sizeof(__kleva_alloc_recs) / sizeof(__kleva_alloc_recs[0]); i++) {
        if (!__kleva_alloc_recs[i].active) {
            __kleva_alloc_recs[i].ptr = ptr;
            __kleva_alloc_recs[i].size = size;
            __kleva_alloc_recs[i].active = 1;
            return;
        }
    }
}
static size_t __kleva_alloc_size_of(void *ptr) {
    for (size_t i = 0; i < sizeof(__kleva_alloc_recs) / sizeof(__kleva_alloc_recs[0]); i++) {
        if (__kleva_alloc_recs[i].active && __kleva_alloc_recs[i].ptr == ptr) {
            return __kleva_alloc_recs[i].size;
        }
    }
    return 0;
}
static void __kleva_alloc_forget(void *ptr) {
    for (size_t i = 0; i < sizeof(__kleva_alloc_recs) / sizeof(__kleva_alloc_recs[0]); i++) {
        if (__kleva_alloc_recs[i].active && __kleva_alloc_recs[i].ptr == ptr) {
            __kleva_alloc_recs[i].active = 0;
            return;
        }
    }
}
static void __kleva_alloc_fail_on(long index) {
    __kleva_alloc_fail_at = __kleva_alloc_call + index;
}
void *__kleva_malloc(size_t size) {
    if (__kleva_alloc_fail_at >= 0 && __kleva_alloc_call == __kleva_alloc_fail_at) {
        __kleva_alloc_call++;
        __kleva_alloc_fail_at = -1;
        return (void *)0;
    }
    __kleva_alloc_call++;
    if (size == 0) {
        size = 1;
    }
    size = (size + 7u) & ~((size_t)7u);
    if (size > sizeof(__kleva_alloc_arena) - __kleva_alloc_offset) {
        return (void *)0;
    }
    void *ptr = __kleva_alloc_arena + __kleva_alloc_offset;
    __kleva_alloc_offset += size;
    __kleva_alloc_record(ptr, size);
    return ptr;
}
void __kleva_free(void *ptr) {
    __kleva_alloc_forget(ptr);
}
void *__kleva_calloc(size_t count, size_t size) {
    size_t total = count * size;
    void *ptr = __kleva_malloc(total);
    if (ptr) {
        memset(ptr, 0, total);
    }
    return ptr;
}
void *__kleva_realloc(void *ptr, size_t size) {
    if (!ptr) {
        return __kleva_malloc(size);
    }
    if (size == 0) {
        __kleva_free(ptr);
        return (void *)0;
    }
    size_t old_size = __kleva_alloc_size_of(ptr);
    void *new_ptr = __kleva_malloc(size);
    if (!new_ptr) {
        return (void *)0;
    }
    if (old_size > 0) {
        size_t copy_size = old_size < size ? old_size : size;
        memcpy(new_ptr, ptr, copy_size);
    }
    __kleva_alloc_forget(ptr);
    return new_ptr;
}

static void test_create_valid_tv001(void) {
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 1); /* EVA-proven oracle */
    printf("PASS test_create_valid_tv001\n");
}

static void test_create_ir_alloc_malloc_0_zero_failure_tv001(void) {
    __kleva_alloc_reset();
    __kleva_alloc_fail_on(0);
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_capacity == 0); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_0_zero_failure_tv001\n");
}

static void test_create_ir_alloc_malloc_0_zero_success_tv001(void) {
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_0_zero_success_tv001\n");
}

static void test_create_ir_diversity_capacity_one_tv001(void) {
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_capacity_one_tv001\n");
}

static void test_create_ir_diversity_capacity_two_tv001(void) {
    Packet * out_ret = packet_create(2);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 2); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_capacity_two_tv001\n");
}

static void test_prepend_valid_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    uintptr_t kleva_old_ir_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_len = (uintptr_t)(p->len);
    int out_ret = packet_prepend(p, header, 1);
    int out_ir_post_p_data = ((uintptr_t)(p->data) == (uintptr_t)((kleva_old_ir_p_data - 1)));
    int out_ir_post_p_len = ((uintptr_t)(p->len) == (uintptr_t)((kleva_old_ir_p_len + 1)));
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_ir_post_p_data == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_valid_tv001\n");
}

static void test_prepend_ok_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    p->data = p->head + 1;
    uintptr_t kleva_old_p_len = (uintptr_t)(p->len);
    uintptr_t kleva_old_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_len = (uintptr_t)(p->len);
    int out_ret = packet_prepend(p, header, 1);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    int out_post_p_len_header_len = ((uintptr_t)(p->len) == (kleva_old_p_len + (uintptr_t)(1)));
    int out_post_p_data_header_len = ((uintptr_t)(p->data) == (kleva_old_p_data - (uintptr_t)(1)));
    int out_ir_post_p_data = ((uintptr_t)(p->data) == (uintptr_t)((kleva_old_ir_p_data - 1)));
    int out_ir_post_p_len = ((uintptr_t)(p->len) == (uintptr_t)((kleva_old_ir_p_len + 1)));
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    assert(out_post_p_len_header_len == 1); /* EVA-proven oracle */
    assert(out_post_p_data_header_len == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_data == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_ok_tv001\n");
}

static void test_prepend_no_headroom_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    p->data = p->head;
    uintptr_t kleva_old_p_len = (uintptr_t)(p->len);
    int out_ret = packet_prepend(p, header, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    int out_post_p_len = ((uintptr_t)(p->len) == kleva_old_p_len);
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    assert(out_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_no_headroom_tv001\n");
}

static void test_prepend_ir_if_0_header_len_gt_size_t_p_data_p_head_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    int out_ret = packet_prepend(p, header, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_ir_if_0_header_len_gt_size_t_p_data_p_head_tv001\n");
}

static void test_prepend_ir_if_0_false_header_len_le_size_t_p_data_p_head_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    int out_ret = packet_prepend(p, header, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_prepend_ir_if_0_false_header_len_le_size_t_p_data_p_head_tv001\n");
}

static void test_prepend_ir_diversity_header_len_one_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    int out_ret = packet_prepend(p, header, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_ir_diversity_header_len_one_tv001\n");
}

static void test_prepend_ir_diversity_header_len_two_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    int out_ret = packet_prepend(p, header, 2);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_ir_diversity_header_len_two_tv001\n");
}

static void test_strip_valid_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uintptr_t kleva_old_ir_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_len = (uintptr_t)(p->len);
    int out_ret = packet_strip(p, 1);
    int out_ir_post_p_data = ((uintptr_t)(p->data) == (uintptr_t)((kleva_old_ir_p_data + 1)));
    int out_ir_post_p_len = ((uintptr_t)(p->len) == (uintptr_t)((kleva_old_ir_p_len - 1)));
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_ir_post_p_data == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_valid_tv001\n");
}

static void test_strip_valid_strip_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    p->len = 1;
    uintptr_t kleva_old_p_len = (uintptr_t)(p->len);
    uintptr_t kleva_old_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_len = (uintptr_t)(p->len);
    int out_ret = packet_strip(p, 1);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    int out_post_p_len_header_len = ((uintptr_t)(p->len) == (kleva_old_p_len - (uintptr_t)(1)));
    int out_post_p_data_header_len = ((uintptr_t)(p->data) == (kleva_old_p_data + (uintptr_t)(1)));
    int out_ir_post_p_data = ((uintptr_t)(p->data) == (uintptr_t)((kleva_old_ir_p_data + 1)));
    int out_ir_post_p_len = ((uintptr_t)(p->len) == (uintptr_t)((kleva_old_ir_p_len - 1)));
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    assert(out_post_p_len_header_len == 1); /* EVA-proven oracle */
    assert(out_post_p_data_header_len == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_data == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_valid_strip_tv001\n");
}

static void test_strip_overflow_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    p->len = ((1) > 0 ? (1) - 1 : 0);
    uintptr_t kleva_old_p_len = (uintptr_t)(p->len);
    uintptr_t kleva_old_p_data = (uintptr_t)(p->data);
    int out_ret = packet_strip(p, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    int out_post_p_len = ((uintptr_t)(p->len) == kleva_old_p_len);
    int out_post_p_data = ((uintptr_t)(p->data) == kleva_old_p_data);
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    assert(out_post_p_len == 1); /* EVA-proven oracle */
    assert(out_post_p_data == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_overflow_tv001\n");
}

static void test_strip_ir_if_0_header_len_gt_p_len_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    int out_ret = packet_strip(p, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_ir_if_0_header_len_gt_p_len_tv001\n");
}

static void test_strip_ir_if_0_false_header_len_le_p_len_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    int out_ret = packet_strip(p, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_false_header_len_le_p_len_tv001\n");
}

static void test_strip_ir_diversity_header_len_zero_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    int out_ret = packet_strip(p, 0);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_ir_diversity_header_len_zero_tv001\n");
}

static void test_strip_ir_diversity_header_len_one_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    int out_ret = packet_strip(p, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_ir_diversity_header_len_one_tv001\n");
}

static void test_strip_ir_diversity_header_len_two_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    int out_ret = packet_strip(p, 2);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_ir_diversity_header_len_two_tv001\n");
}

static void test_clone_valid_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t p_data_buffer[64];
    memset(p_data_buffer, 0, sizeof(p_data_buffer));
    if (p->data == NULL) p->data = p_data_buffer;
    memset(p->data, 0, p->len);
    Packet * out_ret = packet_clone(p);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_clone_valid_tv001\n");
}

static void test_clone_ir_callee_packet_create_zero_failure_tv001(void) {
    __kleva_alloc_reset();
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    __kleva_alloc_fail_on(0);
    uint8_t p_data_buffer[64];
    memset(p_data_buffer, 0, sizeof(p_data_buffer));
    if (p->data == NULL) p->data = p_data_buffer;
    memset(p->data, 0, p->len);
    Packet * out_ret = packet_clone(p);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_clone_ir_callee_packet_create_zero_failure_tv001\n");
}

static void test_clone_ir_callee_packet_create_zero_success_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t p_data_buffer[64];
    memset(p_data_buffer, 0, sizeof(p_data_buffer));
    if (p->data == NULL) p->data = p_data_buffer;
    memset(p->data, 0, p->len);
    Packet * out_ret = packet_clone(p);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_clone_ir_callee_packet_create_zero_success_tv001\n");
}

static void test_free_null_tv001(void) {
    packet_free(NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_free_null_tv001\n");
}

static void test_free_valid_tv001(void) {
    void *malloc(size_t size);
    Packet *p = malloc(sizeof(Packet));
    if (p) memset(p, 0, sizeof(*p));
    packet_free(p);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_free_valid_tv001\n");
}

static void test_checksum_valid_tv001(void) {
    uint8_t data_buf[256];
    memset(data_buf, 0, sizeof(data_buf));
    const void * data = data_buf;
    uint16_t out_ret = packet_checksum(data, 1);
    assert(out_ret == 65535); /* EVA-proven oracle */
    printf("PASS test_checksum_valid_tv001\n");
}

static void test_checksum_ir_diversity_len_one_tv001(void) {
    uint8_t data_buf[256];
    memset(data_buf, 0, sizeof(data_buf));
    const void * data = data_buf;
    uint16_t out_ret = packet_checksum(data, 1);
    assert(out_ret == 65535); /* EVA-proven oracle */
    printf("PASS test_checksum_ir_diversity_len_one_tv001\n");
}

static void test_checksum_ir_diversity_len_two_tv001(void) {
    uint8_t data_buf[256];
    memset(data_buf, 0, sizeof(data_buf));
    const void * data = data_buf;
    uint16_t out_ret = packet_checksum(data, 2);
    assert(out_ret == 65535); /* EVA-proven oracle */
    printf("PASS test_checksum_ir_diversity_len_two_tv001\n");
}

static void test_dump_valid_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    packet_dump(p);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_dump_valid_tv001\n");
}

int main(void) {
    __kleva_alloc_reset();
    test_create_valid_tv001();
    __kleva_alloc_reset();
    test_create_ir_alloc_malloc_0_zero_failure_tv001();
    __kleva_alloc_reset();
    test_create_ir_alloc_malloc_0_zero_success_tv001();
    __kleva_alloc_reset();
    test_create_ir_diversity_capacity_one_tv001();
    __kleva_alloc_reset();
    test_create_ir_diversity_capacity_two_tv001();
    __kleva_alloc_reset();
    test_prepend_valid_tv001();
    __kleva_alloc_reset();
    test_prepend_ok_tv001();
    __kleva_alloc_reset();
    test_prepend_no_headroom_tv001();
    __kleva_alloc_reset();
    test_prepend_ir_if_0_header_len_gt_size_t_p_data_p_head_tv001();
    __kleva_alloc_reset();
    test_prepend_ir_if_0_false_header_len_le_size_t_p_data_p_head_tv001();
    __kleva_alloc_reset();
    test_prepend_ir_diversity_header_len_one_tv001();
    __kleva_alloc_reset();
    test_prepend_ir_diversity_header_len_two_tv001();
    __kleva_alloc_reset();
    test_strip_valid_tv001();
    __kleva_alloc_reset();
    test_strip_valid_strip_tv001();
    __kleva_alloc_reset();
    test_strip_overflow_tv001();
    __kleva_alloc_reset();
    test_strip_ir_if_0_header_len_gt_p_len_tv001();
    __kleva_alloc_reset();
    test_strip_ir_if_0_false_header_len_le_p_len_tv001();
    __kleva_alloc_reset();
    test_strip_ir_diversity_header_len_zero_tv001();
    __kleva_alloc_reset();
    test_strip_ir_diversity_header_len_one_tv001();
    __kleva_alloc_reset();
    test_strip_ir_diversity_header_len_two_tv001();
    __kleva_alloc_reset();
    test_clone_valid_tv001();
    __kleva_alloc_reset();
    test_clone_ir_callee_packet_create_zero_failure_tv001();
    __kleva_alloc_reset();
    test_clone_ir_callee_packet_create_zero_success_tv001();
    __kleva_alloc_reset();
    test_free_null_tv001();
    __kleva_alloc_reset();
    test_free_valid_tv001();
    __kleva_alloc_reset();
    test_checksum_valid_tv001();
    __kleva_alloc_reset();
    test_checksum_ir_diversity_len_one_tv001();
    __kleva_alloc_reset();
    test_checksum_ir_diversity_len_two_tv001();
    __kleva_alloc_reset();
    test_dump_valid_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
