/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-27 18:17:47
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "icmp.h"

#include "packet.h"
#include "icmp.h"
#include "interface.h"
#include "ip.h"
#include "scheduler.h"
#include "topology.h"
#include "simulator.h"

static void test_receive_null_iface_tv001(void) {
    void *malloc(size_t size);
    Packet *pkt = malloc(sizeof(Packet));
    if (pkt) memset(pkt, 0, sizeof(*pkt));
    uint8_t pkt_data[64];
    memset(pkt_data, 0, sizeof(pkt_data));
    if (pkt->data == NULL) pkt->data = pkt_data;
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    int out_ret = icmp_receive(NULL, pkt, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_receive_null_iface_tv001\n");
}

static void test_receive_null_pkt_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    int out_ret = icmp_receive(iface, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_null_pkt_tv001\n");
}

static void test_receive_too_short_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    void *malloc(size_t size);
    Packet *pkt = malloc(sizeof(Packet));
    if (pkt) memset(pkt, 0, sizeof(*pkt));
    uint8_t pkt_data[64];
    memset(pkt_data, 0, sizeof(pkt_data));
    if (pkt->data == NULL) pkt->data = pkt_data;
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    pkt->len = ((ICMP_HDR_LEN) > 0 ? (ICMP_HDR_LEN) - 1 : 0);
    int out_ret = icmp_receive(iface, pkt, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_too_short_tv001\n");
}

static void test_receive_missing_stripped_ip_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    void *malloc(size_t size);
    Packet *pkt = malloc(sizeof(Packet));
    if (pkt) memset(pkt, 0, sizeof(*pkt));
    uint8_t pkt_data[64];
    memset(pkt_data, 0, sizeof(pkt_data));
    if (pkt->data == NULL) pkt->data = pkt_data;
    if (pkt->len == 0) pkt->len = 8;
    memset(pkt->data, 0, pkt->len);
    pkt->len = ICMP_HDR_LEN;
    pkt->data = pkt->head;
    int out_ret = icmp_receive(iface, pkt, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_missing_stripped_ip_tv001\n");
}

static void test_send_echo_request_null_input_tv001(void) {
    int out_ret = icmp_send_echo_request(NULL, 0, 0, 0, 0, NULL, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_echo_request_null_input_tv001\n");
}

static void test_send_echo_request_valid_tv001(void) {
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    int out_ret = icmp_send_echo_request(sim, 0, 0, 0, 0, payload, 0);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_valid_tv001\n");
}

static void test_send_echo_request_ir_if_0_not_sim_tv001(void) {
    int out_ok = 1;
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    sim = 0;
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, 0);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_if_0_not_sim_tv001\n");
}

static void test_send_echo_request_ir_if_1_payload_len_gt_0_and_not_payload_tv001(void) {
    int out_ok = 1;
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    size_t payload_len = 0;
    payload_len = ((0) + 1);
    payload = 0;
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, payload_len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_if_1_payload_len_gt_0_and_not_payload_tv001\n");
}

static void test_send_echo_request_ir_if_1_false_left_false_payload_len_le_0_tv001(void) {
    int out_ok = 1;
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    size_t payload_len = 0;
    payload_len = 0;
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, payload_len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_if_1_false_left_false_payload_len_le_0_tv001\n");
}

static void test_send_echo_request_ir_if_3_payload_len_gt_0_tv001(void) {
    int out_ok = 1;
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    size_t payload_len = 0;
    payload_len = ((0) + 1);
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, payload_len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_if_3_payload_len_gt_0_tv001\n");
}

static void test_send_echo_request_ir_if_3_false_payload_len_le_0_tv001(void) {
    int out_ok = 1;
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    size_t payload_len = 0;
    payload_len = 0;
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, payload_len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_if_3_false_payload_len_le_0_tv001\n");
}

static void test_send_echo_request_ir_callee_packet_create_zero_failure_tv001(void) {
    int out_ok = 1;
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, 0);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_callee_packet_create_zero_failure_tv001\n");
}

static void test_send_echo_request_ir_callee_packet_create_zero_success_tv001(void) {
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, 0);
    int out_sim_topo_nonnull = (sim->topo != NULL);
    int out_sim_sched_nonnull = (sim->sched != NULL);
    uint64_t out_sim_end_time = sim->end_time;
    assert(out_sim_topo_nonnull == 1); /* EVA-proven oracle */
    assert(out_sim_sched_nonnull == 1); /* EVA-proven oracle */
    assert(out_sim_end_time == 0); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_callee_packet_create_zero_success_tv001\n");
}

static void test_send_echo_request_ir_max_guard_1_payload_len_gt_0_valid_low_tv001(void) {
    int out_ok = 1;
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    size_t payload_len = 0;
    payload_len = 0;
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, payload_len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_max_guard_1_payload_len_gt_0_valid_low_tv001\n");
}

static void test_send_echo_request_ir_max_guard_1_payload_len_gt_0_boundary_tv001(void) {
    int out_ok = 1;
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    size_t payload_len = 0;
    payload_len = 0;
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, payload_len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_max_guard_1_payload_len_gt_0_boundary_tv001\n");
}

static void test_send_echo_request_ir_max_guard_1_payload_len_gt_0_too_high_tv001(void) {
    int out_ok = 1;
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    const uint8_t * payload = payload_buf;
    size_t payload_len = 0;
    payload_len = 1;
    icmp_send_echo_request(sim, 0, 0, 0, 0, payload, payload_len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_ir_max_guard_1_payload_len_gt_0_too_high_tv001\n");
}

static void test_send_echo_reply_null_input_tv001(void) {
    int out_ret = icmp_send_echo_reply(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_echo_reply_null_input_tv001\n");
}

static void test_send_echo_reply_too_short_tv001(void) {
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    void *malloc(size_t size);
    Packet *req_pkt = malloc(sizeof(Packet));
    if (req_pkt) memset(req_pkt, 0, sizeof(*req_pkt));
    uint8_t req_pkt_data[64];
    memset(req_pkt_data, 0, sizeof(req_pkt_data));
    if (req_pkt->data == NULL) req_pkt->data = req_pkt_data;
    if (req_pkt->len == 0) req_pkt->len = 8;
    memset(req_pkt->data, 0, req_pkt->len);
    req_pkt->len = ((ICMP_HDR_LEN) > 0 ? (ICMP_HDR_LEN) - 1 : 0);
    int out_ret = icmp_send_echo_reply(sim, iface, req_pkt);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    printf("PASS test_send_echo_reply_too_short_tv001\n");
}

static void test_send_echo_reply_missing_stripped_ip_tv001(void) {
    Simulator * simulator_create(Topology * topo, Scheduler * sched);
    Topology * topology_create(void);
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    void topology_free(Topology *arg0);
    Scheduler * scheduler_create(size_t capacity);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    void scheduler_free(Scheduler *arg0);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    void simulator_free(Simulator *arg0);
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    void *malloc(size_t size);
    Packet *req_pkt = malloc(sizeof(Packet));
    if (req_pkt) memset(req_pkt, 0, sizeof(*req_pkt));
    uint8_t req_pkt_data[64];
    memset(req_pkt_data, 0, sizeof(req_pkt_data));
    if (req_pkt->data == NULL) req_pkt->data = req_pkt_data;
    if (req_pkt->len == 0) req_pkt->len = 8;
    memset(req_pkt->data, 0, req_pkt->len);
    req_pkt->len = ICMP_HDR_LEN;
    req_pkt->data = req_pkt->head;
    int out_ret = icmp_send_echo_reply(sim, iface, req_pkt);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    printf("PASS test_send_echo_reply_missing_stripped_ip_tv001\n");
}

static void test_send_time_exceeded_null_input_tv001(void) {
    int out_ret = icmp_send_time_exceeded(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_time_exceeded_null_input_tv001\n");
}

static void test_send_unreach_net_null_input_tv001(void) {
    int out_ret = icmp_send_unreach_net(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_unreach_net_null_input_tv001\n");
}

static void test_send_unreach_host_null_input_tv001(void) {
    int out_ret = icmp_send_unreach_host(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_unreach_host_null_input_tv001\n");
}

static void test_send_unreach_proto_null_input_tv001(void) {
    int out_ret = icmp_send_unreach_proto(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_unreach_proto_null_input_tv001\n");
}

static void test_send_unreach_port_null_input_tv001(void) {
    int out_ret = icmp_send_unreach_port(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_unreach_port_null_input_tv001\n");
}

static void test_send_frag_needed_null_input_tv001(void) {
    int out_ret = icmp_send_frag_needed(NULL, NULL, NULL, 0);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_frag_needed_null_input_tv001\n");
}

static void test_checksum_null_tv001(void) {
    uint16_t out_ret = icmp_checksum(NULL, 1);
    int out_sentinel = (out_ret == 65535) ? 1 : 0;
    assert(out_ret == 65535); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_checksum_null_tv001\n");
}

static void test_checksum_empty_tv001(void) {
    uint16_t out_ret = icmp_checksum(NULL, 0);
    int out_sentinel = (out_ret == 65535) ? 1 : 0;
    assert(out_ret == 65535); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_checksum_empty_tv001\n");
}

static void test_checksum_valid_tv001(void) {
    uint16_t out_ret = icmp_checksum(NULL, 1);
    assert(out_ret == 65535); /* EVA-proven oracle */
    printf("PASS test_checksum_valid_tv001\n");
}

static void test_checksum_ir_if_0_left_not_data_tv001(void) {
    int out_ok = 1;
    uint8_t data_buf[64];
    memset(data_buf, 0, sizeof(data_buf));
    const void * data = data_buf;
    data = 0;
    icmp_checksum(data, 1);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_checksum_ir_if_0_left_not_data_tv001\n");
}

static void test_checksum_ir_if_0_right_len_eq_0_tv001(void) {
    int out_ok = 1;
    size_t len = 1;
    len = 0;
    icmp_checksum(NULL, len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_checksum_ir_if_0_right_len_eq_0_tv001\n");
}

static void test_checksum_ir_forbidden_value_0_len_eq_0_forbidden_tv001(void) {
    int out_ok = 1;
    size_t len = 1;
    len = 0;
    icmp_checksum(NULL, len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_checksum_ir_forbidden_value_0_len_eq_0_forbidden_tv001\n");
}

static void test_checksum_ir_forbidden_value_0_len_eq_0_allowed_tv001(void) {
    int out_ok = 1;
    size_t len = 1;
    len = 1;
    icmp_checksum(NULL, len);
    out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_checksum_ir_forbidden_value_0_len_eq_0_allowed_tv001\n");
}

int main(void) {
    test_receive_null_iface_tv001();
    test_receive_null_pkt_tv001();
    test_receive_too_short_tv001();
    test_receive_missing_stripped_ip_tv001();
    test_send_echo_request_null_input_tv001();
    test_send_echo_request_valid_tv001();
    test_send_echo_request_ir_if_0_not_sim_tv001();
    test_send_echo_request_ir_if_1_payload_len_gt_0_and_not_payload_tv001();
    test_send_echo_request_ir_if_1_false_left_false_payload_len_le_0_tv001();
    test_send_echo_request_ir_if_3_payload_len_gt_0_tv001();
    test_send_echo_request_ir_if_3_false_payload_len_le_0_tv001();
    test_send_echo_request_ir_callee_packet_create_zero_failure_tv001();
    test_send_echo_request_ir_callee_packet_create_zero_success_tv001();
    test_send_echo_request_ir_max_guard_1_payload_len_gt_0_valid_low_tv001();
    test_send_echo_request_ir_max_guard_1_payload_len_gt_0_boundary_tv001();
    test_send_echo_request_ir_max_guard_1_payload_len_gt_0_too_high_tv001();
    test_send_echo_reply_null_input_tv001();
    test_send_echo_reply_too_short_tv001();
    test_send_echo_reply_missing_stripped_ip_tv001();
    test_send_time_exceeded_null_input_tv001();
    test_send_unreach_net_null_input_tv001();
    test_send_unreach_host_null_input_tv001();
    test_send_unreach_proto_null_input_tv001();
    test_send_unreach_port_null_input_tv001();
    test_send_frag_needed_null_input_tv001();
    test_checksum_null_tv001();
    test_checksum_empty_tv001();
    test_checksum_valid_tv001();
    test_checksum_ir_if_0_left_not_data_tv001();
    test_checksum_ir_if_0_right_len_eq_0_tv001();
    test_checksum_ir_forbidden_value_0_len_eq_0_forbidden_tv001();
    test_checksum_ir_forbidden_value_0_len_eq_0_allowed_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
