/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-02 15:35:16
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "mac_table.h"

static void test_table_init_tv001(void) {
    MacTable table;
    memset(&table, 0xA5, sizeof(table));
    mac_table_init(&table);
    int out_count = table.count;
    int out_first_valid = table.entries[0].valid;
    int out_last_valid = table.entries[MAC_TABLE_SIZE - 1].valid;
    assert(out_count == 0); /* EVA-proven oracle */
    assert(out_first_valid == 0); /* EVA-proven oracle */
    assert(out_last_valid == 0); /* EVA-proven oracle */
    printf("PASS test_table_init_tv001\n");
}

static void test_table_init_null_tv001(void) {
    mac_table_init(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_table_init_null_tv001\n");
}

static void test_table_learn_new_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    uint8_t mac[6] = {0xAA,0xBB,0xCC,0x11,0x22,0x33};
    MacEntry *entry = mac_table_learn(&table, mac, &port, 1000);
    int out_not_null = (entry != NULL) ? 1 : 0;
    int out_count = table.count;
    int out_valid = (entry != NULL && entry->valid == 1) ? 1 : 0;
    int out_port_match = (entry != NULL && entry->port == &port) ? 1 : 0;
    int out_mac_match = (entry != NULL && entry->mac[0] == 0xAA && entry->mac[5] == 0x33) ? 1 : 0;
    int out_timestamp = (entry != NULL && entry->timestamp == 1000) ? 1 : 0;
    assert(out_not_null == 1); /* EVA-proven oracle */
    assert(out_count == 1); /* EVA-proven oracle */
    assert(out_valid == 1); /* EVA-proven oracle */
    assert(out_port_match == 1); /* EVA-proven oracle */
    assert(out_mac_match == 1); /* EVA-proven oracle */
    assert(out_timestamp == 1); /* EVA-proven oracle */
    printf("PASS test_table_learn_new_tv001\n");
}

static void test_table_learn_update_port_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface old_port;
    Interface new_port;
    memset(&old_port, 0, sizeof(old_port));
    memset(&new_port, 0, sizeof(new_port));
    uint8_t mac[6] = {0x10,0x20,0x30,0x40,0x50,0x60};
    mac_table_learn(&table, mac, &old_port, 1000);
    MacEntry *entry = mac_table_learn(&table, mac, &new_port, 2000);
    int out_count = table.count;
    int out_port_match = (entry != NULL && entry->port == &new_port) ? 1 : 0;
    int out_timestamp = (entry != NULL && entry->timestamp == 2000) ? 1 : 0;
    assert(out_count == 1); /* EVA-proven oracle */
    assert(out_port_match == 1); /* EVA-proven oracle */
    assert(out_timestamp == 1); /* EVA-proven oracle */
    printf("PASS test_table_learn_update_port_tv001\n");
}

static void test_table_learn_table_full_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    for (int i = 0; i < MAC_TABLE_SIZE; i++) { table.entries[i].valid = 1; table.entries[i].mac[0] = (uint8_t)i; }
    table.count = MAC_TABLE_SIZE;
    uint8_t mac[6] = {0xAA,0xBB,0xCC,0xDD,0xEE,0xFF};
    MacEntry *entry = mac_table_learn(&table, mac, &port, 1234);
    int out_is_null = (entry == NULL) ? 1 : 0;
    int out_count = table.count;
    assert(out_is_null == 1); /* EVA-proven oracle */
    assert(out_count == 1024); /* EVA-proven oracle */
    printf("PASS test_table_learn_table_full_tv001\n");
}

static void test_table_learn_null_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    uint8_t mac[6] = {0};
    MacEntry *r1 = mac_table_learn(NULL, mac, &port, 0);
    MacEntry *r2 = mac_table_learn(&table, NULL, &port, 0);
    MacEntry *r3 = mac_table_learn(&table, mac, NULL, 0);
    int out_null_table = (r1 == NULL) ? 1 : 0;
    int out_null_mac = (r2 == NULL) ? 1 : 0;
    int out_null_port = (r3 == NULL) ? 1 : 0;
    int out_count = table.count;
    assert(out_null_table == 1); /* EVA-proven oracle */
    assert(out_null_mac == 1); /* EVA-proven oracle */
    assert(out_null_port == 1); /* EVA-proven oracle */
    assert(out_count == 0); /* EVA-proven oracle */
    printf("PASS test_table_learn_null_tv001\n");
}

static void test_table_lookup_hit_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    uint8_t mac[6] = {0x01,0x02,0x03,0x04,0x05,0x06};
    mac_table_learn(&table, mac, &port, 10);
    Interface *found = mac_table_lookup(&table, mac);
    int out_found = (found == &port) ? 1 : 0;
    assert(out_found == 1); /* EVA-proven oracle */
    printf("PASS test_table_lookup_hit_tv001\n");
}

static void test_table_lookup_miss_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    uint8_t known[6] = {0x01,0x02,0x03,0x04,0x05,0x06};
    uint8_t unknown[6] = {0x06,0x05,0x04,0x03,0x02,0x01};
    mac_table_learn(&table, known, &port, 10);
    Interface *found = mac_table_lookup(&table, unknown);
    int out_is_null = (found == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    printf("PASS test_table_lookup_miss_tv001\n");
}

static void test_table_lookup_null_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    uint8_t mac[6] = {0};
    Interface *r1 = mac_table_lookup(NULL, mac);
    Interface *r2 = mac_table_lookup(&table, NULL);
    int out_null_table = (r1 == NULL) ? 1 : 0;
    int out_null_mac = (r2 == NULL) ? 1 : 0;
    assert(out_null_table == 1); /* EVA-proven oracle */
    assert(out_null_mac == 1); /* EVA-proven oracle */
    printf("PASS test_table_lookup_null_tv001\n");
}

static void test_table_lookup_after_age_expires_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    uint8_t mac[6] = {0xDE,0xAD,0xBE,0xEF,0x00,0x01};
    mac_table_learn(&table, mac, &port, 0);
    mac_table_age(&table, MAC_AGE_MS + 1);
    Interface *found = mac_table_lookup(&table, mac);
    int out_is_null = (found == NULL) ? 1 : 0;
    int out_count = table.count;
    assert(out_is_null == 1); /* EVA-proven oracle */
    assert(out_count == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_after_age_expires_tv001\n");
}

static void test_table_age_keeps_fresh_entry_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    uint8_t mac[6] = {0xAA,0x00,0x00,0x00,0x00,0x01};
    mac_table_learn(&table, mac, &port, 1000);
    mac_table_age(&table, 1000 + MAC_AGE_MS);
    int out_valid = table.entries[0].valid;
    int out_count = table.count;
    assert(out_valid == 1); /* EVA-proven oracle */
    assert(out_count == 1); /* EVA-proven oracle */
    printf("PASS test_table_age_keeps_fresh_entry_tv001\n");
}

static void test_table_age_removes_stale_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    uint8_t mac[6] = {0xAA,0x00,0x00,0x00,0x00,0x02};
    mac_table_learn(&table, mac, &port, 1000);
    mac_table_age(&table, 1001 + MAC_AGE_MS);
    int out_valid = table.entries[0].valid;
    int out_count = table.count;
    assert(out_valid == 0); /* EVA-proven oracle */
    assert(out_count == 0); /* EVA-proven oracle */
    printf("PASS test_table_age_removes_stale_tv001\n");
}

static void test_table_age_null_tv001(void) {
    mac_table_age(NULL, 999999);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_table_age_null_tv001\n");
}

static void test_table_flush_port_removes_entries_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    uint8_t mac1[6] = {0x01,0x01,0x01,0x01,0x01,0x01};
    uint8_t mac2[6] = {0x02,0x02,0x02,0x02,0x02,0x02};
    mac_table_learn(&table, mac1, &port, 10);
    mac_table_learn(&table, mac2, &port, 20);
    mac_table_flush_port(&table, &port);
    int out_first_valid = table.entries[0].valid;
    int out_second_valid = table.entries[1].valid;
    int out_count = table.count;
    assert(out_first_valid == 0); /* EVA-proven oracle */
    assert(out_second_valid == 0); /* EVA-proven oracle */
    assert(out_count == 0); /* EVA-proven oracle */
    printf("PASS test_table_flush_port_removes_entries_tv001\n");
}

static void test_table_flush_port_leaves_others_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface flush_port;
    Interface keep_port;
    memset(&flush_port, 0, sizeof(flush_port));
    memset(&keep_port, 0, sizeof(keep_port));
    uint8_t mac1[6] = {0x01,0x01,0x01,0x01,0x01,0x01};
    uint8_t mac2[6] = {0x02,0x02,0x02,0x02,0x02,0x02};
    mac_table_learn(&table, mac1, &flush_port, 10);
    mac_table_learn(&table, mac2, &keep_port, 20);
    mac_table_flush_port(&table, &flush_port);
    int out_flushed_valid = table.entries[0].valid;
    int out_kept_valid = table.entries[1].valid;
    int out_count = table.count;
    assert(out_flushed_valid == 0); /* EVA-proven oracle */
    assert(out_kept_valid == 1); /* EVA-proven oracle */
    assert(out_count == 1); /* EVA-proven oracle */
    printf("PASS test_table_flush_port_leaves_others_tv001\n");
}

static void test_table_flush_port_null_tv001(void) {
    MacTable table;
    mac_table_init(&table);
    Interface port;
    memset(&port, 0, sizeof(port));
    uint8_t mac[6] = {0x01,0x01,0x01,0x01,0x01,0x01};
    mac_table_learn(&table, mac, &port, 10);
    mac_table_flush_port(NULL, &port);
    mac_table_flush_port(&table, NULL);
    int out_count = table.count;
    int out_valid = table.entries[0].valid;
    assert(out_count == 1); /* EVA-proven oracle */
    assert(out_valid == 1); /* EVA-proven oracle */
    printf("PASS test_table_flush_port_null_tv001\n");
}

int main(void) {
    test_table_init_tv001();
    test_table_init_null_tv001();
    test_table_learn_new_tv001();
    test_table_learn_update_port_tv001();
    test_table_learn_table_full_tv001();
    test_table_learn_null_tv001();
    test_table_lookup_hit_tv001();
    test_table_lookup_miss_tv001();
    test_table_lookup_null_tv001();
    test_table_lookup_after_age_expires_tv001();
    test_table_age_keeps_fresh_entry_tv001();
    test_table_age_removes_stale_tv001();
    test_table_age_null_tv001();
    test_table_flush_port_removes_entries_tv001();
    test_table_flush_port_leaves_others_tv001();
    test_table_flush_port_null_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
