/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-27 16:15:42
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "ethernet.h"

#include "ethernet.h"

static void test_receive_event_valid_tv001(void) {
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    ethernet_receive_event(e, NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    event_free(e);
    printf("PASS test_receive_event_valid_tv001\n");
}

static void test_send_null_tv001(void) {
    int out_ret = ethernet_send(NULL, NULL, NULL, 0, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_null_tv001\n");
}

static void test_send_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    uint8_t dst_mac[6] = {0, 0, 0, 0, 0, 0};
    Packet *payload = packet_create(64);
    assert(payload != NULL);
    if (payload->len == 0) payload->len = 8;
    memset(payload->data, 0, payload->len);
    int out_ret = ethernet_send(sim, iface, dst_mac, 0, payload);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(payload);
    printf("PASS test_send_valid_tv001\n");
}

static void test_receive_null_tv001(void) {
    int out_ret = ethernet_receive(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_receive_null_tv001\n");
}

static void test_receive_drop_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *frame = packet_create(64);
    assert(frame != NULL);
    if (frame->len == 0) frame->len = 8;
    memset(frame->data, 0, frame->len);
    /* kleva synth: no visible allocation strategy for uint16_t *out_ethertype; using NULL */
    int out_ret = ethernet_receive(iface, frame, NULL);
    int out_sentinel = (out_ret == 1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 0); /* EVA-proven oracle */
    interface_free(iface);
    packet_free(frame);
    printf("PASS test_receive_drop_tv001\n");
}

static void test_receive_valid_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *frame = packet_create(64);
    assert(frame != NULL);
    if (frame->len == 0) frame->len = 8;
    memset(frame->data, 0, frame->len);
    /* kleva synth: no visible allocation strategy for uint16_t *out_ethertype; using NULL */
    int out_ret = ethernet_receive(iface, frame, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    packet_free(frame);
    printf("PASS test_receive_valid_tv001\n");
}

int main(void) {
    test_receive_event_valid_tv001();
    test_send_null_tv001();
    test_send_valid_tv001();
    test_receive_null_tv001();
    test_receive_drop_tv001();
    test_receive_valid_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
