/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-16 18:40:11
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "arp.h"

#include "arp.h"

static void test_init_null_tv001(void) {
    arp_init(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_init_null_tv001\n");
}

static void test_init_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    arp_init(sim);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_init_valid_tv001\n");
}

static void test_cache_add_null_tv001(void) {
    uint8_t mac_addr[6] = {0, 0, 0, 0, 0, 0};
    arp_cache_add(NULL, 0, mac_addr, 0);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_cache_add_null_tv001\n");
}

static void test_cache_add_valid_tv001(void) {
    ArpCache cache;
    memset(&cache, 0, sizeof(cache));
    uint8_t mac_addr[6] = {0, 0, 0, 0, 0, 0};
    arp_cache_add(&cache, 1, mac_addr, 0);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_cache_add_valid_tv001\n");
}

static void test_send_request_null_tv001(void) {
    int out_ret = arp_send_request(NULL, NULL, 0);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_request_null_tv001\n");
}

static void test_send_request_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    int out_ret = arp_send_request(sim, iface, 1);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    printf("PASS test_send_request_valid_tv001\n");
}

static void test_send_reply_null_tv001(void) {
    int out_ret = arp_send_reply(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_reply_null_tv001\n");
}

static void test_send_reply_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *req_pkt = packet_create(64);
    assert(req_pkt != NULL);
    if (req_pkt->len == 0) req_pkt->len = 8;
    memset(req_pkt->data, 0, req_pkt->len);
    req_pkt->len = 28;
    if (req_pkt->len == 0) req_pkt->len = 1;
    memset(req_pkt->data, 0, req_pkt->len);
    int out_ret = arp_send_reply(sim, iface, req_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(req_pkt);
    printf("PASS test_send_reply_valid_tv001\n");
}

static void test_cache_lookup_null_tv001(void) {
    int out_ret = arp_cache_lookup(NULL, 0, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_cache_lookup_null_tv001\n");
}

static void test_cache_lookup_valid_tv001(void) {
    ArpCache cache;
    memset(&cache, 0, sizeof(cache));
    uint8_t out_mac[6] = {0, 0, 0, 0, 0, 0};
    int out_ret = arp_cache_lookup(&cache, 1, out_mac);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_cache_lookup_valid_tv001\n");
}

static void test_pending_enqueue_null_tv001(void) {
    int out_ret = arp_pending_enqueue(NULL, NULL, 0, 0, 0, 0, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_pending_enqueue_null_tv001\n");
}

static void test_pending_enqueue_valid_tv001(void) {
    ArpCache cache;
    memset(&cache, 0, sizeof(cache));
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *payload = packet_create(64);
    assert(payload != NULL);
    int out_ret = arp_pending_enqueue(&cache, iface, 1, 0, 0, 0, payload);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    packet_free(payload);
    printf("PASS test_pending_enqueue_valid_tv001\n");
}

static void test_pending_flush_null_tv001(void) {
    int out_ret = arp_pending_flush(NULL, NULL, 0, NULL);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_pending_flush_null_tv001\n");
}

static void test_pending_flush_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    ArpCache cache;
    memset(&cache, 0, sizeof(cache));
    uint8_t mac_addr[6] = {0, 0, 0, 0, 0, 0};
    int out_ret = arp_pending_flush(sim, &cache, 1, mac_addr);
    assert(out_ret == 0); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_pending_flush_valid_tv001\n");
}

static void test_cache_cleanup_null_tv001(void) {
    arp_cache_cleanup(NULL, 0);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_cache_cleanup_null_tv001\n");
}

static void test_cache_cleanup_valid_tv001(void) {
    ArpCache cache;
    memset(&cache, 0, sizeof(cache));
    arp_cache_cleanup(&cache, 0);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_cache_cleanup_valid_tv001\n");
}

int main(void) {
    test_init_null_tv001();
    test_init_valid_tv001();
    test_cache_add_null_tv001();
    test_cache_add_valid_tv001();
    test_send_request_null_tv001();
    test_send_request_valid_tv001();
    test_send_reply_null_tv001();
    test_send_reply_valid_tv001();
    test_cache_lookup_null_tv001();
    test_cache_lookup_valid_tv001();
    test_pending_enqueue_null_tv001();
    test_pending_enqueue_valid_tv001();
    test_pending_flush_null_tv001();
    test_pending_flush_valid_tv001();
    test_cache_cleanup_null_tv001();
    test_cache_cleanup_valid_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
