/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-29 18:52:07
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "interface.h"

#include "interface.h"
static void kleva_stub_RxHandler(struct Interface * arg0, struct Packet * arg1, uint16_t arg2, void * arg3) {
    (void)arg0;
    (void)arg1;
    (void)arg2;
    (void)arg3;
}

static void test_create_valid_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_valid_tv001\n");
}

static void test_create_ir_diversity_mac_all_zero_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    /* diversity: byte-buffer mac all-zero */
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_mac_all_zero_tv001\n");
}

static void test_create_ir_diversity_mac_all_0xff_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0xFF, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    /* diversity: byte-buffer mac all-0xff */
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_mac_all_0xff_tv001\n");
}

static void test_create_ir_diversity_mac_first_byte_set_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    if (sizeof(mac_buf) > 0) mac_buf[0] = 1;
    const uint8_t * mac = mac_buf;
    /* diversity: byte-buffer mac first-byte-set */
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_mac_first_byte_set_tv001\n");
}

static void test_create_ir_diversity_ip_addr_min_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_ip_addr_min_tv001\n");
}

static void test_create_ir_diversity_ip_addr_one_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 1, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 1); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_ip_addr_one_tv001\n");
}

static void test_create_ir_diversity_prefix_len_zero_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_prefix_len_zero_tv001\n");
}

static void test_create_ir_diversity_prefix_len_one_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 0, 1, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 1); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_prefix_len_one_tv001\n");
}

static void test_create_ir_diversity_prefix_len_two_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 0, 2, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 2); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_prefix_len_two_tv001\n");
}

static void test_create_ir_diversity_mtu_one_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_mtu_one_tv001\n");
}

static void test_create_ir_diversity_mtu_max_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 0, 0, 65535);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 65535); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_mtu_max_tv001\n");
}

static void test_set_up_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    interface_set_up(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_iface_up = ((uintptr_t)(iface->up) == (uintptr_t)(0));
    assert(out_ir_post_iface_up == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_up_valid_tv001\n");
}

static void test_is_up_null_tv001(void) {
    int out_ret = interface_is_up(NULL);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_is_up_null_tv001\n");
}

static void test_is_up_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    int out_ret = interface_is_up(iface);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_is_up_valid_tv001\n");
}

static void test_is_up_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    iface = 0;
    int out_ret = interface_is_up(iface);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_is_up_ir_if_0_false_truthy_iface_tv001\n");
}

static void test_set_link_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    interface_set_link(iface, NULL);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_iface_link = ((uintptr_t)(iface->link) == (uintptr_t)(NULL));
    assert(out_ir_post_iface_link == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_link_valid_tv001\n");
}

static void test_get_link_null_tv001(void) {
    struct Link * out_ret = interface_get_link(NULL);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_get_link_null_tv001\n");
}

static void test_get_link_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    struct Link * out_ret = interface_get_link(iface);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_get_link_valid_tv001\n");
}

static void test_get_link_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    iface = 0;
    struct Link * out_ret = interface_get_link(iface);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_get_link_ir_if_0_false_truthy_iface_tv001\n");
}

static void test_get_mac_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    const uint8_t * out_ret = interface_get_mac(iface);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_get_mac_valid_tv001\n");
}

static void test_get_ip_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uint32_t out_ret = interface_get_ip(iface);
    assert(out_ret == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_get_ip_valid_tv001\n");
}

static void test_add_tx_bytes_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    uintptr_t kleva_old_ir_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    interface_add_tx_bytes(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_tx_bytes_n = ((uintptr_t)(iface->tx_bytes) == (kleva_old_iface_tx_bytes + (uintptr_t)(0)));
    int out_ir_post_iface_tx_bytes = ((uintptr_t)(iface->tx_bytes) == (uintptr_t)((kleva_old_ir_iface_tx_bytes + 0)));
    assert(out_post_iface_tx_bytes_n == 1); /* EVA-proven oracle */
    assert(out_ir_post_iface_tx_bytes == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_tx_bytes_valid_tv001\n");
}

static void test_add_tx_bytes_ir_diversity_n_min_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    interface_add_tx_bytes(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_tx_bytes_n = ((uintptr_t)(iface->tx_bytes) == (kleva_old_iface_tx_bytes + (uintptr_t)(0)));
    assert(out_post_iface_tx_bytes_n == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_tx_bytes_ir_diversity_n_min_tv001\n");
}

static void test_add_tx_bytes_ir_diversity_n_one_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    interface_add_tx_bytes(iface, 1);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_tx_bytes_n = ((uintptr_t)(iface->tx_bytes) == (kleva_old_iface_tx_bytes + (uintptr_t)(1)));
    assert(out_post_iface_tx_bytes_n == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_tx_bytes_ir_diversity_n_one_tv001\n");
}

static void test_add_rx_bytes_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    uintptr_t kleva_old_ir_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    interface_add_rx_bytes(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_rx_bytes_n = ((uintptr_t)(iface->rx_bytes) == (kleva_old_iface_rx_bytes + (uintptr_t)(0)));
    int out_ir_post_iface_rx_bytes = ((uintptr_t)(iface->rx_bytes) == (uintptr_t)((kleva_old_ir_iface_rx_bytes + 0)));
    assert(out_post_iface_rx_bytes_n == 1); /* EVA-proven oracle */
    assert(out_ir_post_iface_rx_bytes == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_rx_bytes_valid_tv001\n");
}

static void test_add_rx_bytes_ir_diversity_n_min_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    interface_add_rx_bytes(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_rx_bytes_n = ((uintptr_t)(iface->rx_bytes) == (kleva_old_iface_rx_bytes + (uintptr_t)(0)));
    assert(out_post_iface_rx_bytes_n == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_rx_bytes_ir_diversity_n_min_tv001\n");
}

static void test_add_rx_bytes_ir_diversity_n_one_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    interface_add_rx_bytes(iface, 1);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_rx_bytes_n = ((uintptr_t)(iface->rx_bytes) == (kleva_old_iface_rx_bytes + (uintptr_t)(1)));
    assert(out_post_iface_rx_bytes_n == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_rx_bytes_ir_diversity_n_one_tv001\n");
}

static void test_set_rx_handler_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    interface_set_rx_handler(iface, kleva_stub_RxHandler, NULL);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_iface_rx_handler = ((uintptr_t)(iface->rx_handler) == (uintptr_t)(kleva_stub_RxHandler));
    int out_ir_post_iface_handler_ctx = ((uintptr_t)(iface->handler_ctx) == (uintptr_t)(NULL));
    assert(out_ir_post_iface_rx_handler == 1); /* EVA-proven oracle */
    assert(out_ir_post_iface_handler_ctx == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_rx_handler_valid_tv001\n");
}

static void test_set_arp_cache_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    interface_set_arp_cache(iface, NULL);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_iface_arp_cache = ((uintptr_t)(iface->arp_cache) == (uintptr_t)(NULL));
    assert(out_ir_post_iface_arp_cache == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_arp_cache_valid_tv001\n");
}

int main(void) {
    test_create_valid_tv001();
    test_create_ir_diversity_mac_all_zero_tv001();
    test_create_ir_diversity_mac_all_0xff_tv001();
    test_create_ir_diversity_mac_first_byte_set_tv001();
    test_create_ir_diversity_ip_addr_min_tv001();
    test_create_ir_diversity_ip_addr_one_tv001();
    test_create_ir_diversity_prefix_len_zero_tv001();
    test_create_ir_diversity_prefix_len_one_tv001();
    test_create_ir_diversity_prefix_len_two_tv001();
    test_create_ir_diversity_mtu_one_tv001();
    test_create_ir_diversity_mtu_max_tv001();
    test_set_up_valid_tv001();
    test_is_up_null_tv001();
    test_is_up_valid_tv001();
    test_is_up_ir_if_0_false_truthy_iface_tv001();
    test_set_link_valid_tv001();
    test_get_link_null_tv001();
    test_get_link_valid_tv001();
    test_get_link_ir_if_0_false_truthy_iface_tv001();
    test_get_mac_valid_tv001();
    test_get_ip_valid_tv001();
    test_add_tx_bytes_valid_tv001();
    test_add_tx_bytes_ir_diversity_n_min_tv001();
    test_add_tx_bytes_ir_diversity_n_one_tv001();
    test_add_rx_bytes_valid_tv001();
    test_add_rx_bytes_ir_diversity_n_min_tv001();
    test_add_rx_bytes_ir_diversity_n_one_tv001();
    test_set_rx_handler_valid_tv001();
    test_set_arp_cache_valid_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
