/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-05-26 17:35:01
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "simulator.h"

static void test_create_ok_tv001(void) {
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    uint64_t out_end_time   = sim->end_time;
    int      out_topo_ok    = (sim->topo  == topo)  ? 1 : 0;
    int      out_sched_ok   = (sim->sched == sched) ? 1 : 0;
    assert(out_end_time == 0); /* EVA-proven oracle */
    assert(out_topo_ok == 1); /* EVA-proven oracle */
    assert(out_sched_ok == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_create_ok_tv001\n");
}

static void test_create_null_sched_tv001(void) {
    Topology *topo = topology_create();
    assert(topo != NULL);
    Simulator *sim = simulator_create(topo, NULL);
    int out_is_null = (sim == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    topology_free(topo);
    printf("PASS test_create_null_sched_tv001\n");
}

static void test_create_null_tv001(void) {
    Simulator *sim = simulator_create(NULL, NULL);
    int out_is_null = (sim == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    printf("PASS test_create_null_tv001\n");
}

static void test_free_null_tv001(void) {
    simulator_free(NULL);
    printf("PASS test_free_null_tv001\n");
}

static void test_set_end_time_tv001(void) {
    uint64_t end_us = (uint64_t)254ULL;
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    simulator_set_end_time(sim, end_us);
    uint64_t out_end_time = sim->end_time;
    assert(out_end_time == 254); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_set_end_time_tv001\n");
}

static void test_set_end_time_null_tv001(void) {
    simulator_set_end_time(NULL, 5000);
    printf("PASS test_set_end_time_null_tv001\n");
}

static void test_now_valid_tv001(void) {
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    uint64_t out_now = simulator_now(sim);
    assert(out_now == 0); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_now_valid_tv001\n");
}

static void test_now_null_tv001(void) {
    uint64_t out_now = simulator_now(NULL);
    assert(out_now == 0); /* EVA-proven oracle */
    printf("PASS test_now_null_tv001\n");
}

static void test_stop_valid_tv001(void) {
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    sim->sched->running = 1;
    simulator_stop(sim);
    int out_running = sim->sched->running;
    assert(out_running == 0); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_stop_valid_tv001\n");
}

static void test_stop_null_tv001(void) {
    simulator_stop(NULL);
    printf("PASS test_stop_null_tv001\n");
}

static void test_register_handler_valid_tv001(void) {
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    void *ctx = (void *)0xBEEF;
    simulator_register_handler(sim, EVT_PACKET_SEND, (EventHandler)0xCAFE, ctx);
    int out_fn_set  = (sim->sched->handlers[EVT_PACKET_SEND].fn  == (EventHandler)0xCAFE) ? 1 : 0;
    int out_ctx_set = (sim->sched->handlers[EVT_PACKET_SEND].ctx == ctx) ? 1 : 0;
    assert(out_fn_set == 1); /* EVA-proven oracle */
    assert(out_ctx_set == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_register_handler_valid_tv001\n");
}

static void test_register_handler_null_tv001(void) {
    simulator_register_handler(NULL, EVT_PACKET_SEND, (EventHandler)0xCAFE, NULL);
    printf("PASS test_register_handler_null_tv001\n");
}

static void test_inject_packet_valid_tv001(void) {
    uint64_t delay = (uint64_t)0ULL;
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    Device *src = device_create("H1", 4);
    assert(src != NULL);
    Device *dst = device_create("H2", 4);
    assert(dst != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    int    out_ret   = simulator_inject_packet(sim, src, dst, pkt, delay);
    size_t out_count = sim->sched->eq->count;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_count == 1); /* EVA-proven oracle */
    device_free(src);
    device_free(dst);
    simulator_free(sim);
    printf("PASS test_inject_packet_valid_tv001\n");
}

static void test_inject_packet_null_tv001(void) {
    int out_ret = simulator_inject_packet(NULL, NULL, NULL, NULL, 0);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_inject_packet_null_tv001\n");
}

static void test_step_empty_tv001(void) {
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    int      out_step = simulator_step(sim);
    uint64_t out_now  = simulator_now(sim);
    assert(out_step == 0); /* EVA-proven oracle */
    assert(out_now == 0); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_step_empty_tv001\n");
}

static void test_step_null_tv001(void) {
    int out_ret = simulator_step(NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_step_null_tv001\n");
}

static void test_run_empty_tv001(void) {
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    int out_ret     = simulator_run(sim);
    int out_running = sim->sched->running;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_running == 0); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_run_empty_tv001\n");
}

static void test_run_no_end_time_tv001(void) {
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    Event *e = event_create(EVT_PACKET_SEND, 100, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    scheduler_schedule(sim->sched, e);
    int      out_ret     = simulator_run(sim);
    uint64_t out_now     = simulator_now(sim);
    size_t   out_count   = sim->sched->eq->count;
    int      out_running = sim->sched->running;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_now == 100); /* EVA-proven oracle */
    assert(out_count == 0); /* EVA-proven oracle */
    assert(out_running == 0); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_run_no_end_time_tv001\n");
}

static void test_run_hits_end_time_tv001(void) {
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    simulator_set_end_time(sim, 100);
    Event *e = event_create(EVT_PACKET_SEND, 200, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    scheduler_schedule(sim->sched, e);
    int      out_ret     = simulator_run(sim);
    uint64_t out_now     = simulator_now(sim);
    int      out_running = sim->sched->running;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_now == 200); /* EVA-proven oracle */
    assert(out_running == 0); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_run_hits_end_time_tv001\n");
}

static void test_run_end_time_tv001(void) {
    Topology  *topo  = topology_create();
    assert(topo != NULL);
    Scheduler *sched = scheduler_create(8);
    assert(sched != NULL);
    Simulator *sim   = simulator_create(topo, sched);
    assert(sim != NULL);
    simulator_set_end_time(sim, 100);
    Event *e = event_create(EVT_PACKET_SEND, 50, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    scheduler_schedule(sim->sched, e);
    int      out_ret     = simulator_run(sim);
    uint64_t out_now     = simulator_now(sim);
    int      out_running = sim->sched->running;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_now == 50); /* EVA-proven oracle */
    assert(out_running == 0); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_run_end_time_tv001\n");
}

int main(void) {
    test_create_ok_tv001();
    test_create_null_sched_tv001();
    test_create_null_tv001();
    test_free_null_tv001();
    test_set_end_time_tv001();
    test_set_end_time_null_tv001();
    test_now_valid_tv001();
    test_now_null_tv001();
    test_stop_valid_tv001();
    test_stop_null_tv001();
    test_register_handler_valid_tv001();
    test_register_handler_null_tv001();
    test_inject_packet_valid_tv001();
    test_inject_packet_null_tv001();
    test_step_empty_tv001();
    test_step_null_tv001();
    test_run_empty_tv001();
    test_run_no_end_time_tv001();
    test_run_hits_end_time_tv001();
    test_run_end_time_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
