/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-16 18:10:10
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "scheduler.h"

#include "scheduler.h"

static void test_create_bad_tv001(void) {
    Scheduler * out_ret = scheduler_create(0);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    if (out_ret) scheduler_free(out_ret);
    printf("PASS test_create_bad_tv001\n");
}

static void test_create_ok_tv001(void) {
    Scheduler * out_ret = scheduler_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    if (out_ret) scheduler_free(out_ret);
    printf("PASS test_create_ok_tv001\n");
}

static void test_free_valid_tv001(void) {
    scheduler_free(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_free_valid_tv001\n");
}

static void test_register_null_tv001(void) {
    scheduler_register(NULL, 0, 0, NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_register_null_tv001\n");
}

static void test_register_valid_tv001(void) {
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    scheduler_register(s, 0, 0, NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_register_valid_tv001\n");
}

static void test_schedule_null_tv001(void) {
    int out_ret = scheduler_schedule(NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_schedule_null_tv001\n");
}

static void test_schedule_valid_tv001(void) {
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    Event *e = event_create(0, 1, NULL, NULL, NULL, NULL);
    assert(e != NULL);
    int out_ret = scheduler_schedule(s, e);
    assert(out_ret == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_schedule_valid_tv001\n");
}

static void test_step_valid_tv001(void) {
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    int out_ret = scheduler_step(s);
    assert(out_ret == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_step_valid_tv001\n");
}

static void test_run_valid_tv001(void) {
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    int out_ret = scheduler_run(s);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_run_valid_tv001\n");
}

static void test_stop_null_tv001(void) {
    scheduler_stop(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_stop_null_tv001\n");
}

static void test_stop_valid_tv001(void) {
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    scheduler_stop(s);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_stop_valid_tv001\n");
}

static void test_now_null_tv001(void) {
    uint64_t out_ret = scheduler_now(NULL);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_now_null_tv001\n");
}

static void test_now_valid_tv001(void) {
    Scheduler *s = scheduler_create(64);
    assert(s != NULL);
    uint64_t out_ret = scheduler_now(s);
    assert(out_ret == 0); /* EVA-proven oracle */
    scheduler_free(s);
    printf("PASS test_now_valid_tv001\n");
}

int main(void) {
    test_create_bad_tv001();
    test_create_ok_tv001();
    test_free_valid_tv001();
    test_register_null_tv001();
    test_register_valid_tv001();
    test_schedule_null_tv001();
    test_schedule_valid_tv001();
    test_step_valid_tv001();
    test_run_valid_tv001();
    test_stop_null_tv001();
    test_stop_valid_tv001();
    test_now_null_tv001();
    test_now_valid_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
