/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-16 15:12:23
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "udp.h"

static void kleva_stub_Udp_Recv_Handler(uint32_t src_ip, uint16_t src_port, Packet *payload, void *ctx) {
    (void)src_ip;
    (void)src_port;
    (void)payload;
    (void)ctx;
}

static void test_init_null_tv001(void) {
    udp_init(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_init_null_tv001\n");
}

static void test_init_valid_tv001(void) {
    UdpState state;
    memset(&state, 0, sizeof(state));
    udp_init(&state);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_init_valid_tv001\n");
}

static void test_bind_null_input_tv001(void) {
    int out_ret = udp_bind(NULL, 0, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_bind_null_input_tv001\n");
}

static void test_bind_duplicate_tv001(void) {
    UdpState state;
    memset(&state, 0, sizeof(state));
    state.sockets[0].valid = 1;
    state.sockets[0].port = 1;
    int out_ret = udp_bind(&state, 1, kleva_stub_Udp_Recv_Handler, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_bind_duplicate_tv001\n");
}

static void test_bind_full_tv001(void) {
    UdpState state;
    memset(&state, 0, sizeof(state));
    for (int kleva_i = 0; kleva_i < 32; kleva_i++) state.sockets[kleva_i].valid = 1;
    int out_ret = udp_bind(&state, 1, kleva_stub_Udp_Recv_Handler, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_bind_full_tv001\n");
}

static void test_bind_bound_tv001(void) {
    UdpState state;
    memset(&state, 0, sizeof(state));
    for (int kleva_i = 0; kleva_i < 32; kleva_i++) state.sockets[kleva_i].valid = 0;
    state.sockets[0].valid = 0;
    int out_ret = udp_bind(&state, 1, kleva_stub_Udp_Recv_Handler, NULL);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_bind_bound_tv001\n");
}

static void test_unbind_null_input_tv001(void) {
    int out_ret = udp_unbind(NULL, 0);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_unbind_null_input_tv001\n");
}

static void test_unbind_not_found_tv001(void) {
    UdpState state;
    memset(&state, 0, sizeof(state));
    for (int kleva_i = 0; kleva_i < 32; kleva_i++) state.sockets[kleva_i].valid = 0;
    int out_ret = udp_unbind(&state, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_unbind_not_found_tv001\n");
}

static void test_unbind_remove_tv001(void) {
    UdpState state;
    memset(&state, 0, sizeof(state));
    state.sockets[0].valid = 1;
    state.sockets[0].port = 1;
    int out_ret = udp_unbind(&state, 1);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_unbind_remove_tv001\n");
}

static void test_send_null_input_tv001(void) {
    int out_ret = udp_send(NULL, 0, 0, 0, 0, NULL, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_null_input_tv001\n");
}

static void test_send_too_large_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    int out_ret = udp_send(sim, 0, 0, 0, 1, NULL, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_too_large_tv001\n");
}

static void test_send_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    int out_ret = udp_send(sim, 0, 0, 0, 1, payload_buf, 1);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_valid_tv001\n");
}

static void test_receive_null_iface_tv001(void) {
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    int out_ret = udp_receive(NULL, pkt, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_receive_null_iface_tv001\n");
}

static void test_receive_null_pkt_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    int out_ret = udp_receive(iface, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_null_pkt_tv001\n");
}

static void test_receive_null_ctx_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    int out_ret = udp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_null_ctx_tv001\n");
}

static void test_receive_too_short_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = ((8) > 0 ? (8) - 1 : 0);
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_too_short_tv001\n");
}

static void test_receive_readable_udp_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_readable_udp_tv001\n");
}

static void test_receive_source_udp_ctx_state_NULL_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((UdpContext *)&ctx_UdpContext)->state = NULL;
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_udp_ctx_state_NULL_tv001\n");
}

static void test_receive_source_ip_hdr_protocol_eq_IPPROTO_UDP_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_UDP;
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_ip_hdr_protocol_eq_IPPROTO_UDP_tv001\n");
}

static void test_receive_source_ip_hdr_protocol_ne_IPPROTO_UDP_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = 0;
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_ip_hdr_protocol_ne_IPPROTO_UDP_tv001\n");
}

static void test_receive_source_udp_len_tmp_UDP_HDR_LEN_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((UdpHeader *)pkt->data)->length = ns_htons(((UDP_HDR_LEN) > 0 ? (UDP_HDR_LEN) - 1 : 0));
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_udp_len_tmp_UDP_HDR_LEN_tv001\n");
}

static void test_receive_source_udp_len_not_tmp_UDP_HDR_LEN_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((UdpHeader *)pkt->data)->length = ns_htons(UDP_HDR_LEN);
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_udp_len_not_tmp_UDP_HDR_LEN_tv001\n");
}

static void test_receive_source_udp_len_tmp_pkt_len_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((UdpHeader *)pkt->data)->length = ns_htons(((pkt->len) + 1));
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_udp_len_tmp_pkt_len_tv001\n");
}

static void test_receive_source_udp_len_not_tmp_pkt_len_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((UdpHeader *)pkt->data)->length = ns_htons(pkt->len);
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_udp_len_not_tmp_pkt_len_tv001\n");
}

static void test_receive_source_udp_ctx_sockets_match_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_UDP;
    ((UdpHeader *)pkt->data)->length = ns_htons(UDP_HDR_LEN);
    ((UdpHeader *)pkt->data)->length = ns_htons(pkt->len);
    UdpState kleva_udp_ctx_state;
    memset(&kleva_udp_ctx_state, 0, sizeof(kleva_udp_ctx_state));
    ((UdpContext *)&ctx_UdpContext)->state = &kleva_udp_ctx_state;
    ((UdpHeader *)pkt->data)->dst_port = ns_htons(1);
    ((UdpContext *)&ctx_UdpContext)->state->sockets[0].valid = 1;
    ((UdpContext *)&ctx_UdpContext)->state->sockets[0].port = 1;
    ((UdpContext *)&ctx_UdpContext)->state->sockets[0].recv_handler = kleva_stub_Udp_Recv_Handler;
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_udp_ctx_sockets_match_tv001\n");
}

static void test_receive_source_udp_ctx_sockets_miss_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    UdpContext ctx_UdpContext;
    memset(&ctx_UdpContext, 0, sizeof(ctx_UdpContext));
    pkt->len = 8;
    uint8_t pkt_20_header[20];
    memset(pkt_20_header, 0, sizeof(pkt_20_header));
    int pkt_20_prep_ret = packet_prepend(pkt, pkt_20_header, 20);
    assert(pkt_20_prep_ret == 0);
    int pkt_20_strip_ret = packet_strip(pkt, 20);
    assert(pkt_20_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IpHeader *)(pkt->data - IP_HDR_LEN))->protocol = IPPROTO_UDP;
    ((UdpHeader *)pkt->data)->length = ns_htons(UDP_HDR_LEN);
    ((UdpHeader *)pkt->data)->length = ns_htons(pkt->len);
    UdpState kleva_udp_ctx_state;
    memset(&kleva_udp_ctx_state, 0, sizeof(kleva_udp_ctx_state));
    ((UdpContext *)&ctx_UdpContext)->state = &kleva_udp_ctx_state;
    ((UdpContext *)&ctx_UdpContext)->state->sockets[0].valid = 0;
    int out_ret = udp_receive(iface, pkt, &ctx_UdpContext);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_udp_ctx_sockets_miss_tv001\n");
}

int main(void) {
    test_init_null_tv001();
    test_init_valid_tv001();
    test_bind_null_input_tv001();
    test_bind_duplicate_tv001();
    test_bind_full_tv001();
    test_bind_bound_tv001();
    test_unbind_null_input_tv001();
    test_unbind_not_found_tv001();
    test_unbind_remove_tv001();
    test_send_null_input_tv001();
    test_send_too_large_tv001();
    test_send_valid_tv001();
    test_receive_null_iface_tv001();
    test_receive_null_pkt_tv001();
    test_receive_null_ctx_tv001();
    test_receive_too_short_tv001();
    test_receive_readable_udp_tv001();
    test_receive_source_udp_ctx_state_NULL_tv001();
    test_receive_source_ip_hdr_protocol_eq_IPPROTO_UDP_tv001();
    test_receive_source_ip_hdr_protocol_ne_IPPROTO_UDP_tv001();
    test_receive_source_udp_len_tmp_UDP_HDR_LEN_tv001();
    test_receive_source_udp_len_not_tmp_UDP_HDR_LEN_tv001();
    test_receive_source_udp_len_tmp_pkt_len_tv001();
    test_receive_source_udp_len_not_tmp_pkt_len_tv001();
    test_receive_source_udp_ctx_sockets_match_tv001();
    test_receive_source_udp_ctx_sockets_miss_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
