/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-07-02 16:41:00
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "interface.h"

/* KLEVA native compile note:
 * This generated test includes allocator-failure candidates.
 * Compile the module-under-test with:
 *   -Dmalloc=__kleva_malloc -Dcalloc=__kleva_calloc -Drealloc=__kleva_realloc -Dfree=__kleva_free
 */

#include "interface.h"
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#ifdef malloc
#undef malloc
#endif
#ifdef calloc
#undef calloc
#endif
#ifdef realloc
#undef realloc
#endif
#ifdef free
#undef free
#endif
static unsigned char __kleva_alloc_arena[1024u * 1024u];
struct __kleva_alloc_rec {
    void *ptr;
    size_t size;
    int active;
};
static struct __kleva_alloc_rec __kleva_alloc_recs[1024];
static size_t __kleva_alloc_offset;
static long __kleva_alloc_call;
static long __kleva_alloc_fail_at = -1;
static void __kleva_alloc_reset(void) {
    __kleva_alloc_offset = 0;
    __kleva_alloc_call = 0;
    __kleva_alloc_fail_at = -1;
    memset(__kleva_alloc_recs, 0, sizeof(__kleva_alloc_recs));
}
static void __kleva_alloc_record(void *ptr, size_t size) {
    if (!ptr) {
        return;
    }
    for (size_t i = 0; i < sizeof(__kleva_alloc_recs) / sizeof(__kleva_alloc_recs[0]); i++) {
        if (!__kleva_alloc_recs[i].active) {
            __kleva_alloc_recs[i].ptr = ptr;
            __kleva_alloc_recs[i].size = size;
            __kleva_alloc_recs[i].active = 1;
            return;
        }
    }
}
static size_t __kleva_alloc_size_of(void *ptr) {
    for (size_t i = 0; i < sizeof(__kleva_alloc_recs) / sizeof(__kleva_alloc_recs[0]); i++) {
        if (__kleva_alloc_recs[i].active && __kleva_alloc_recs[i].ptr == ptr) {
            return __kleva_alloc_recs[i].size;
        }
    }
    return 0;
}
static void __kleva_alloc_forget(void *ptr) {
    for (size_t i = 0; i < sizeof(__kleva_alloc_recs) / sizeof(__kleva_alloc_recs[0]); i++) {
        if (__kleva_alloc_recs[i].active && __kleva_alloc_recs[i].ptr == ptr) {
            __kleva_alloc_recs[i].active = 0;
            return;
        }
    }
}
static void __kleva_alloc_fail_on(long index) {
    __kleva_alloc_fail_at = __kleva_alloc_call + index;
}
void *__kleva_malloc(size_t size) {
    if (__kleva_alloc_fail_at >= 0 && __kleva_alloc_call == __kleva_alloc_fail_at) {
        __kleva_alloc_call++;
        __kleva_alloc_fail_at = -1;
        return (void *)0;
    }
    __kleva_alloc_call++;
    if (size == 0) {
        size = 1;
    }
    size = (size + 7u) & ~((size_t)7u);
    if (size > sizeof(__kleva_alloc_arena) - __kleva_alloc_offset) {
        return (void *)0;
    }
    void *ptr = __kleva_alloc_arena + __kleva_alloc_offset;
    __kleva_alloc_offset += size;
    __kleva_alloc_record(ptr, size);
    return ptr;
}
void __kleva_free(void *ptr) {
    __kleva_alloc_forget(ptr);
}
void *__kleva_calloc(size_t count, size_t size) {
    size_t total = count * size;
    void *ptr = __kleva_malloc(total);
    if (ptr) {
        memset(ptr, 0, total);
    }
    return ptr;
}
void *__kleva_realloc(void *ptr, size_t size) {
    if (!ptr) {
        return __kleva_malloc(size);
    }
    if (size == 0) {
        __kleva_free(ptr);
        return (void *)0;
    }
    size_t old_size = __kleva_alloc_size_of(ptr);
    void *new_ptr = __kleva_malloc(size);
    if (!new_ptr) {
        return (void *)0;
    }
    if (old_size > 0) {
        size_t copy_size = old_size < size ? old_size : size;
        memcpy(new_ptr, ptr, copy_size);
    }
    __kleva_alloc_forget(ptr);
    return new_ptr;
}
static void kleva_stub_RxHandler(struct Interface * arg0, struct Packet * arg1, uint16_t arg2, void * arg3) {
    (void)arg0;
    (void)arg1;
    (void)arg2;
    (void)arg3;
}

static void test_create_valid_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_valid_tv001\n");
}

static void test_create_ir_alloc_malloc_0_zero_failure_tv001(void) {
    __kleva_alloc_reset();
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    __kleva_alloc_fail_on(0);
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 0); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_0_zero_failure_tv001\n");
}

static void test_create_ir_alloc_malloc_0_zero_success_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_0_zero_success_tv001\n");
}

static void test_create_ir_diversity_mac_all_zero_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    /* diversity: byte-buffer mac all-zero */
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_mac_all_zero_tv001\n");
}

static void test_create_ir_diversity_mac_all_0xff_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0xFF, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    /* diversity: byte-buffer mac all-0xff */
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_mac_all_0xff_tv001\n");
}

static void test_create_ir_diversity_mac_first_byte_set_tv001(void) {
    char name_buf[] = "kleva";
    const char * name = name_buf;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    if (sizeof(mac_buf) > 0) mac_buf[0] = 1;
    const uint8_t * mac = mac_buf;
    /* diversity: byte-buffer mac first-byte-set */
    Interface * out_ret = interface_create(name, mac, 0, 0, 1);
    int out_ret_nonnull = (out_ret != NULL);
    uint32_t out_ip_addr = out_ret ? out_ret->ip_addr : 0;
    uint8_t out_prefix_len = out_ret ? out_ret->prefix_len : 0;
    uint16_t out_mtu = out_ret ? out_ret->mtu : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_ip_addr == 0); /* EVA-proven oracle */
    assert(out_prefix_len == 0); /* EVA-proven oracle */
    assert(out_mtu == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_mac_first_byte_set_tv001\n");
}

static void test_free_valid_tv001(void) {
    interface_free(NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_free_valid_tv001\n");
}

static void test_set_up_null_tv001(void) {
    interface_set_up(NULL, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_set_up_null_tv001\n");
}

static void test_set_up_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    interface_set_up(iface, 0);
    uint32_t out_iface_ip_addr = iface->ip_addr;
    uint8_t out_iface_prefix_len = iface->prefix_len;
    uint16_t out_iface_mtu = iface->mtu;
    int out_iface_up = iface->up;
    int out_iface_link_nonnull = (iface->link != NULL);
    int out_iface_device_nonnull = (iface->device != NULL);
    uint64_t out_iface_tx_bytes = iface->tx_bytes;
    uint64_t out_iface_rx_bytes = iface->rx_bytes;
    int out_iface_rx_handler_nonnull = (iface->rx_handler != NULL);
    int out_iface_handler_ctx_nonnull = (iface->handler_ctx != NULL);
    int out_iface_arp_cache_nonnull = (iface->arp_cache != NULL);
    uint64_t out_iface_rx_dropped = iface->rx_dropped;
    uint64_t out_iface_rx_errors = iface->rx_errors;
    uint64_t out_iface_tx_errors = iface->tx_errors;
    int out_iface_state = iface->state;
    uint64_t out_iface_last_rx_time = iface->last_rx_time;
    uint64_t out_iface_last_tx_time = iface->last_tx_time;
    uint64_t out_iface_last_error_time = iface->last_error_time;
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_iface_up = ((uintptr_t)(iface->up) == (uintptr_t)(0));
    assert(out_iface_ip_addr == 1); /* EVA-proven oracle */
    assert(out_iface_prefix_len == 24); /* EVA-proven oracle */
    assert(out_iface_mtu == 1); /* EVA-proven oracle */
    assert(out_iface_up == 0); /* EVA-proven oracle */
    assert(out_iface_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_iface_rx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_tx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_state == 0); /* EVA-proven oracle */
    assert(out_iface_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_error_time == 0); /* EVA-proven oracle */
    assert(out_ir_post_iface_up == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_up_valid_tv001\n");
}

static void test_set_up_ir_if_0_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    assert(iface != NULL);
    interface_set_up(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_state_iface_up_up = ((uintptr_t)(iface->up) == (uintptr_t)(0));
    assert(out_post_state_iface_up_up == 1); /* EVA-proven oracle */
    printf("PASS test_set_up_ir_if_0_truthy_iface_tv001\n");
}

static void test_set_up_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    iface = 0;
    interface_set_up(iface, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_set_up_ir_if_0_false_truthy_iface_tv001\n");
}

static void test_set_up_ir_diversity_up_min_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    interface_set_up(iface, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_up_ir_diversity_up_min_tv001\n");
}

static void test_set_up_ir_diversity_up_one_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    interface_set_up(iface, 1);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_up_ir_diversity_up_one_tv001\n");
}

static void test_is_up_null_tv001(void) {
    int out_ret = interface_is_up(NULL);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_is_up_null_tv001\n");
}

static void test_is_up_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    int out_ret = interface_is_up(iface);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_is_up_valid_tv001\n");
}

static void test_is_up_ir_if_0_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    assert(iface != NULL);
    int out_ret = interface_is_up(iface);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_is_up_ir_if_0_truthy_iface_tv001\n");
}

static void test_is_up_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    iface = 0;
    int out_ret = interface_is_up(iface);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_is_up_ir_if_0_false_truthy_iface_tv001\n");
}

static void test_set_link_null_tv001(void) {
    /* fixture-failed: unknown allocator for Link *link; using NULL */
    interface_set_link(NULL, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_set_link_null_tv001\n");
}

static void test_set_link_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    interface_set_link(iface, NULL);
    uint32_t out_iface_ip_addr = iface->ip_addr;
    uint8_t out_iface_prefix_len = iface->prefix_len;
    uint16_t out_iface_mtu = iface->mtu;
    int out_iface_up = iface->up;
    int out_iface_link_nonnull = (iface->link != NULL);
    int out_iface_device_nonnull = (iface->device != NULL);
    uint64_t out_iface_tx_bytes = iface->tx_bytes;
    uint64_t out_iface_rx_bytes = iface->rx_bytes;
    int out_iface_rx_handler_nonnull = (iface->rx_handler != NULL);
    int out_iface_handler_ctx_nonnull = (iface->handler_ctx != NULL);
    int out_iface_arp_cache_nonnull = (iface->arp_cache != NULL);
    uint64_t out_iface_rx_dropped = iface->rx_dropped;
    uint64_t out_iface_rx_errors = iface->rx_errors;
    uint64_t out_iface_tx_errors = iface->tx_errors;
    int out_iface_state = iface->state;
    uint64_t out_iface_last_rx_time = iface->last_rx_time;
    uint64_t out_iface_last_tx_time = iface->last_tx_time;
    uint64_t out_iface_last_error_time = iface->last_error_time;
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_iface_link = ((uintptr_t)(iface->link) == (uintptr_t)(NULL));
    assert(out_iface_ip_addr == 1); /* EVA-proven oracle */
    assert(out_iface_prefix_len == 24); /* EVA-proven oracle */
    assert(out_iface_mtu == 1); /* EVA-proven oracle */
    assert(out_iface_up == 0); /* EVA-proven oracle */
    assert(out_iface_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_iface_rx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_tx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_state == 0); /* EVA-proven oracle */
    assert(out_iface_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_error_time == 0); /* EVA-proven oracle */
    assert(out_ir_post_iface_link == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_link_valid_tv001\n");
}

static void test_set_link_ir_if_0_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    assert(iface != NULL);
    interface_set_link(iface, NULL);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_state_iface_link_link = ((uintptr_t)(iface->link) == (uintptr_t)(NULL));
    assert(out_post_state_iface_link_link == 1); /* EVA-proven oracle */
    printf("PASS test_set_link_ir_if_0_truthy_iface_tv001\n");
}

static void test_set_link_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    iface = 0;
    interface_set_link(iface, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_set_link_ir_if_0_false_truthy_iface_tv001\n");
}

static void test_get_link_null_tv001(void) {
    struct Link * out_ret = interface_get_link(NULL);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_get_link_null_tv001\n");
}

static void test_get_link_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    struct Link * out_ret = interface_get_link(iface);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_get_link_valid_tv001\n");
}

static void test_get_link_ir_if_0_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    assert(iface != NULL);
    struct Link * out_ret = interface_get_link(iface);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_get_link_ir_if_0_truthy_iface_tv001\n");
}

static void test_get_link_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    iface = 0;
    struct Link * out_ret = interface_get_link(iface);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_get_link_ir_if_0_false_truthy_iface_tv001\n");
}

static void test_get_mac_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    const uint8_t * out_ret = interface_get_mac(iface);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_get_mac_valid_tv001\n");
}

static void test_get_ip_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uint32_t out_ret = interface_get_ip(iface);
    assert(out_ret == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_get_ip_valid_tv001\n");
}

static void test_add_tx_bytes_null_tv001(void) {
    interface_add_tx_bytes(NULL, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_add_tx_bytes_null_tv001\n");
}

static void test_add_tx_bytes_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    uintptr_t kleva_old_ir_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    interface_add_tx_bytes(iface, 0);
    uint32_t out_iface_ip_addr = iface->ip_addr;
    uint8_t out_iface_prefix_len = iface->prefix_len;
    uint16_t out_iface_mtu = iface->mtu;
    int out_iface_up = iface->up;
    int out_iface_link_nonnull = (iface->link != NULL);
    int out_iface_device_nonnull = (iface->device != NULL);
    uint64_t out_iface_tx_bytes = iface->tx_bytes;
    uint64_t out_iface_rx_bytes = iface->rx_bytes;
    int out_iface_rx_handler_nonnull = (iface->rx_handler != NULL);
    int out_iface_handler_ctx_nonnull = (iface->handler_ctx != NULL);
    int out_iface_arp_cache_nonnull = (iface->arp_cache != NULL);
    uint64_t out_iface_rx_dropped = iface->rx_dropped;
    uint64_t out_iface_rx_errors = iface->rx_errors;
    uint64_t out_iface_tx_errors = iface->tx_errors;
    int out_iface_state = iface->state;
    uint64_t out_iface_last_rx_time = iface->last_rx_time;
    uint64_t out_iface_last_tx_time = iface->last_tx_time;
    uint64_t out_iface_last_error_time = iface->last_error_time;
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_tx_bytes_n = ((uintptr_t)(iface->tx_bytes) == (kleva_old_iface_tx_bytes + (uintptr_t)(0)));
    int out_ir_post_iface_tx_bytes = ((uintptr_t)(iface->tx_bytes) == (uintptr_t)((kleva_old_ir_iface_tx_bytes + 0)));
    assert(out_iface_ip_addr == 1); /* EVA-proven oracle */
    assert(out_iface_prefix_len == 24); /* EVA-proven oracle */
    assert(out_iface_mtu == 1); /* EVA-proven oracle */
    assert(out_iface_up == 0); /* EVA-proven oracle */
    assert(out_iface_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_iface_rx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_tx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_state == 0); /* EVA-proven oracle */
    assert(out_iface_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_error_time == 0); /* EVA-proven oracle */
    assert(out_post_iface_tx_bytes_n == 1); /* EVA-proven oracle */
    assert(out_ir_post_iface_tx_bytes == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_tx_bytes_valid_tv001\n");
}

static void test_add_tx_bytes_ir_if_0_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    assert(iface != NULL);
    uintptr_t kleva_old_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    uintptr_t kleva_old_post_state_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    interface_add_tx_bytes(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_tx_bytes_n = ((uintptr_t)(iface->tx_bytes) == (kleva_old_iface_tx_bytes + (uintptr_t)(0)));
    int out_post_state_iface_tx_bytes_iface_tx_bytes_n = ((uintptr_t)(iface->tx_bytes) == (uintptr_t)((kleva_old_post_state_iface_tx_bytes + 0)));
    assert(out_post_iface_tx_bytes_n == 1); /* EVA-proven oracle */
    assert(out_post_state_iface_tx_bytes_iface_tx_bytes_n == 1); /* EVA-proven oracle */
    printf("PASS test_add_tx_bytes_ir_if_0_truthy_iface_tv001\n");
}

static void test_add_tx_bytes_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    iface = 0;
    interface_add_tx_bytes(iface, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_add_tx_bytes_ir_if_0_false_truthy_iface_tv001\n");
}

static void test_add_tx_bytes_ir_diversity_n_min_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    interface_add_tx_bytes(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_tx_bytes_n = ((uintptr_t)(iface->tx_bytes) == (kleva_old_iface_tx_bytes + (uintptr_t)(0)));
    assert(out_post_iface_tx_bytes_n == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_tx_bytes_ir_diversity_n_min_tv001\n");
}

static void test_add_tx_bytes_ir_diversity_n_one_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_tx_bytes = (uintptr_t)(iface->tx_bytes);
    interface_add_tx_bytes(iface, 1);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_tx_bytes_n = ((uintptr_t)(iface->tx_bytes) == (kleva_old_iface_tx_bytes + (uintptr_t)(1)));
    assert(out_post_iface_tx_bytes_n == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_tx_bytes_ir_diversity_n_one_tv001\n");
}

static void test_add_rx_bytes_null_tv001(void) {
    interface_add_rx_bytes(NULL, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_add_rx_bytes_null_tv001\n");
}

static void test_add_rx_bytes_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    uintptr_t kleva_old_ir_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    interface_add_rx_bytes(iface, 0);
    uint32_t out_iface_ip_addr = iface->ip_addr;
    uint8_t out_iface_prefix_len = iface->prefix_len;
    uint16_t out_iface_mtu = iface->mtu;
    int out_iface_up = iface->up;
    int out_iface_link_nonnull = (iface->link != NULL);
    int out_iface_device_nonnull = (iface->device != NULL);
    uint64_t out_iface_tx_bytes = iface->tx_bytes;
    uint64_t out_iface_rx_bytes = iface->rx_bytes;
    int out_iface_rx_handler_nonnull = (iface->rx_handler != NULL);
    int out_iface_handler_ctx_nonnull = (iface->handler_ctx != NULL);
    int out_iface_arp_cache_nonnull = (iface->arp_cache != NULL);
    uint64_t out_iface_rx_dropped = iface->rx_dropped;
    uint64_t out_iface_rx_errors = iface->rx_errors;
    uint64_t out_iface_tx_errors = iface->tx_errors;
    int out_iface_state = iface->state;
    uint64_t out_iface_last_rx_time = iface->last_rx_time;
    uint64_t out_iface_last_tx_time = iface->last_tx_time;
    uint64_t out_iface_last_error_time = iface->last_error_time;
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_rx_bytes_n = ((uintptr_t)(iface->rx_bytes) == (kleva_old_iface_rx_bytes + (uintptr_t)(0)));
    int out_ir_post_iface_rx_bytes = ((uintptr_t)(iface->rx_bytes) == (uintptr_t)((kleva_old_ir_iface_rx_bytes + 0)));
    assert(out_iface_ip_addr == 1); /* EVA-proven oracle */
    assert(out_iface_prefix_len == 24); /* EVA-proven oracle */
    assert(out_iface_mtu == 1); /* EVA-proven oracle */
    assert(out_iface_up == 0); /* EVA-proven oracle */
    assert(out_iface_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_iface_rx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_tx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_state == 0); /* EVA-proven oracle */
    assert(out_iface_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_error_time == 0); /* EVA-proven oracle */
    assert(out_post_iface_rx_bytes_n == 1); /* EVA-proven oracle */
    assert(out_ir_post_iface_rx_bytes == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_rx_bytes_valid_tv001\n");
}

static void test_add_rx_bytes_ir_if_0_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    assert(iface != NULL);
    uintptr_t kleva_old_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    uintptr_t kleva_old_post_state_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    interface_add_rx_bytes(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_rx_bytes_n = ((uintptr_t)(iface->rx_bytes) == (kleva_old_iface_rx_bytes + (uintptr_t)(0)));
    int out_post_state_iface_rx_bytes_iface_rx_bytes_n = ((uintptr_t)(iface->rx_bytes) == (uintptr_t)((kleva_old_post_state_iface_rx_bytes + 0)));
    assert(out_post_iface_rx_bytes_n == 1); /* EVA-proven oracle */
    assert(out_post_state_iface_rx_bytes_iface_rx_bytes_n == 1); /* EVA-proven oracle */
    printf("PASS test_add_rx_bytes_ir_if_0_truthy_iface_tv001\n");
}

static void test_add_rx_bytes_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    iface = 0;
    interface_add_rx_bytes(iface, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_add_rx_bytes_ir_if_0_false_truthy_iface_tv001\n");
}

static void test_add_rx_bytes_ir_diversity_n_min_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    interface_add_rx_bytes(iface, 0);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_rx_bytes_n = ((uintptr_t)(iface->rx_bytes) == (kleva_old_iface_rx_bytes + (uintptr_t)(0)));
    assert(out_post_iface_rx_bytes_n == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_rx_bytes_ir_diversity_n_min_tv001\n");
}

static void test_add_rx_bytes_ir_diversity_n_one_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    uintptr_t kleva_old_iface_rx_bytes = (uintptr_t)(iface->rx_bytes);
    interface_add_rx_bytes(iface, 1);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_iface_rx_bytes_n = ((uintptr_t)(iface->rx_bytes) == (kleva_old_iface_rx_bytes + (uintptr_t)(1)));
    assert(out_post_iface_rx_bytes_n == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_rx_bytes_ir_diversity_n_one_tv001\n");
}

static void test_set_rx_handler_null_tv001(void) {
    interface_set_rx_handler(NULL, NULL, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_set_rx_handler_null_tv001\n");
}

static void test_set_rx_handler_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    RxHandler fn = kleva_stub_RxHandler;
    interface_set_rx_handler(iface, fn, NULL);
    uint32_t out_iface_ip_addr = iface->ip_addr;
    uint8_t out_iface_prefix_len = iface->prefix_len;
    uint16_t out_iface_mtu = iface->mtu;
    int out_iface_up = iface->up;
    int out_iface_link_nonnull = (iface->link != NULL);
    int out_iface_device_nonnull = (iface->device != NULL);
    uint64_t out_iface_tx_bytes = iface->tx_bytes;
    uint64_t out_iface_rx_bytes = iface->rx_bytes;
    int out_iface_rx_handler_nonnull = (iface->rx_handler != NULL);
    int out_iface_handler_ctx_nonnull = (iface->handler_ctx != NULL);
    int out_iface_arp_cache_nonnull = (iface->arp_cache != NULL);
    uint64_t out_iface_rx_dropped = iface->rx_dropped;
    uint64_t out_iface_rx_errors = iface->rx_errors;
    uint64_t out_iface_tx_errors = iface->tx_errors;
    int out_iface_state = iface->state;
    uint64_t out_iface_last_rx_time = iface->last_rx_time;
    uint64_t out_iface_last_tx_time = iface->last_tx_time;
    uint64_t out_iface_last_error_time = iface->last_error_time;
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_iface_rx_handler = ((uintptr_t)(iface->rx_handler) == (uintptr_t)(fn));
    int out_ir_post_iface_handler_ctx = ((uintptr_t)(iface->handler_ctx) == (uintptr_t)(NULL));
    assert(out_iface_ip_addr == 1); /* EVA-proven oracle */
    assert(out_iface_prefix_len == 24); /* EVA-proven oracle */
    assert(out_iface_mtu == 1); /* EVA-proven oracle */
    assert(out_iface_up == 0); /* EVA-proven oracle */
    assert(out_iface_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_handler_nonnull == 1); /* EVA-proven oracle */
    assert(out_iface_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_iface_rx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_tx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_state == 0); /* EVA-proven oracle */
    assert(out_iface_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_error_time == 0); /* EVA-proven oracle */
    assert(out_ir_post_iface_rx_handler == 1); /* EVA-proven oracle */
    assert(out_ir_post_iface_handler_ctx == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_rx_handler_valid_tv001\n");
}

static void test_set_rx_handler_ir_if_0_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    RxHandler fn = kleva_stub_RxHandler;
    assert(iface != NULL);
    interface_set_rx_handler(iface, fn, NULL);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_state_iface_rx_handler_fn = ((uintptr_t)(iface->rx_handler) == (uintptr_t)(fn));
    int out_post_state_iface_handler_ctx_ctx = ((uintptr_t)(iface->handler_ctx) == (uintptr_t)(NULL));
    assert(out_post_state_iface_rx_handler_fn == 1); /* EVA-proven oracle */
    assert(out_post_state_iface_handler_ctx_ctx == 1); /* EVA-proven oracle */
    printf("PASS test_set_rx_handler_ir_if_0_truthy_iface_tv001\n");
}

static void test_set_rx_handler_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    RxHandler fn = kleva_stub_RxHandler;
    iface = 0;
    interface_set_rx_handler(iface, fn, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_set_rx_handler_ir_if_0_false_truthy_iface_tv001\n");
}

static void test_set_arp_cache_null_tv001(void) {
    /* fixture-failed: unknown allocator for ArpCache *cache; using NULL */
    interface_set_arp_cache(NULL, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_set_arp_cache_null_tv001\n");
}

static void test_set_arp_cache_valid_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    interface_set_arp_cache(iface, NULL);
    uint32_t out_iface_ip_addr = iface->ip_addr;
    uint8_t out_iface_prefix_len = iface->prefix_len;
    uint16_t out_iface_mtu = iface->mtu;
    int out_iface_up = iface->up;
    int out_iface_link_nonnull = (iface->link != NULL);
    int out_iface_device_nonnull = (iface->device != NULL);
    uint64_t out_iface_tx_bytes = iface->tx_bytes;
    uint64_t out_iface_rx_bytes = iface->rx_bytes;
    int out_iface_rx_handler_nonnull = (iface->rx_handler != NULL);
    int out_iface_handler_ctx_nonnull = (iface->handler_ctx != NULL);
    int out_iface_arp_cache_nonnull = (iface->arp_cache != NULL);
    uint64_t out_iface_rx_dropped = iface->rx_dropped;
    uint64_t out_iface_rx_errors = iface->rx_errors;
    uint64_t out_iface_tx_errors = iface->tx_errors;
    int out_iface_state = iface->state;
    uint64_t out_iface_last_rx_time = iface->last_rx_time;
    uint64_t out_iface_last_tx_time = iface->last_tx_time;
    uint64_t out_iface_last_error_time = iface->last_error_time;
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_iface_arp_cache = ((uintptr_t)(iface->arp_cache) == (uintptr_t)(NULL));
    assert(out_iface_ip_addr == 1); /* EVA-proven oracle */
    assert(out_iface_prefix_len == 24); /* EVA-proven oracle */
    assert(out_iface_mtu == 1); /* EVA-proven oracle */
    assert(out_iface_up == 0); /* EVA-proven oracle */
    assert(out_iface_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_iface_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_iface_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_iface_rx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_tx_errors == 0); /* EVA-proven oracle */
    assert(out_iface_state == 0); /* EVA-proven oracle */
    assert(out_iface_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_iface_last_error_time == 0); /* EVA-proven oracle */
    assert(out_ir_post_iface_arp_cache == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_set_arp_cache_valid_tv001\n");
}

static void test_set_arp_cache_ir_if_0_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    assert(iface != NULL);
    interface_set_arp_cache(iface, NULL);
    /* oracle-deferred: post-call witness will be emitted below */
    int out_post_state_iface_arp_cache_cache = ((uintptr_t)(iface->arp_cache) == (uintptr_t)(NULL));
    assert(out_post_state_iface_arp_cache_cache == 1); /* EVA-proven oracle */
    printf("PASS test_set_arp_cache_ir_if_0_truthy_iface_tv001\n");
}

static void test_set_arp_cache_ir_if_0_false_truthy_iface_tv001(void) {
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t iface_mac_buf[64];
    memset(iface_mac_buf, 0, sizeof(iface_mac_buf));
    const uint8_t * iface_mac = iface_mac_buf;
    Interface *iface = interface_create("kleva", iface_mac, 1, 24, 1);
    assert(iface != NULL);
    void interface_free(Interface *arg0);
    iface = 0;
    interface_set_arp_cache(iface, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_set_arp_cache_ir_if_0_false_truthy_iface_tv001\n");
}

int main(void) {
    __kleva_alloc_reset();
    test_create_valid_tv001();
    __kleva_alloc_reset();
    test_create_ir_alloc_malloc_0_zero_failure_tv001();
    __kleva_alloc_reset();
    test_create_ir_alloc_malloc_0_zero_success_tv001();
    __kleva_alloc_reset();
    test_create_ir_diversity_mac_all_zero_tv001();
    __kleva_alloc_reset();
    test_create_ir_diversity_mac_all_0xff_tv001();
    __kleva_alloc_reset();
    test_create_ir_diversity_mac_first_byte_set_tv001();
    __kleva_alloc_reset();
    test_free_valid_tv001();
    __kleva_alloc_reset();
    test_set_up_null_tv001();
    __kleva_alloc_reset();
    test_set_up_valid_tv001();
    __kleva_alloc_reset();
    test_set_up_ir_if_0_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_set_up_ir_if_0_false_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_set_up_ir_diversity_up_min_tv001();
    __kleva_alloc_reset();
    test_set_up_ir_diversity_up_one_tv001();
    __kleva_alloc_reset();
    test_is_up_null_tv001();
    __kleva_alloc_reset();
    test_is_up_valid_tv001();
    __kleva_alloc_reset();
    test_is_up_ir_if_0_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_is_up_ir_if_0_false_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_set_link_null_tv001();
    __kleva_alloc_reset();
    test_set_link_valid_tv001();
    __kleva_alloc_reset();
    test_set_link_ir_if_0_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_set_link_ir_if_0_false_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_get_link_null_tv001();
    __kleva_alloc_reset();
    test_get_link_valid_tv001();
    __kleva_alloc_reset();
    test_get_link_ir_if_0_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_get_link_ir_if_0_false_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_get_mac_valid_tv001();
    __kleva_alloc_reset();
    test_get_ip_valid_tv001();
    __kleva_alloc_reset();
    test_add_tx_bytes_null_tv001();
    __kleva_alloc_reset();
    test_add_tx_bytes_valid_tv001();
    __kleva_alloc_reset();
    test_add_tx_bytes_ir_if_0_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_add_tx_bytes_ir_if_0_false_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_add_tx_bytes_ir_diversity_n_min_tv001();
    __kleva_alloc_reset();
    test_add_tx_bytes_ir_diversity_n_one_tv001();
    __kleva_alloc_reset();
    test_add_rx_bytes_null_tv001();
    __kleva_alloc_reset();
    test_add_rx_bytes_valid_tv001();
    __kleva_alloc_reset();
    test_add_rx_bytes_ir_if_0_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_add_rx_bytes_ir_if_0_false_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_add_rx_bytes_ir_diversity_n_min_tv001();
    __kleva_alloc_reset();
    test_add_rx_bytes_ir_diversity_n_one_tv001();
    __kleva_alloc_reset();
    test_set_rx_handler_null_tv001();
    __kleva_alloc_reset();
    test_set_rx_handler_valid_tv001();
    __kleva_alloc_reset();
    test_set_rx_handler_ir_if_0_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_set_rx_handler_ir_if_0_false_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_set_arp_cache_null_tv001();
    __kleva_alloc_reset();
    test_set_arp_cache_valid_tv001();
    __kleva_alloc_reset();
    test_set_arp_cache_ir_if_0_truthy_iface_tv001();
    __kleva_alloc_reset();
    test_set_arp_cache_ir_if_0_false_truthy_iface_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
