/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-07-02 17:01:57
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "mac_table.h"

#include "mac_table.h"
#include "interface.h"

static void test_table_init_null_tv001(void) {
    mac_table_init(NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_table_init_null_tv001\n");
}

static void test_table_init_valid_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    mac_table_init(&table);
    int out_table_count = table.count;
    int out_table__pad = table._pad;
    /* oracle-deferred: post-call witness will be emitted below */
    int out_ir_post_table_count = ((uintptr_t)(table.count) == (uintptr_t)(0));
    assert(out_table_count == 0); /* EVA-proven oracle */
    assert(out_table__pad == 0); /* EVA-proven oracle */
    assert(out_ir_post_table_count == 1); /* EVA-proven oracle */
    printf("PASS test_table_init_valid_tv001\n");
}

static void test_table_init_ir_if_0_not_table_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    mac_table_init(&table);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_table_init_ir_if_0_not_table_tv001\n");
}

static void test_table_init_ir_if_0_false_not_table_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    (void)0;
    mac_table_init(&table);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_table_init_ir_if_0_false_not_table_tv001\n");
}

static void test_table_learn_null_tv001(void) {
    MacEntry * out_ret = mac_table_learn(NULL, NULL, NULL, 0);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_table_learn_null_tv001\n");
}

static void test_table_learn_valid_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    printf("PASS test_table_learn_valid_tv001\n");
}

static void test_table_learn_ir_if_0_left_left_not_table_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_if_0_left_left_not_table_tv001\n");
}

static void test_table_learn_ir_if_0_left_right_not_mac_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    mac = 0;
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_same == 0); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_if_0_left_right_not_mac_tv001\n");
}

static void test_table_learn_ir_if_0_right_not_port_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    port = 0;
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_same == 0); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_if_0_right_not_port_tv001\n");
}

static void test_table_learn_ir_if_0_false_false_not_table_and_false_not_mac_and_false_not_port_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    (void)0;
    assert(mac != NULL);
    assert(port != NULL);
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_if_0_false_false_not_table_and_false_not_mac_and_false_not_port_tv001\n");
}

static void test_table_learn_ir_if_4_not_table_entries_i_valid_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    (void)0;
    assert(mac != NULL);
    assert(port != NULL);
    table.entries[0].valid = 0;
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_if_4_not_table_entries_i_valid_tv001\n");
}

static void test_table_learn_ir_if_4_false_not_table_entries_i_valid_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    (void)0;
    assert(mac != NULL);
    assert(port != NULL);
    table.entries[0].valid = 0;
    table.entries[0].valid = 1;
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_if_4_false_not_table_entries_i_valid_tv001\n");
}

static void test_table_learn_ir_call_guard_1_memcmp_eq_0_success_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    int out_table_count = table.count;
    int out_table__pad = table._pad;
    uint32_t out_port_ip_addr = port->ip_addr;
    uint8_t out_port_prefix_len = port->prefix_len;
    uint16_t out_port_mtu = port->mtu;
    int out_port_up = port->up;
    int out_port_link_nonnull = (port->link != NULL);
    int out_port_device_nonnull = (port->device != NULL);
    uint64_t out_port_tx_bytes = port->tx_bytes;
    uint64_t out_port_rx_bytes = port->rx_bytes;
    int out_port_rx_handler_nonnull = (port->rx_handler != NULL);
    int out_port_handler_ctx_nonnull = (port->handler_ctx != NULL);
    int out_port_arp_cache_nonnull = (port->arp_cache != NULL);
    uint64_t out_port_rx_dropped = port->rx_dropped;
    uint64_t out_port_rx_errors = port->rx_errors;
    uint64_t out_port_tx_errors = port->tx_errors;
    int out_port_state = port->state;
    uint64_t out_port_last_rx_time = port->last_rx_time;
    uint64_t out_port_last_tx_time = port->last_tx_time;
    uint64_t out_port_last_error_time = port->last_error_time;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    assert(out_table_count == 1); /* EVA-proven oracle */
    assert(out_table__pad == 0); /* EVA-proven oracle */
    assert(out_port_ip_addr == 1); /* EVA-proven oracle */
    assert(out_port_prefix_len == 24); /* EVA-proven oracle */
    assert(out_port_mtu == 1); /* EVA-proven oracle */
    assert(out_port_up == 0); /* EVA-proven oracle */
    assert(out_port_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_port_rx_errors == 0); /* EVA-proven oracle */
    assert(out_port_tx_errors == 0); /* EVA-proven oracle */
    assert(out_port_state == 0); /* EVA-proven oracle */
    assert(out_port_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_error_time == 0); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_call_guard_1_memcmp_eq_0_success_tv001\n");
}

static void test_table_learn_ir_call_guard_1_memcmp_eq_0_failure_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    int out_table_count = table.count;
    int out_table__pad = table._pad;
    uint32_t out_port_ip_addr = port->ip_addr;
    uint8_t out_port_prefix_len = port->prefix_len;
    uint16_t out_port_mtu = port->mtu;
    int out_port_up = port->up;
    int out_port_link_nonnull = (port->link != NULL);
    int out_port_device_nonnull = (port->device != NULL);
    uint64_t out_port_tx_bytes = port->tx_bytes;
    uint64_t out_port_rx_bytes = port->rx_bytes;
    int out_port_rx_handler_nonnull = (port->rx_handler != NULL);
    int out_port_handler_ctx_nonnull = (port->handler_ctx != NULL);
    int out_port_arp_cache_nonnull = (port->arp_cache != NULL);
    uint64_t out_port_rx_dropped = port->rx_dropped;
    uint64_t out_port_rx_errors = port->rx_errors;
    uint64_t out_port_tx_errors = port->tx_errors;
    int out_port_state = port->state;
    uint64_t out_port_last_rx_time = port->last_rx_time;
    uint64_t out_port_last_tx_time = port->last_tx_time;
    uint64_t out_port_last_error_time = port->last_error_time;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    assert(out_table_count == 1); /* EVA-proven oracle */
    assert(out_table__pad == 0); /* EVA-proven oracle */
    assert(out_port_ip_addr == 1); /* EVA-proven oracle */
    assert(out_port_prefix_len == 24); /* EVA-proven oracle */
    assert(out_port_mtu == 1); /* EVA-proven oracle */
    assert(out_port_up == 0); /* EVA-proven oracle */
    assert(out_port_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_port_rx_errors == 0); /* EVA-proven oracle */
    assert(out_port_tx_errors == 0); /* EVA-proven oracle */
    assert(out_port_state == 0); /* EVA-proven oracle */
    assert(out_port_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_error_time == 0); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_call_guard_1_memcmp_eq_0_failure_tv001\n");
}

static void test_table_learn_ir_call_guard_2_memcmp_eq_0_success_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    int out_table_count = table.count;
    int out_table__pad = table._pad;
    uint32_t out_port_ip_addr = port->ip_addr;
    uint8_t out_port_prefix_len = port->prefix_len;
    uint16_t out_port_mtu = port->mtu;
    int out_port_up = port->up;
    int out_port_link_nonnull = (port->link != NULL);
    int out_port_device_nonnull = (port->device != NULL);
    uint64_t out_port_tx_bytes = port->tx_bytes;
    uint64_t out_port_rx_bytes = port->rx_bytes;
    int out_port_rx_handler_nonnull = (port->rx_handler != NULL);
    int out_port_handler_ctx_nonnull = (port->handler_ctx != NULL);
    int out_port_arp_cache_nonnull = (port->arp_cache != NULL);
    uint64_t out_port_rx_dropped = port->rx_dropped;
    uint64_t out_port_rx_errors = port->rx_errors;
    uint64_t out_port_tx_errors = port->tx_errors;
    int out_port_state = port->state;
    uint64_t out_port_last_rx_time = port->last_rx_time;
    uint64_t out_port_last_tx_time = port->last_tx_time;
    uint64_t out_port_last_error_time = port->last_error_time;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    assert(out_table_count == 1); /* EVA-proven oracle */
    assert(out_table__pad == 0); /* EVA-proven oracle */
    assert(out_port_ip_addr == 1); /* EVA-proven oracle */
    assert(out_port_prefix_len == 24); /* EVA-proven oracle */
    assert(out_port_mtu == 1); /* EVA-proven oracle */
    assert(out_port_up == 0); /* EVA-proven oracle */
    assert(out_port_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_port_rx_errors == 0); /* EVA-proven oracle */
    assert(out_port_tx_errors == 0); /* EVA-proven oracle */
    assert(out_port_state == 0); /* EVA-proven oracle */
    assert(out_port_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_error_time == 0); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_call_guard_2_memcmp_eq_0_success_tv001\n");
}

static void test_table_learn_ir_call_guard_2_memcmp_eq_0_failure_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    int out_table_count = table.count;
    int out_table__pad = table._pad;
    uint32_t out_port_ip_addr = port->ip_addr;
    uint8_t out_port_prefix_len = port->prefix_len;
    uint16_t out_port_mtu = port->mtu;
    int out_port_up = port->up;
    int out_port_link_nonnull = (port->link != NULL);
    int out_port_device_nonnull = (port->device != NULL);
    uint64_t out_port_tx_bytes = port->tx_bytes;
    uint64_t out_port_rx_bytes = port->rx_bytes;
    int out_port_rx_handler_nonnull = (port->rx_handler != NULL);
    int out_port_handler_ctx_nonnull = (port->handler_ctx != NULL);
    int out_port_arp_cache_nonnull = (port->arp_cache != NULL);
    uint64_t out_port_rx_dropped = port->rx_dropped;
    uint64_t out_port_rx_errors = port->rx_errors;
    uint64_t out_port_tx_errors = port->tx_errors;
    int out_port_state = port->state;
    uint64_t out_port_last_rx_time = port->last_rx_time;
    uint64_t out_port_last_tx_time = port->last_tx_time;
    uint64_t out_port_last_error_time = port->last_error_time;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    assert(out_table_count == 1); /* EVA-proven oracle */
    assert(out_table__pad == 0); /* EVA-proven oracle */
    assert(out_port_ip_addr == 1); /* EVA-proven oracle */
    assert(out_port_prefix_len == 24); /* EVA-proven oracle */
    assert(out_port_mtu == 1); /* EVA-proven oracle */
    assert(out_port_up == 0); /* EVA-proven oracle */
    assert(out_port_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_port_rx_errors == 0); /* EVA-proven oracle */
    assert(out_port_tx_errors == 0); /* EVA-proven oracle */
    assert(out_port_state == 0); /* EVA-proven oracle */
    assert(out_port_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_error_time == 0); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_call_guard_2_memcmp_eq_0_failure_tv001\n");
}

static void test_table_learn_ir_diversity_mac_all_zero_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    /* diversity: byte-buffer mac all-zero */
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_diversity_mac_all_zero_tv001\n");
}

static void test_table_learn_ir_diversity_mac_all_0xff_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[64];
    memset(mac_buf, 0xFF, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    /* diversity: byte-buffer mac all-0xff */
    MacEntry * out_ret = mac_table_learn(&table, mac, port, 0);
    int out_ret_nonnull = (out_ret != NULL);
    int out_port_same = (out_ret != NULL && out_ret->port == port);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_port_same == 1); /* EVA-proven oracle */
    printf("PASS test_table_learn_ir_diversity_mac_all_0xff_tv001\n");
}

static void test_table_lookup_null_tv001(void) {
    Interface * out_ret = mac_table_lookup(NULL, NULL);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_null_tv001\n");
}

static void test_table_lookup_valid_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = mac_table_lookup(&table, mac);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_valid_tv001\n");
}

static void test_table_lookup_ir_if_0_left_not_table_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = mac_table_lookup(&table, mac);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_ir_if_0_left_not_table_tv001\n");
}

static void test_table_lookup_ir_if_0_right_not_mac_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    mac = 0;
    Interface * out_ret = mac_table_lookup(&table, mac);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_ir_if_0_right_not_mac_tv001\n");
}

static void test_table_lookup_ir_if_0_false_false_not_table_and_false_not_mac_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    (void)0;
    assert(mac != NULL);
    Interface * out_ret = mac_table_lookup(&table, mac);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_ir_if_0_false_false_not_table_and_false_not_mac_tv001\n");
}

static void test_table_lookup_ir_call_guard_1_memcmp_eq_0_success_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = mac_table_lookup(&table, mac);
    int out_ret_nonnull = (out_ret != NULL);
    int out_table_count = table.count;
    int out_table__pad = table._pad;
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_table_count == 0); /* EVA-proven oracle */
    assert(out_table__pad == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_ir_call_guard_1_memcmp_eq_0_success_tv001\n");
}

static void test_table_lookup_ir_call_guard_1_memcmp_eq_0_failure_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[6];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    Interface * out_ret = mac_table_lookup(&table, mac);
    int out_ret_nonnull = (out_ret != NULL);
    int out_table_count = table.count;
    int out_table__pad = table._pad;
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_table_count == 0); /* EVA-proven oracle */
    assert(out_table__pad == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_ir_call_guard_1_memcmp_eq_0_failure_tv001\n");
}

static void test_table_lookup_ir_diversity_mac_all_zero_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    /* diversity: byte-buffer mac all-zero */
    Interface * out_ret = mac_table_lookup(&table, mac);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_ir_diversity_mac_all_zero_tv001\n");
}

static void test_table_lookup_ir_diversity_mac_all_0xff_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[64];
    memset(mac_buf, 0xFF, sizeof(mac_buf));
    const uint8_t * mac = mac_buf;
    /* diversity: byte-buffer mac all-0xff */
    Interface * out_ret = mac_table_lookup(&table, mac);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_ir_diversity_mac_all_0xff_tv001\n");
}

static void test_table_lookup_ir_diversity_mac_first_byte_set_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    uint8_t mac_buf[64];
    memset(mac_buf, 0, sizeof(mac_buf));
    if (sizeof(mac_buf) > 0) mac_buf[0] = 1;
    const uint8_t * mac = mac_buf;
    /* diversity: byte-buffer mac first-byte-set */
    Interface * out_ret = mac_table_lookup(&table, mac);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_table_lookup_ir_diversity_mac_first_byte_set_tv001\n");
}

static void test_table_age_null_tv001(void) {
    mac_table_age(NULL, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_table_age_null_tv001\n");
}

static void test_table_age_valid_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    mac_table_age(&table, 0);
    int out_table_count = table.count;
    int out_table__pad = table._pad;
    /* oracle-deferred: post-call witness will be emitted below */
    assert(out_table_count == 0); /* EVA-proven oracle */
    assert(out_table__pad == 0); /* EVA-proven oracle */
    printf("PASS test_table_age_valid_tv001\n");
}

static void test_table_age_ir_if_0_not_table_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    mac_table_age(&table, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_table_age_ir_if_0_not_table_tv001\n");
}

static void test_table_age_ir_if_0_false_not_table_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    table.entries[0] = table_entries_0;
    (void)0;
    mac_table_age(&table, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_table_age_ir_if_0_false_not_table_tv001\n");
}

static void test_table_age_ir_diversity_now_min_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    mac_table_age(&table, 0);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_table_age_ir_diversity_now_min_tv001\n");
}

static void test_table_age_ir_diversity_now_one_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    mac_table_age(&table, 1);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_table_age_ir_diversity_now_one_tv001\n");
}

static void test_table_flush_port_null_tv001(void) {
    mac_table_flush_port(NULL, NULL);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    printf("PASS test_table_flush_port_null_tv001\n");
}

static void test_table_flush_port_valid_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    mac_table_flush_port(&table, port);
    int out_table_count = table.count;
    int out_table__pad = table._pad;
    uint32_t out_port_ip_addr = port->ip_addr;
    uint8_t out_port_prefix_len = port->prefix_len;
    uint16_t out_port_mtu = port->mtu;
    int out_port_up = port->up;
    int out_port_link_nonnull = (port->link != NULL);
    int out_port_device_nonnull = (port->device != NULL);
    uint64_t out_port_tx_bytes = port->tx_bytes;
    uint64_t out_port_rx_bytes = port->rx_bytes;
    int out_port_rx_handler_nonnull = (port->rx_handler != NULL);
    int out_port_handler_ctx_nonnull = (port->handler_ctx != NULL);
    int out_port_arp_cache_nonnull = (port->arp_cache != NULL);
    uint64_t out_port_rx_dropped = port->rx_dropped;
    uint64_t out_port_rx_errors = port->rx_errors;
    uint64_t out_port_tx_errors = port->tx_errors;
    int out_port_state = port->state;
    uint64_t out_port_last_rx_time = port->last_rx_time;
    uint64_t out_port_last_tx_time = port->last_tx_time;
    uint64_t out_port_last_error_time = port->last_error_time;
    /* oracle-deferred: post-call witness will be emitted below */
    assert(out_table_count == 0); /* EVA-proven oracle */
    assert(out_table__pad == 0); /* EVA-proven oracle */
    assert(out_port_ip_addr == 1); /* EVA-proven oracle */
    assert(out_port_prefix_len == 24); /* EVA-proven oracle */
    assert(out_port_mtu == 1); /* EVA-proven oracle */
    assert(out_port_up == 0); /* EVA-proven oracle */
    assert(out_port_link_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_device_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_tx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_bytes == 0); /* EVA-proven oracle */
    assert(out_port_rx_handler_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_handler_ctx_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_arp_cache_nonnull == 0); /* EVA-proven oracle */
    assert(out_port_rx_dropped == 0); /* EVA-proven oracle */
    assert(out_port_rx_errors == 0); /* EVA-proven oracle */
    assert(out_port_tx_errors == 0); /* EVA-proven oracle */
    assert(out_port_state == 0); /* EVA-proven oracle */
    assert(out_port_last_rx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_tx_time == 0); /* EVA-proven oracle */
    assert(out_port_last_error_time == 0); /* EVA-proven oracle */
    interface_free(port);
    printf("PASS test_table_flush_port_valid_tv001\n");
}

static void test_table_flush_port_ir_if_0_left_not_table_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    mac_table_flush_port(&table, port);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    interface_free(port);
    printf("PASS test_table_flush_port_ir_if_0_left_not_table_tv001\n");
}

static void test_table_flush_port_ir_if_0_right_not_port_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    port = 0;
    mac_table_flush_port(&table, port);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    interface_free(port);
    printf("PASS test_table_flush_port_ir_if_0_right_not_port_tv001\n");
}

static void test_table_flush_port_ir_if_0_false_false_not_table_and_false_not_port_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    (void)0;
    assert(port != NULL);
    mac_table_flush_port(&table, port);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    interface_free(port);
    printf("PASS test_table_flush_port_ir_if_0_false_false_not_table_and_false_not_port_tv001\n");
}

static void test_table_flush_port_ir_table_table__entries_port_hit_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    table.entries[0].port = port;
    mac_table_flush_port(&table, port);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    interface_free(port);
    printf("PASS test_table_flush_port_ir_table_table__entries_port_hit_tv001\n");
}

static void test_table_flush_port_ir_table_table__entries_port_miss_tv001(void) {
    MacTable table;
    memset(&table, 0, sizeof(table));
    MacEntry table_entries_0;
    memset(&table_entries_0, 0, sizeof(table_entries_0));
    Interface table_entries_0_port;
    memset(&table_entries_0_port, 0, sizeof(table_entries_0_port));
    table_entries_0.port = &table_entries_0_port;
    table.entries[0] = table_entries_0;
    Interface * interface_create(const char * name, const uint8_t * mac, uint32_t ip_addr, uint8_t prefix_len, uint16_t mtu);
    uint8_t port_mac_buf[64];
    memset(port_mac_buf, 0, sizeof(port_mac_buf));
    const uint8_t * port_mac = port_mac_buf;
    Interface *port = interface_create("kleva", port_mac, 1, 24, 1);
    assert(port != NULL);
    void interface_free(Interface *arg0);
    table.entries[0].port = 0;
    mac_table_flush_port(&table, port);
    int out_call_completed = 1;
    assert(out_call_completed == 1); /* EVA-proven oracle */
    interface_free(port);
    printf("PASS test_table_flush_port_ir_table_table__entries_port_miss_tv001\n");
}

int main(void) {
    test_table_init_null_tv001();
    test_table_init_valid_tv001();
    test_table_init_ir_if_0_not_table_tv001();
    test_table_init_ir_if_0_false_not_table_tv001();
    test_table_learn_null_tv001();
    test_table_learn_valid_tv001();
    test_table_learn_ir_if_0_left_left_not_table_tv001();
    test_table_learn_ir_if_0_left_right_not_mac_tv001();
    test_table_learn_ir_if_0_right_not_port_tv001();
    test_table_learn_ir_if_0_false_false_not_table_and_false_not_mac_and_false_not_port_tv001();
    test_table_learn_ir_if_4_not_table_entries_i_valid_tv001();
    test_table_learn_ir_if_4_false_not_table_entries_i_valid_tv001();
    test_table_learn_ir_call_guard_1_memcmp_eq_0_success_tv001();
    test_table_learn_ir_call_guard_1_memcmp_eq_0_failure_tv001();
    test_table_learn_ir_call_guard_2_memcmp_eq_0_success_tv001();
    test_table_learn_ir_call_guard_2_memcmp_eq_0_failure_tv001();
    test_table_learn_ir_diversity_mac_all_zero_tv001();
    test_table_learn_ir_diversity_mac_all_0xff_tv001();
    test_table_lookup_null_tv001();
    test_table_lookup_valid_tv001();
    test_table_lookup_ir_if_0_left_not_table_tv001();
    test_table_lookup_ir_if_0_right_not_mac_tv001();
    test_table_lookup_ir_if_0_false_false_not_table_and_false_not_mac_tv001();
    test_table_lookup_ir_call_guard_1_memcmp_eq_0_success_tv001();
    test_table_lookup_ir_call_guard_1_memcmp_eq_0_failure_tv001();
    test_table_lookup_ir_diversity_mac_all_zero_tv001();
    test_table_lookup_ir_diversity_mac_all_0xff_tv001();
    test_table_lookup_ir_diversity_mac_first_byte_set_tv001();
    test_table_age_null_tv001();
    test_table_age_valid_tv001();
    test_table_age_ir_if_0_not_table_tv001();
    test_table_age_ir_if_0_false_not_table_tv001();
    test_table_age_ir_diversity_now_min_tv001();
    test_table_age_ir_diversity_now_one_tv001();
    test_table_flush_port_null_tv001();
    test_table_flush_port_valid_tv001();
    test_table_flush_port_ir_if_0_left_not_table_tv001();
    test_table_flush_port_ir_if_0_right_not_port_tv001();
    test_table_flush_port_ir_if_0_false_false_not_table_and_false_not_port_tv001();
    test_table_flush_port_ir_table_table__entries_port_hit_tv001();
    test_table_flush_port_ir_table_table__entries_port_miss_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
