/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-05-25 18:14:21
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "topology.h"

static void test_create_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    int    out_dev_count  = t->dev_count;
    int    out_link_count = t->link_count;
    int    out_dev_cap_ok  = (t->dev_cap > 0) ? 1 : 0;
    int    out_link_cap_ok = (t->link_cap > 0) ? 1 : 0;
    assert(out_dev_count == 0); /* EVA-proven oracle */
    assert(out_link_count == 0); /* EVA-proven oracle */
    assert(out_dev_cap_ok == 1); /* EVA-proven oracle */
    assert(out_link_cap_ok == 1); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_create_tv001\n");
}

static void test_free_null_tv001(void) {
    topology_free(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_free_null_tv001\n");
}

static void test_add_device_ok_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    Device *dev = device_create("R1", 4);
    assert(dev != NULL);
    int out_ret   = topology_add_device(t, dev);
    int out_count = t->dev_count;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_count == 1); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_add_device_ok_tv001\n");
}

static void test_add_device_null_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    Device *dev = device_create("R1", 4);
    assert(dev != NULL);
    int out_null_topo = topology_add_device(NULL, dev);
    int out_null_dev  = topology_add_device(t, NULL);
    assert(out_null_topo == -1); /* EVA-proven oracle */
    assert(out_null_dev == -1); /* EVA-proven oracle */
    topology_free(t);
    device_free(dev);
    printf("PASS test_add_device_null_tv001\n");
}

static void test_add_link_ok_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    uint8_t mac_a[6] = {0x11,0x11,0x11,0x11,0x11,0x11};
    uint8_t mac_b[6] = {0x22,0x22,0x22,0x22,0x22,0x22};
    Interface *a = interface_create("eth0", mac_a, 0xC0A80001, 24, 1500);
    assert(a != NULL);
    Interface *b = interface_create("eth1", mac_b, 0xC0A80002, 24, 1500);
    assert(b != NULL);
    Link *lnk = link_create(a, b, 1000, 1, 0.0f);
    assert(lnk != NULL);
    int out_ret   = topology_add_link(t, lnk);
    int out_count = t->link_count;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_count == 1); /* EVA-proven oracle */
    topology_free(t);
    interface_free(a);
    interface_free(b);
    printf("PASS test_add_link_ok_tv001\n");
}

static void test_add_link_null_tv001(void) {
    uint8_t mac_a[6] = {0x11,0x11,0x11,0x11,0x11,0x11};
    uint8_t mac_b[6] = {0x22,0x22,0x22,0x22,0x22,0x22};
    Interface *a = interface_create("eth0", mac_a, 0xC0A80001, 24, 1500);
    assert(a != NULL);
    Interface *b = interface_create("eth1", mac_b, 0xC0A80002, 24, 1500);
    assert(b != NULL);
    Link *lnk = link_create(a, b, 1000, 1, 0.0f);
    assert(lnk != NULL);
    int out_null_topo = topology_add_link(NULL, lnk);
    int out_null_link = topology_add_link(NULL, NULL);
    assert(out_null_topo == -1); /* EVA-proven oracle */
    assert(out_null_link == -1); /* EVA-proven oracle */
    link_free(lnk);
    interface_free(a);
    interface_free(b);
    printf("PASS test_add_link_null_tv001\n");
}

static void test_find_device_by_name_found_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    Device *dev = device_create("Router-A", 4);
    assert(dev != NULL);
    topology_add_device(t, dev);
    Device *out_found = topology_find_device_by_name(t, "Router-A");
    int out_match = (out_found == dev) ? 1 : 0;
    assert(out_match == 1); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_find_device_by_name_found_tv001\n");
}

static void test_find_device_by_name_not_found_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    Device *dev = device_create("Router-A", 4);
    assert(dev != NULL);
    topology_add_device(t, dev);
    Device *out_result = topology_find_device_by_name(t, "Router-B");
    int out_is_null = (out_result == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_find_device_by_name_not_found_tv001\n");
}

static void test_find_device_by_name_null_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    Device *r1 = topology_find_device_by_name(NULL, "R");
    Device *r2 = topology_find_device_by_name(t, NULL);
    int out_null_topo = (r1 == NULL) ? 1 : 0;
    int out_null_name = (r2 == NULL) ? 1 : 0;
    assert(out_null_topo == 1); /* EVA-proven oracle */
    assert(out_null_name == 1); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_find_device_by_name_null_tv001\n");
}

static void test_find_device_by_ip_found_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    Device *dev = device_create("R1", 4);
    assert(dev != NULL);
    uint8_t mac[6] = {0x11,0x22,0x33,0x44,0x55,0x66};
    Interface *iface = interface_create("eth0", mac, 0xC0A80001, 24, 1500);
    assert(iface != NULL);
    device_add_interface(dev, iface);
    topology_add_device(t, dev);
    Device *out_found = topology_find_device_by_ip(t, 0xC0A80001);
    int out_match = (out_found == dev) ? 1 : 0;
    assert(out_match == 1); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_find_device_by_ip_found_tv001\n");
}

static void test_find_device_by_ip_not_found_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    Device *dev = device_create("R1", 4);
    assert(dev != NULL);
    uint8_t mac[6] = {0x11,0x22,0x33,0x44,0x55,0x66};
    Interface *iface = interface_create("eth0", mac, 0xC0A80001, 24, 1500);
    assert(iface != NULL);
    device_add_interface(dev, iface);
    topology_add_device(t, dev);
    Device *out_result = topology_find_device_by_ip(t, 0xDEADBEEF);
    int out_is_null = (out_result == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_find_device_by_ip_not_found_tv001\n");
}

static void test_find_device_by_ip_null_tv001(void) {
    Device *out_result = topology_find_device_by_ip(NULL, 0xC0A80001);
    int out_is_null = (out_result == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    printf("PASS test_find_device_by_ip_null_tv001\n");
}

static void test_get_link_between_found_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    uint8_t mac_a[6] = {0x11,0x11,0x11,0x11,0x11,0x11};
    uint8_t mac_b[6] = {0x22,0x22,0x22,0x22,0x22,0x22};
    Interface *a = interface_create("eth0", mac_a, 0xC0A80001, 24, 1500);
    assert(a != NULL);
    Interface *b = interface_create("eth1", mac_b, 0xC0A80002, 24, 1500);
    assert(b != NULL);
    Link *lnk = link_create(a, b, 1000, 1, 0.0f);
    assert(lnk != NULL);
    topology_add_link(t, lnk);
    Link *out_found = topology_get_link_between(t, a, b);
    int out_match = (out_found == lnk) ? 1 : 0;
    assert(out_match == 1); /* EVA-proven oracle */
    topology_free(t);
    interface_free(a);
    interface_free(b);
    printf("PASS test_get_link_between_found_tv001\n");
}

static void test_get_link_between_reverse_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    uint8_t mac_a[6] = {0x11,0x11,0x11,0x11,0x11,0x11};
    uint8_t mac_b[6] = {0x22,0x22,0x22,0x22,0x22,0x22};
    Interface *a = interface_create("eth0", mac_a, 0xC0A80001, 24, 1500);
    assert(a != NULL);
    Interface *b = interface_create("eth1", mac_b, 0xC0A80002, 24, 1500);
    assert(b != NULL);
    Link *lnk = link_create(a, b, 1000, 1, 0.0f);
    assert(lnk != NULL);
    topology_add_link(t, lnk);
    Link *out_found = topology_get_link_between(t, b, a);
    int out_match = (out_found == lnk) ? 1 : 0;
    assert(out_match == 1); /* EVA-proven oracle */
    topology_free(t);
    interface_free(a);
    interface_free(b);
    printf("PASS test_get_link_between_reverse_tv001\n");
}

static void test_get_link_between_not_found_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    uint8_t mac_a[6] = {0x11,0x11,0x11,0x11,0x11,0x11};
    uint8_t mac_b[6] = {0x22,0x22,0x22,0x22,0x22,0x22};
    uint8_t mac_c[6] = {0x33,0x33,0x33,0x33,0x33,0x33};
    Interface *a = interface_create("eth0", mac_a, 0xC0A80001, 24, 1500);
    assert(a != NULL);
    Interface *b = interface_create("eth1", mac_b, 0xC0A80002, 24, 1500);
    assert(b != NULL);
    Interface *c = interface_create("eth2", mac_c, 0xC0A80003, 24, 1500);
    assert(c != NULL);
    Link *lnk = link_create(a, b, 1000, 1, 0.0f);
    assert(lnk != NULL);
    topology_add_link(t, lnk);
    Link *out_result = topology_get_link_between(t, a, c);
    int out_is_null = (out_result == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    topology_free(t);
    interface_free(a);
    interface_free(b);
    interface_free(c);
    printf("PASS test_get_link_between_not_found_tv001\n");
}

static void test_get_link_between_null_tv001(void) {
    uint8_t mac_a[6] = {0x11,0x11,0x11,0x11,0x11,0x11};
    uint8_t mac_b[6] = {0x22,0x22,0x22,0x22,0x22,0x22};
    Interface *a = interface_create("eth0", mac_a, 0xC0A80001, 24, 1500);
    assert(a != NULL);
    Interface *b = interface_create("eth1", mac_b, 0xC0A80002, 24, 1500);
    assert(b != NULL);
    Link *r1 = topology_get_link_between(NULL, a, b);
    Link *r2 = topology_get_link_between(NULL, NULL, NULL);
    int out_null_topo  = (r1 == NULL) ? 1 : 0;
    int out_all_null   = (r2 == NULL) ? 1 : 0;
    assert(out_null_topo == 1); /* EVA-proven oracle */
    assert(out_all_null == 1); /* EVA-proven oracle */
    interface_free(a);
    interface_free(b);
    printf("PASS test_get_link_between_null_tv001\n");
}

static void test_device_count_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    Device *dev = device_create("R1", 4);
    assert(dev != NULL);
    topology_add_device(t, dev);
    int out_count      = topology_device_count(t);
    int out_null_count = topology_device_count(NULL);
    assert(out_count == 1); /* EVA-proven oracle */
    assert(out_null_count == 0); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_device_count_tv001\n");
}

static void test_link_count_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    uint8_t mac_a[6] = {0x11,0x11,0x11,0x11,0x11,0x11};
    uint8_t mac_b[6] = {0x22,0x22,0x22,0x22,0x22,0x22};
    Interface *a = interface_create("eth0", mac_a, 0xC0A80001, 24, 1500);
    assert(a != NULL);
    Interface *b = interface_create("eth1", mac_b, 0xC0A80002, 24, 1500);
    assert(b != NULL);
    Link *lnk = link_create(a, b, 1000, 1, 0.0f);
    assert(lnk != NULL);
    topology_add_link(t, lnk);
    int out_count      = topology_link_count(t);
    int out_null_count = topology_link_count(NULL);
    assert(out_count == 1); /* EVA-proven oracle */
    assert(out_null_count == 0); /* EVA-proven oracle */
    topology_free(t);
    interface_free(a);
    interface_free(b);
    printf("PASS test_link_count_tv001\n");
}

static void test_grow_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    for (int i = 0; i < 9; i++) {
        Device *d = device_create("R", 1);
        if (!d) break;
        topology_add_device(t, d);
    }
    int out_count  = t->dev_count;
    int out_cap_ok = (t->dev_cap >= 9) ? 1 : 0;
    assert(out_count == 9); /* EVA-proven oracle */
    assert(out_cap_ok == 1); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_grow_tv001\n");
}

static void test_grow_links_tv001(void) {
    Topology *t = topology_create();
    assert(t != NULL);
    for (int i = 0; i < 9; i++) {
        uint8_t ma[6] = {0x11,(uint8_t)i,0,0,0,0};
        uint8_t mb[6] = {0x22,(uint8_t)i,0,0,0,0};
        Interface *a = interface_create("a", ma, (uint32_t)(0xC0A80000+i*2),   24, 1500);
        Interface *b = interface_create("b", mb, (uint32_t)(0xC0A80001+i*2), 24, 1500);
        if (!a || !b) { interface_free(a); interface_free(b); break; }
        Link *lnk = link_create(a, b, 1000, 1, 0.0f);
        if (!lnk) { interface_free(a); interface_free(b); break; }
        topology_add_link(t, lnk);
    }
    int out_count  = t->link_count;
    int out_cap_ok = (t->link_cap >= 9) ? 1 : 0;
    assert(out_count == 9); /* EVA-proven oracle */
    assert(out_cap_ok == 1); /* EVA-proven oracle */
    topology_free(t);
    printf("PASS test_grow_links_tv001\n");
}

int main(void) {
    test_create_tv001();
    test_free_null_tv001();
    test_add_device_ok_tv001();
    test_add_device_null_tv001();
    test_add_link_ok_tv001();
    test_add_link_null_tv001();
    test_find_device_by_name_found_tv001();
    test_find_device_by_name_not_found_tv001();
    test_find_device_by_name_null_tv001();
    test_find_device_by_ip_found_tv001();
    test_find_device_by_ip_not_found_tv001();
    test_find_device_by_ip_null_tv001();
    test_get_link_between_found_tv001();
    test_get_link_between_reverse_tv001();
    test_get_link_between_not_found_tv001();
    test_get_link_between_null_tv001();
    test_device_count_tv001();
    test_link_count_tv001();
    test_grow_tv001();
    test_grow_links_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
