/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-01 11:09:54
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "device.h"

static void test_create_tv001(void) {
    int iface_max = (int)8ULL;
    Device *dev = device_create("Router-A", iface_max);
    assert(dev != NULL);
    int out_count = dev->iface_count;
    int out_max   = dev->iface_max;
    assert(out_count == 0); /* EVA-proven oracle */
    assert(out_max == 8); /* EVA-proven oracle */
    device_free(dev);
    printf("PASS test_create_tv001\n");
}

static void test_create_tv002(void) {
    int iface_max = (int)1ULL;
    Device *dev = device_create("Router-A", iface_max);
    assert(dev != NULL);
    int out_count = dev->iface_count;
    int out_max   = dev->iface_max;
    assert(out_count == 0); /* EVA-proven oracle */
    assert(out_max == 1); /* EVA-proven oracle */
    device_free(dev);
    printf("PASS test_create_tv002\n");
}

static void test_create_null_tv001(void) {
    Device *d1 = device_create(NULL, 4);
    Device *d2 = device_create("R", 0);
    Device *d3 = device_create("R", -1);
    int out_null_name     = (d1 == NULL) ? 1 : 0;
    int out_zero_max      = (d2 == NULL) ? 1 : 0;
    int out_negative_max  = (d3 == NULL) ? 1 : 0;
    assert(out_null_name == 1); /* EVA-proven oracle */
    assert(out_zero_max == 1); /* EVA-proven oracle */
    assert(out_negative_max == 1); /* EVA-proven oracle */
    printf("PASS test_create_null_tv001\n");
}

static void test_free_null_tv001(void) {
    device_free(NULL);
    int out_ok = 1;
    assert(out_ok == 1); /* EVA-proven oracle */
    printf("PASS test_free_null_tv001\n");
}

static void test_add_interface_ok_tv001(void) {
    Device *dev = device_create("R", 4);
    assert(dev != NULL);
    uint8_t mac[6] = {0x11,0x22,0x33,0x44,0x55,0x66};
    Interface *iface = interface_create("eth0", mac, 0xC0A80001, 24, 1500);
    assert(iface != NULL);
    int out_ret    = device_add_interface(dev, iface);
    int out_count  = dev->iface_count;
    int out_backptr = (iface->device == dev) ? 1 : 0;
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_count == 1); /* EVA-proven oracle */
    assert(out_backptr == 1); /* EVA-proven oracle */
    device_free(dev);
    printf("PASS test_add_interface_ok_tv001\n");
}

static void test_add_interface_duplicate_tv001(void) {
    Device *dev = device_create("R", 4);
    assert(dev != NULL);
    uint8_t mac_a[6] = {0x11,0x11,0x11,0x11,0x11,0x11};
    uint8_t mac_b[6] = {0x22,0x22,0x22,0x22,0x22,0x22};
    Interface *a = interface_create("eth0", mac_a, 0xC0A80001, 24, 1500);
    assert(a != NULL);
    Interface *b = interface_create("eth0", mac_b, 0xC0A80002, 24, 1500);
    assert(b != NULL);
    device_add_interface(dev, a);
    int out_dup = device_add_interface(dev, b);
    int out_count = dev->iface_count;
    assert(out_dup == -1); /* EVA-proven oracle */
    assert(out_count == 1); /* EVA-proven oracle */
    device_free(dev);
    interface_free(b);
    printf("PASS test_add_interface_duplicate_tv001\n");
}

static void test_add_interface_full_tv001(void) {
    Device *dev = device_create("R", 1);
    assert(dev != NULL);
    uint8_t mac_a[6] = {0x11,0x11,0x11,0x11,0x11,0x11};
    uint8_t mac_b[6] = {0x22,0x22,0x22,0x22,0x22,0x22};
    Interface *a = interface_create("eth0", mac_a, 0xC0A80001, 24, 1500);
    assert(a != NULL);
    Interface *b = interface_create("eth1", mac_b, 0xC0A80002, 24, 1500);
    assert(b != NULL);
    device_add_interface(dev, a);
    int out_full = device_add_interface(dev, b);
    assert(out_full == -1); /* EVA-proven oracle */
    device_free(dev);
    interface_free(b);
    printf("PASS test_add_interface_full_tv001\n");
}

static void test_add_interface_null_tv001(void) {
    uint8_t mac[6] = {0};
    Interface *iface = interface_create("eth0", mac, 0, 24, 1500);
    assert(iface != NULL);
    int out_null_dev   = device_add_interface(NULL,  iface);
    int out_null_iface = device_add_interface(NULL,  NULL);
    assert(out_null_dev == -1); /* EVA-proven oracle */
    assert(out_null_iface == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_add_interface_null_tv001\n");
}

static void test_get_interface_by_name_found_tv001(void) {
    Device *dev = device_create("R", 4);
    assert(dev != NULL);
    uint8_t mac[6] = {0};
    Interface *iface = interface_create("eth0", mac, 0xC0A80001, 24, 1500);
    assert(iface != NULL);
    device_add_interface(dev, iface);
    Interface *out_found = device_get_interface_by_name(dev, iface->name);
    int out_match = (out_found == iface) ? 1 : 0;
    assert(out_match == 1); /* EVA-proven oracle */
    device_free(dev);
    printf("PASS test_get_interface_by_name_found_tv001\n");
}

static void test_get_interface_by_name_not_found_tv001(void) {
    Device *dev = device_create("R", 4);
    assert(dev != NULL);
    Interface *out_result = device_get_interface_by_name(dev, "eth0");
    int out_is_null = (out_result == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    device_free(dev);
    printf("PASS test_get_interface_by_name_not_found_tv001\n");
}

static void test_get_interface_by_name_null_tv001(void) {
    Device *dev = device_create("R", 1);
    assert(dev != NULL);
    Interface *r1 = device_get_interface_by_name(NULL, "eth0");
    Interface *r2 = device_get_interface_by_name(dev,  NULL);
    int out_null_dev  = (r1 == NULL) ? 1 : 0;
    int out_null_name = (r2 == NULL) ? 1 : 0;
    assert(out_null_dev == 1); /* EVA-proven oracle */
    assert(out_null_name == 1); /* EVA-proven oracle */
    device_free(dev);
    printf("PASS test_get_interface_by_name_null_tv001\n");
}

static void test_get_interface_by_ip_found_tv001(void) {
    Device *dev = device_create("R", 4);
    assert(dev != NULL);
    uint8_t mac[6] = {0};
    Interface *iface = interface_create("eth0", mac, 0xC0A80001, 24, 1500);
    assert(iface != NULL);
    device_add_interface(dev, iface);
    Interface *out_found = device_get_interface_by_ip(dev, 0xC0A80001);
    int out_match = (out_found == iface) ? 1 : 0;
    assert(out_match == 1); /* EVA-proven oracle */
    device_free(dev);
    printf("PASS test_get_interface_by_ip_found_tv001\n");
}

static void test_get_interface_by_ip_not_found_tv001(void) {
    Device *dev = device_create("R", 4);
    assert(dev != NULL);
    uint8_t mac[6] = {0};
    Interface *iface = interface_create("eth0", mac, 0xC0A80001, 24, 1500);
    assert(iface != NULL);
    device_add_interface(dev, iface);
    Interface *out_result = device_get_interface_by_ip(dev, 0xDEADBEEF);
    int out_is_null = (out_result == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    device_free(dev);
    printf("PASS test_get_interface_by_ip_not_found_tv001\n");
}

static void test_get_interface_by_ip_null_tv001(void) {
    Interface *out_result = device_get_interface_by_ip(NULL, 0xC0A80001);
    int out_is_null = (out_result == NULL) ? 1 : 0;
    assert(out_is_null == 1); /* EVA-proven oracle */
    printf("PASS test_get_interface_by_ip_null_tv001\n");
}

static void test_receive_packet_ok_tv001(void) {
    Device *dev = device_create("R", 1);
    assert(dev != NULL);
    uint8_t mac[6] = {0};
    Interface *iface = interface_create("eth0", mac, 0xC0A80001, 24, 1500);
    assert(iface != NULL);
    device_add_interface(dev, iface);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    int out_ret = device_receive_packet(dev, iface, pkt);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(pkt);
    device_free(dev);
    printf("PASS test_receive_packet_ok_tv001\n");
}

static void test_receive_packet_null_tv001(void) {
    uint8_t mac[6] = {0};
    Interface *iface = interface_create("eth0", mac, 0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    int out_null_dev   = device_receive_packet(NULL,  iface, pkt);
    int out_null_iface = device_receive_packet(NULL,  NULL,  pkt);
    int out_null_pkt   = device_receive_packet(NULL,  iface, NULL);
    assert(out_null_dev == -1); /* EVA-proven oracle */
    assert(out_null_iface == -1); /* EVA-proven oracle */
    assert(out_null_pkt == -1); /* EVA-proven oracle */
    interface_free(iface);
    packet_free(pkt);
    printf("PASS test_receive_packet_null_tv001\n");
}

static void test_send_packet_ok_tv001(void) {
    Device *dev = device_create("R", 1);
    assert(dev != NULL);
    uint8_t mac[6] = {0};
    Interface *iface = interface_create("eth0", mac, 0xC0A80001, 24, 1500);
    assert(iface != NULL);
    device_add_interface(dev, iface);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    int out_ret = device_send_packet(dev, iface, pkt);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(pkt);
    device_free(dev);
    printf("PASS test_send_packet_ok_tv001\n");
}

static void test_send_packet_null_tv001(void) {
    uint8_t mac[6] = {0};
    Interface *iface = interface_create("eth0", mac, 0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    int out_null_dev   = device_send_packet(NULL,  iface, pkt);
    int out_null_iface = device_send_packet(NULL,  NULL,  pkt);
    int out_null_pkt   = device_send_packet(NULL,  iface, NULL);
    assert(out_null_dev == -1); /* EVA-proven oracle */
    assert(out_null_iface == -1); /* EVA-proven oracle */
    assert(out_null_pkt == -1); /* EVA-proven oracle */
    interface_free(iface);
    packet_free(pkt);
    printf("PASS test_send_packet_null_tv001\n");
}

int main(void) {
    test_create_tv001();
    test_create_tv002();
    test_create_null_tv001();
    test_free_null_tv001();
    test_add_interface_ok_tv001();
    test_add_interface_duplicate_tv001();
    test_add_interface_full_tv001();
    test_add_interface_null_tv001();
    test_get_interface_by_name_found_tv001();
    test_get_interface_by_name_not_found_tv001();
    test_get_interface_by_name_null_tv001();
    test_get_interface_by_ip_found_tv001();
    test_get_interface_by_ip_not_found_tv001();
    test_get_interface_by_ip_null_tv001();
    test_receive_packet_ok_tv001();
    test_receive_packet_null_tv001();
    test_send_packet_ok_tv001();
    test_send_packet_null_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
