/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-11 18:08:43
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "icmp.h"

static void test_receive_null_iface_tv001(void) {
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    int out_ret = icmp_receive(NULL, pkt, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_receive_null_iface_tv001\n");
}

static void test_receive_null_pkt_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    int out_ret = icmp_receive(iface, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_null_pkt_tv001\n");
}

static void test_receive_too_short_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ((ICMP_HDR_LEN) > 0 ? (ICMP_HDR_LEN) - 1 : 0);
    int out_ret = icmp_receive(iface, pkt, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_too_short_tv001\n");
}

static void test_receive_missing_stripped_ip_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    pkt->data = pkt->head;
    int out_ret = icmp_receive(iface, pkt, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_missing_stripped_ip_tv001\n");
}

static void test_receive_readable_message_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_readable_message_tv001\n");
}

static void test_receive_source_case_ICMP_ECHO_REQUEST_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->type = ICMP_ECHO_REQUEST;
    ((IcmpHeader *)pkt->data)->code = 0;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_case_ICMP_ECHO_REQUEST_tv001\n");
}

static void test_receive_source_case_ICMP_ECHO_REPLY_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->type = ICMP_ECHO_REPLY;
    ((IcmpHeader *)pkt->data)->code = 0;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_case_ICMP_ECHO_REPLY_tv001\n");
}

static void test_receive_source_case_ICMP_DEST_UNREACH_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->type = ICMP_DEST_UNREACH;
    ((IcmpHeader *)pkt->data)->code = 0;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_case_ICMP_DEST_UNREACH_tv001\n");
}

static void test_receive_source_case_ICMP_TIME_EXCEEDED_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->type = ICMP_TIME_EXCEEDED;
    ((IcmpHeader *)pkt->data)->code = 0;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_case_ICMP_TIME_EXCEEDED_tv001\n");
}

static void test_receive_source_default_type_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->type = 255;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_default_type_tv001\n");
}

static void test_receive_source_icmp_hdr_code_0_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->code = 0;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == 0); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_icmp_hdr_code_0_tv001\n");
}

static void test_receive_source_icmp_hdr_code_1_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->code = 1;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_icmp_hdr_code_1_tv001\n");
}

static void test_receive_source_icmp_hdr_code_2_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->code = 2;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_icmp_hdr_code_2_tv001\n");
}

static void test_receive_source_icmp_hdr_code_3_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->code = 3;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_icmp_hdr_code_3_tv001\n");
}

static void test_receive_source_icmp_hdr_code_4_tv001(void) {
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *pkt = packet_create(64);
    assert(pkt != NULL);
    pkt->len = ICMP_HDR_LEN;
    uint8_t pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(pkt_IP_HDR_LEN_header, 0, sizeof(pkt_IP_HDR_LEN_header));
    int pkt_IP_HDR_LEN_prep_ret = packet_prepend(pkt, pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_prep_ret == 0);
    int pkt_IP_HDR_LEN_strip_ret = packet_strip(pkt, IP_HDR_LEN);
    assert(pkt_IP_HDR_LEN_strip_ret == 0);
    if (pkt->len == 0) pkt->len = 1;
    memset(pkt->data, 0, pkt->len);
    ((IcmpHeader *)pkt->data)->code = 4;
    ((IcmpHeader *)pkt->data)->checksum = 0;
    ((IcmpHeader *)pkt->data)->checksum = icmp_checksum(pkt->data, pkt->len);
    int out_ret = icmp_receive(iface, pkt, NULL);
    assert(out_ret == -1); /* EVA-proven oracle */
    interface_free(iface);
    printf("PASS test_receive_source_icmp_hdr_code_4_tv001\n");
}

static void test_send_echo_request_null_input_tv001(void) {
    int out_ret = icmp_send_echo_request(NULL, 0, 0, 0, 0, NULL, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_echo_request_null_input_tv001\n");
}

static void test_send_echo_request_valid_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t payload_buf[64];
    memset(payload_buf, 0, sizeof(payload_buf));
    int out_ret = icmp_send_echo_request(sim, 0, 0, 0, 0, payload_buf, 1);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    printf("PASS test_send_echo_request_valid_tv001\n");
}

static void test_send_echo_reply_null_input_tv001(void) {
    int out_ret = icmp_send_echo_reply(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_echo_reply_null_input_tv001\n");
}

static void test_send_echo_reply_too_short_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *req_pkt = packet_create(64);
    assert(req_pkt != NULL);
    req_pkt->len = ((ICMP_HDR_LEN) > 0 ? (ICMP_HDR_LEN) - 1 : 0);
    int out_ret = icmp_send_echo_reply(sim, iface, req_pkt);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    printf("PASS test_send_echo_reply_too_short_tv001\n");
}

static void test_send_echo_reply_missing_stripped_ip_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *req_pkt = packet_create(64);
    assert(req_pkt != NULL);
    req_pkt->len = ICMP_HDR_LEN;
    req_pkt->data = req_pkt->head;
    int out_ret = icmp_send_echo_reply(sim, iface, req_pkt);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    printf("PASS test_send_echo_reply_missing_stripped_ip_tv001\n");
}

static void test_send_echo_reply_valid_echo_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *req_pkt = packet_create(64);
    assert(req_pkt != NULL);
    req_pkt->len = ICMP_HDR_LEN;
    uint8_t req_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(req_pkt_IP_HDR_LEN_header, 0, sizeof(req_pkt_IP_HDR_LEN_header));
    int req_pkt_IP_HDR_LEN_prep_ret = packet_prepend(req_pkt, req_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(req_pkt_IP_HDR_LEN_prep_ret == 0);
    int req_pkt_IP_HDR_LEN_strip_ret = packet_strip(req_pkt, IP_HDR_LEN);
    assert(req_pkt_IP_HDR_LEN_strip_ret == 0);
    if (req_pkt->len == 0) req_pkt->len = 1;
    memset(req_pkt->data, 0, req_pkt->len);
    ((IcmpHeader *)req_pkt->data)->type = ICMP_ECHO_REQUEST;
    ((IcmpHeader *)req_pkt->data)->code = 0;
    int out_ret = icmp_send_echo_reply(sim, iface, req_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    printf("PASS test_send_echo_reply_valid_echo_tv001\n");
}

static void test_send_time_exceeded_null_input_tv001(void) {
    int out_ret = icmp_send_time_exceeded(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_time_exceeded_null_input_tv001\n");
}

static void test_send_time_exceeded_readable_original_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    int out_ret = icmp_send_time_exceeded(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_time_exceeded_readable_original_tv001\n");
}

static void test_send_time_exceeded_source_orig_ip_protocol_IPPROTO_ICMP_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IpHeader *)(orig_pkt->data - IP_HDR_LEN))->protocol = IPPROTO_ICMP;
    int out_ret = icmp_send_time_exceeded(sim, iface, orig_pkt);
    assert(out_ret == 0); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_time_exceeded_source_orig_ip_protocol_IPPROTO_ICMP_tv001\n");
}

static void test_send_time_exceeded_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_DEST_UNREACH;
    int out_ret = icmp_send_time_exceeded(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_time_exceeded_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001\n");
}

static void test_send_time_exceeded_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_TIME_EXCEEDED;
    int out_ret = icmp_send_time_exceeded(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_time_exceeded_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001\n");
}

static void test_send_unreach_net_null_input_tv001(void) {
    int out_ret = icmp_send_unreach_net(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_unreach_net_null_input_tv001\n");
}

static void test_send_unreach_net_readable_original_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    int out_ret = icmp_send_unreach_net(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_net_readable_original_tv001\n");
}

static void test_send_unreach_net_source_orig_ip_protocol_IPPROTO_ICMP_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IpHeader *)(orig_pkt->data - IP_HDR_LEN))->protocol = IPPROTO_ICMP;
    int out_ret = icmp_send_unreach_net(sim, iface, orig_pkt);
    assert(out_ret == 0); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_net_source_orig_ip_protocol_IPPROTO_ICMP_tv001\n");
}

static void test_send_unreach_net_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_DEST_UNREACH;
    int out_ret = icmp_send_unreach_net(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_net_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001\n");
}

static void test_send_unreach_net_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_TIME_EXCEEDED;
    int out_ret = icmp_send_unreach_net(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_net_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001\n");
}

static void test_send_unreach_host_null_input_tv001(void) {
    int out_ret = icmp_send_unreach_host(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_unreach_host_null_input_tv001\n");
}

static void test_send_unreach_host_readable_original_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    int out_ret = icmp_send_unreach_host(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_host_readable_original_tv001\n");
}

static void test_send_unreach_host_source_orig_ip_protocol_IPPROTO_ICMP_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IpHeader *)(orig_pkt->data - IP_HDR_LEN))->protocol = IPPROTO_ICMP;
    int out_ret = icmp_send_unreach_host(sim, iface, orig_pkt);
    assert(out_ret == 0); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_host_source_orig_ip_protocol_IPPROTO_ICMP_tv001\n");
}

static void test_send_unreach_host_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_DEST_UNREACH;
    int out_ret = icmp_send_unreach_host(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_host_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001\n");
}

static void test_send_unreach_host_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_TIME_EXCEEDED;
    int out_ret = icmp_send_unreach_host(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_host_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001\n");
}

static void test_send_unreach_proto_null_input_tv001(void) {
    int out_ret = icmp_send_unreach_proto(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_unreach_proto_null_input_tv001\n");
}

static void test_send_unreach_proto_readable_original_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    int out_ret = icmp_send_unreach_proto(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_proto_readable_original_tv001\n");
}

static void test_send_unreach_proto_source_orig_ip_protocol_IPPROTO_ICMP_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IpHeader *)(orig_pkt->data - IP_HDR_LEN))->protocol = IPPROTO_ICMP;
    int out_ret = icmp_send_unreach_proto(sim, iface, orig_pkt);
    assert(out_ret == 0); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_proto_source_orig_ip_protocol_IPPROTO_ICMP_tv001\n");
}

static void test_send_unreach_proto_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_DEST_UNREACH;
    int out_ret = icmp_send_unreach_proto(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_proto_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001\n");
}

static void test_send_unreach_proto_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_TIME_EXCEEDED;
    int out_ret = icmp_send_unreach_proto(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_proto_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001\n");
}

static void test_send_unreach_port_null_input_tv001(void) {
    int out_ret = icmp_send_unreach_port(NULL, NULL, NULL);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_unreach_port_null_input_tv001\n");
}

static void test_send_unreach_port_readable_original_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    int out_ret = icmp_send_unreach_port(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_port_readable_original_tv001\n");
}

static void test_send_unreach_port_source_orig_ip_protocol_IPPROTO_ICMP_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IpHeader *)(orig_pkt->data - IP_HDR_LEN))->protocol = IPPROTO_ICMP;
    int out_ret = icmp_send_unreach_port(sim, iface, orig_pkt);
    assert(out_ret == 0); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_port_source_orig_ip_protocol_IPPROTO_ICMP_tv001\n");
}

static void test_send_unreach_port_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_DEST_UNREACH;
    int out_ret = icmp_send_unreach_port(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_port_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001\n");
}

static void test_send_unreach_port_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_TIME_EXCEEDED;
    int out_ret = icmp_send_unreach_port(sim, iface, orig_pkt);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_unreach_port_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001\n");
}

static void test_send_frag_needed_null_input_tv001(void) {
    int out_ret = icmp_send_frag_needed(NULL, NULL, NULL, 0);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_send_frag_needed_null_input_tv001\n");
}

static void test_send_frag_needed_readable_original_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    int out_ret = icmp_send_frag_needed(sim, iface, orig_pkt, 0);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_frag_needed_readable_original_tv001\n");
}

static void test_send_frag_needed_source_orig_ip_protocol_IPPROTO_ICMP_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IpHeader *)(orig_pkt->data - IP_HDR_LEN))->protocol = IPPROTO_ICMP;
    int out_ret = icmp_send_frag_needed(sim, iface, orig_pkt, 0);
    assert(out_ret == 0); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_frag_needed_source_orig_ip_protocol_IPPROTO_ICMP_tv001\n");
}

static void test_send_frag_needed_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_DEST_UNREACH;
    int out_ret = icmp_send_frag_needed(sim, iface, orig_pkt, 0);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_frag_needed_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001\n");
}

static void test_send_frag_needed_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001(void) {
    Topology *sim_topo = topology_create();
    assert(sim_topo != NULL);
    Scheduler *sim_sched = scheduler_create(64);
    assert(sim_sched != NULL);
    Simulator *sim = simulator_create(sim_topo, sim_sched);
    assert(sim != NULL);
    uint8_t iface_mac[6] = {0, 0, 0, 0, 0, 0};
    Interface *iface = interface_create("kleva", iface_mac, 0x0100A8C0, 24, 1500);
    assert(iface != NULL);
    Packet *orig_pkt = packet_create(64);
    assert(orig_pkt != NULL);
    uint8_t orig_pkt_IP_HDR_LEN_header[IP_HDR_LEN];
    memset(orig_pkt_IP_HDR_LEN_header, 0, sizeof(orig_pkt_IP_HDR_LEN_header));
    int orig_pkt_IP_HDR_LEN_prep_ret = packet_prepend(orig_pkt, orig_pkt_IP_HDR_LEN_header, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_prep_ret == 0);
    int orig_pkt_IP_HDR_LEN_strip_ret = packet_strip(orig_pkt, IP_HDR_LEN);
    assert(orig_pkt_IP_HDR_LEN_strip_ret == 0);
    ((IcmpHeader *)orig_pkt->data)->type = ICMP_TIME_EXCEEDED;
    int out_ret = icmp_send_frag_needed(sim, iface, orig_pkt, 0);
    assert(out_ret == -1); /* EVA-proven oracle */
    simulator_free(sim);
    interface_free(iface);
    packet_free(orig_pkt);
    printf("PASS test_send_frag_needed_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001\n");
}

static void test_checksum_null_tv001(void) {
    uint16_t out_ret = icmp_checksum(NULL, 1);
    int out_sentinel = (out_ret == 65535) ? 1 : 0;
    assert(out_ret == 65535); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    printf("PASS test_checksum_null_tv001\n");
}

static void test_checksum_empty_tv001(void) {
    uint16_t out_ret = icmp_checksum(NULL, 1);
    assert(out_ret == 65535); /* EVA-proven oracle */
    printf("PASS test_checksum_empty_tv001\n");
}

static void test_checksum_valid_tv001(void) {
    uint16_t out_ret = icmp_checksum(NULL, 1);
    assert(out_ret == 65535); /* EVA-proven oracle */
    printf("PASS test_checksum_valid_tv001\n");
}

int main(void) {
    test_receive_null_iface_tv001();
    test_receive_null_pkt_tv001();
    test_receive_too_short_tv001();
    test_receive_missing_stripped_ip_tv001();
    test_receive_readable_message_tv001();
    test_receive_source_case_ICMP_ECHO_REQUEST_tv001();
    test_receive_source_case_ICMP_ECHO_REPLY_tv001();
    test_receive_source_case_ICMP_DEST_UNREACH_tv001();
    test_receive_source_case_ICMP_TIME_EXCEEDED_tv001();
    test_receive_source_default_type_tv001();
    test_receive_source_icmp_hdr_code_0_tv001();
    test_receive_source_icmp_hdr_code_1_tv001();
    test_receive_source_icmp_hdr_code_2_tv001();
    test_receive_source_icmp_hdr_code_3_tv001();
    test_receive_source_icmp_hdr_code_4_tv001();
    test_send_echo_request_null_input_tv001();
    test_send_echo_request_valid_tv001();
    test_send_echo_reply_null_input_tv001();
    test_send_echo_reply_too_short_tv001();
    test_send_echo_reply_missing_stripped_ip_tv001();
    test_send_echo_reply_valid_echo_tv001();
    test_send_time_exceeded_null_input_tv001();
    test_send_time_exceeded_readable_original_tv001();
    test_send_time_exceeded_source_orig_ip_protocol_IPPROTO_ICMP_tv001();
    test_send_time_exceeded_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001();
    test_send_time_exceeded_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001();
    test_send_unreach_net_null_input_tv001();
    test_send_unreach_net_readable_original_tv001();
    test_send_unreach_net_source_orig_ip_protocol_IPPROTO_ICMP_tv001();
    test_send_unreach_net_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001();
    test_send_unreach_net_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001();
    test_send_unreach_host_null_input_tv001();
    test_send_unreach_host_readable_original_tv001();
    test_send_unreach_host_source_orig_ip_protocol_IPPROTO_ICMP_tv001();
    test_send_unreach_host_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001();
    test_send_unreach_host_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001();
    test_send_unreach_proto_null_input_tv001();
    test_send_unreach_proto_readable_original_tv001();
    test_send_unreach_proto_source_orig_ip_protocol_IPPROTO_ICMP_tv001();
    test_send_unreach_proto_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001();
    test_send_unreach_proto_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001();
    test_send_unreach_port_null_input_tv001();
    test_send_unreach_port_readable_original_tv001();
    test_send_unreach_port_source_orig_ip_protocol_IPPROTO_ICMP_tv001();
    test_send_unreach_port_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001();
    test_send_unreach_port_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001();
    test_send_frag_needed_null_input_tv001();
    test_send_frag_needed_readable_original_tv001();
    test_send_frag_needed_source_orig_ip_protocol_IPPROTO_ICMP_tv001();
    test_send_frag_needed_source_orig_icmp_type_ICMP_DEST_UNREACH_tv001();
    test_send_frag_needed_source_orig_icmp_type_ICMP_TIME_EXCEEDED_tv001();
    test_checksum_null_tv001();
    test_checksum_empty_tv001();
    test_checksum_valid_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
