/* AUTO-GENERATED by kleva (KLEE + EVA) — DO NOT EDIT
 * Oracle values are EVA-proven singletons — not hand-written expected values.
 * Re-generate: kleva gen <module.yaml>
 * Generated: 2026-06-30 13:15:17
 */
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "packet.h"

/* KLEVA native compile note:
 * This generated test includes allocator-failure candidates.
 * Compile the module-under-test with:
 *   -Dmalloc=__kleva_malloc -Dcalloc=__kleva_calloc -Drealloc=__kleva_realloc -Dfree=__kleva_free
 */

#include "packet.h"
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#ifdef malloc
#undef malloc
#endif
#ifdef calloc
#undef calloc
#endif
#ifdef realloc
#undef realloc
#endif
#ifdef free
#undef free
#endif
static unsigned char __kleva_alloc_arena[1024u * 1024u];
static size_t __kleva_alloc_offset;
static long __kleva_alloc_call;
static long __kleva_alloc_fail_at = -1;
static void __kleva_alloc_reset(void) {
    __kleva_alloc_offset = 0;
    __kleva_alloc_call = 0;
    __kleva_alloc_fail_at = -1;
}
static void __kleva_alloc_fail_on(long index) {
    __kleva_alloc_reset();
    __kleva_alloc_fail_at = index;
}
void *__kleva_malloc(size_t size) {
    if (__kleva_alloc_fail_at >= 0 && __kleva_alloc_call == __kleva_alloc_fail_at) {
        __kleva_alloc_call++;
        __kleva_alloc_fail_at = -1;
        return (void *)0;
    }
    __kleva_alloc_call++;
    if (size == 0) {
        size = 1;
    }
    size = (size + 7u) & ~((size_t)7u);
    if (size > sizeof(__kleva_alloc_arena) - __kleva_alloc_offset) {
        return (void *)0;
    }
    void *ptr = __kleva_alloc_arena + __kleva_alloc_offset;
    __kleva_alloc_offset += size;
    return ptr;
}
void __kleva_free(void *ptr) {
    (void)ptr;
}
void *__kleva_calloc(size_t count, size_t size) {
    size_t total = count * size;
    void *ptr = __kleva_malloc(total);
    if (ptr) {
        memset(ptr, 0, total);
    }
    return ptr;
}
void *__kleva_realloc(void *ptr, size_t size) {
    (void)ptr;
    return __kleva_malloc(size);
}

static void test_create_valid_tv001(void) {
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 1); /* EVA-proven oracle */
    printf("PASS test_create_valid_tv001\n");
}

static void test_create_ir_alloc_malloc_0_zero_failure_tv001(void) {
    __kleva_alloc_fail_on(0);
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_capacity == 0); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_0_zero_failure_tv001\n");
}

static void test_create_ir_alloc_malloc_0_zero_success_tv001(void) {
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_0_zero_success_tv001\n");
}

static void test_create_ir_alloc_malloc_1_zero_failure_tv001(void) {
    __kleva_alloc_fail_on(1);
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    assert(out_capacity == 0); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_1_zero_failure_tv001\n");
}

static void test_create_ir_alloc_malloc_1_zero_success_tv001(void) {
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_alloc_malloc_1_zero_success_tv001\n");
}

static void test_create_ir_diversity_capacity_one_tv001(void) {
    Packet * out_ret = packet_create(1);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 1); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_capacity_one_tv001\n");
}

static void test_create_ir_diversity_capacity_two_tv001(void) {
    Packet * out_ret = packet_create(2);
    int out_ret_nonnull = (out_ret != NULL);
    size_t out_capacity = out_ret ? out_ret->capacity : 0;
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    assert(out_capacity == 2); /* EVA-proven oracle */
    printf("PASS test_create_ir_diversity_capacity_two_tv001\n");
}

static void test_prepend_valid_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    uintptr_t kleva_old_ir_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_len = (uintptr_t)(p->len);
    int out_ret = packet_prepend(p, header, 1);
    int out_ir_post_p_data = ((uintptr_t)(p->data) == (uintptr_t)((kleva_old_ir_p_data - 1)));
    int out_ir_post_p_len = ((uintptr_t)(p->len) == (uintptr_t)((kleva_old_ir_p_len + 1)));
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_ir_post_p_data == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_valid_tv001\n");
}

static void test_prepend_ok_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    p->data = p->head + 1;
    uintptr_t kleva_old_p_len = (uintptr_t)(p->len);
    uintptr_t kleva_old_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_len = (uintptr_t)(p->len);
    int out_ret = packet_prepend(p, header, 1);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    int out_post_p_len_header_len = ((uintptr_t)(p->len) == (kleva_old_p_len + (uintptr_t)(1)));
    int out_post_p_data_header_len = ((uintptr_t)(p->data) == (kleva_old_p_data - (uintptr_t)(1)));
    int out_ir_post_p_data = ((uintptr_t)(p->data) == (uintptr_t)((kleva_old_ir_p_data - 1)));
    int out_ir_post_p_len = ((uintptr_t)(p->len) == (uintptr_t)((kleva_old_ir_p_len + 1)));
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    assert(out_post_p_len_header_len == 1); /* EVA-proven oracle */
    assert(out_post_p_data_header_len == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_data == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_ok_tv001\n");
}

static void test_prepend_no_headroom_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    p->data = p->head;
    uintptr_t kleva_old_p_len = (uintptr_t)(p->len);
    int out_ret = packet_prepend(p, header, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    int out_post_p_len = ((uintptr_t)(p->len) == kleva_old_p_len);
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    assert(out_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_no_headroom_tv001\n");
}

static void test_prepend_ir_if_0_header_len_gt_size_t_p_data_p_head_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    int out_ret = packet_prepend(p, header, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_prepend_ir_if_0_header_len_gt_size_t_p_data_p_head_tv001\n");
}

static void test_prepend_ir_if_0_false_header_len_le_size_t_p_data_p_head_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    int out_ret = packet_prepend(p, header, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_prepend_ir_if_0_false_header_len_le_size_t_p_data_p_head_tv001\n");
}

static void test_prepend_ir_diversity_header_len_one_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    int out_ret = packet_prepend(p, header, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_ir_diversity_header_len_one_tv001\n");
}

static void test_prepend_ir_diversity_header_len_two_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t header_buf[256];
    memset(header_buf, 0, sizeof(header_buf));
    const void * header = header_buf;
    int out_ret = packet_prepend(p, header, 2);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_prepend_ir_diversity_header_len_two_tv001\n");
}

static void test_strip_valid_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uintptr_t kleva_old_ir_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_len = (uintptr_t)(p->len);
    int out_ret = packet_strip(p, 1);
    int out_ir_post_p_data = ((uintptr_t)(p->data) == (uintptr_t)((kleva_old_ir_p_data + 1)));
    int out_ir_post_p_len = ((uintptr_t)(p->len) == (uintptr_t)((kleva_old_ir_p_len - 1)));
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_ir_post_p_data == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_valid_tv001\n");
}

static void test_strip_valid_strip_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    p->len = 1;
    uintptr_t kleva_old_p_len = (uintptr_t)(p->len);
    uintptr_t kleva_old_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_data = (uintptr_t)(p->data);
    uintptr_t kleva_old_ir_p_len = (uintptr_t)(p->len);
    int out_ret = packet_strip(p, 1);
    int out_sentinel = (out_ret == 0) ? 1 : 0;
    int out_post_p_len_header_len = ((uintptr_t)(p->len) == (kleva_old_p_len - (uintptr_t)(1)));
    int out_post_p_data_header_len = ((uintptr_t)(p->data) == (kleva_old_p_data + (uintptr_t)(1)));
    int out_ir_post_p_data = ((uintptr_t)(p->data) == (uintptr_t)((kleva_old_ir_p_data + 1)));
    int out_ir_post_p_len = ((uintptr_t)(p->len) == (uintptr_t)((kleva_old_ir_p_len - 1)));
    assert(out_ret == 0); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    assert(out_post_p_len_header_len == 1); /* EVA-proven oracle */
    assert(out_post_p_data_header_len == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_data == 1); /* EVA-proven oracle */
    assert(out_ir_post_p_len == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_valid_strip_tv001\n");
}

static void test_strip_overflow_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    p->len = ((1) > 0 ? (1) - 1 : 0);
    uintptr_t kleva_old_p_len = (uintptr_t)(p->len);
    uintptr_t kleva_old_p_data = (uintptr_t)(p->data);
    int out_ret = packet_strip(p, 1);
    int out_sentinel = (out_ret == -1) ? 1 : 0;
    int out_post_p_len = ((uintptr_t)(p->len) == kleva_old_p_len);
    int out_post_p_data = ((uintptr_t)(p->data) == kleva_old_p_data);
    assert(out_ret == -1); /* EVA-proven oracle */
    assert(out_sentinel == 1); /* EVA-proven oracle */
    assert(out_post_p_len == 1); /* EVA-proven oracle */
    assert(out_post_p_data == 1); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_overflow_tv001\n");
}

static void test_strip_ir_if_0_header_len_gt_p_len_tv001(void) {
    size_t header_len = (size_t)1ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (((p)->len) + 1);
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_header_len_gt_p_len_tv001\n");
}

static void test_strip_ir_if_0_header_len_gt_p_len_tv002(void) {
    size_t header_len = (size_t)2ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (((p)->len) + 1);
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_header_len_gt_p_len_tv002\n");
}

static void test_strip_ir_if_0_header_len_gt_p_len_tv003(void) {
    size_t header_len = (size_t)268435454ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (((p)->len) + 1);
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_header_len_gt_p_len_tv003\n");
}

static void test_strip_ir_if_0_header_len_gt_p_len_tv004(void) {
    size_t header_len = (size_t)268435455ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (((p)->len) + 1);
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_header_len_gt_p_len_tv004\n");
}

static void test_strip_ir_if_0_header_len_gt_p_len_tv005(void) {
    size_t header_len = (size_t)134217728ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (((p)->len) + 1);
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == -1); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_header_len_gt_p_len_tv005\n");
}

static void test_strip_ir_if_0_false_header_len_le_p_len_tv001(void) {
    size_t header_len = (size_t)1ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (p)->len;
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_false_header_len_le_p_len_tv001\n");
}

static void test_strip_ir_if_0_false_header_len_le_p_len_tv002(void) {
    size_t header_len = (size_t)2ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (p)->len;
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_false_header_len_le_p_len_tv002\n");
}

static void test_strip_ir_if_0_false_header_len_le_p_len_tv003(void) {
    size_t header_len = (size_t)268435454ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (p)->len;
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_false_header_len_le_p_len_tv003\n");
}

static void test_strip_ir_if_0_false_header_len_le_p_len_tv004(void) {
    size_t header_len = (size_t)268435455ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (p)->len;
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_false_header_len_le_p_len_tv004\n");
}

static void test_strip_ir_if_0_false_header_len_le_p_len_tv005(void) {
    size_t header_len = (size_t)134217728ULL;
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    (p)->len = 1;
    header_len = (p)->len;
    int out_ret = packet_strip(p, header_len);
    assert(out_ret == 0); /* EVA-proven oracle */
    printf("PASS test_strip_ir_if_0_false_header_len_le_p_len_tv005\n");
}

static void test_strip_ir_diversity_header_len_zero_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    int out_ret = packet_strip(p, 0);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_ir_diversity_header_len_zero_tv001\n");
}

static void test_strip_ir_diversity_header_len_one_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    int out_ret = packet_strip(p, 1);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_ir_diversity_header_len_one_tv001\n");
}

static void test_strip_ir_diversity_header_len_two_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    int out_ret = packet_strip(p, 2);
    assert(out_ret == 0); /* EVA-proven oracle */
    packet_free(p);
    printf("PASS test_strip_ir_diversity_header_len_two_tv001\n");
}

static void test_clone_valid_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t p_data_buffer[64];
    memset(p_data_buffer, 0, sizeof(p_data_buffer));
    if (p->data == NULL) p->data = p_data_buffer;
    memset(p->data, 0, p->len);
    Packet * out_ret = packet_clone(p);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_clone_valid_tv001\n");
}

static void test_clone_ir_callee_packet_create_zero_failure_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    __kleva_alloc_fail_on(0);
    uint8_t p_data_buffer[64];
    memset(p_data_buffer, 0, sizeof(p_data_buffer));
    if (p->data == NULL) p->data = p_data_buffer;
    memset(p->data, 0, p->len);
    Packet * out_ret = packet_clone(p);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 0); /* EVA-proven oracle */
    printf("PASS test_clone_ir_callee_packet_create_zero_failure_tv001\n");
}

static void test_clone_ir_callee_packet_create_zero_success_tv001(void) {
    Packet * packet_create(size_t capacity);
    Packet *p = packet_create(64);
    assert(p != NULL);
    void packet_free(Packet *arg0);
    uint8_t p_data[64];
    memset(p_data, 0, sizeof(p_data));
    if (p->data == NULL) p->data = p_data;
    if (p->len == 0) p->len = 8;
    memset(p->data, 0, p->len);
    uint8_t p_data_buffer[64];
    memset(p_data_buffer, 0, sizeof(p_data_buffer));
    if (p->data == NULL) p->data = p_data_buffer;
    memset(p->data, 0, p->len);
    Packet * out_ret = packet_clone(p);
    int out_ret_nonnull = (out_ret != NULL);
    assert(out_ret_nonnull == 1); /* EVA-proven oracle */
    printf("PASS test_clone_ir_callee_packet_create_zero_success_tv001\n");
}

static void test_checksum_valid_tv001(void) {
    uint8_t data_buf[256];
    memset(data_buf, 0, sizeof(data_buf));
    const void * data = data_buf;
    uint16_t out_ret = packet_checksum(data, 1);
    assert(out_ret == 65535); /* EVA-proven oracle */
    printf("PASS test_checksum_valid_tv001\n");
}

static void test_checksum_ir_diversity_len_one_tv001(void) {
    uint8_t data_buf[256];
    memset(data_buf, 0, sizeof(data_buf));
    const void * data = data_buf;
    uint16_t out_ret = packet_checksum(data, 1);
    assert(out_ret == 65535); /* EVA-proven oracle */
    printf("PASS test_checksum_ir_diversity_len_one_tv001\n");
}

static void test_checksum_ir_diversity_len_two_tv001(void) {
    uint8_t data_buf[256];
    memset(data_buf, 0, sizeof(data_buf));
    const void * data = data_buf;
    uint16_t out_ret = packet_checksum(data, 2);
    assert(out_ret == 65535); /* EVA-proven oracle */
    printf("PASS test_checksum_ir_diversity_len_two_tv001\n");
}

int main(void) {
    test_create_valid_tv001();
    test_create_ir_alloc_malloc_0_zero_failure_tv001();
    test_create_ir_alloc_malloc_0_zero_success_tv001();
    test_create_ir_alloc_malloc_1_zero_failure_tv001();
    test_create_ir_alloc_malloc_1_zero_success_tv001();
    test_create_ir_diversity_capacity_one_tv001();
    test_create_ir_diversity_capacity_two_tv001();
    test_prepend_valid_tv001();
    test_prepend_ok_tv001();
    test_prepend_no_headroom_tv001();
    test_prepend_ir_if_0_header_len_gt_size_t_p_data_p_head_tv001();
    test_prepend_ir_if_0_false_header_len_le_size_t_p_data_p_head_tv001();
    test_prepend_ir_diversity_header_len_one_tv001();
    test_prepend_ir_diversity_header_len_two_tv001();
    test_strip_valid_tv001();
    test_strip_valid_strip_tv001();
    test_strip_overflow_tv001();
    test_strip_ir_if_0_header_len_gt_p_len_tv001();
    test_strip_ir_if_0_header_len_gt_p_len_tv002();
    test_strip_ir_if_0_header_len_gt_p_len_tv003();
    test_strip_ir_if_0_header_len_gt_p_len_tv004();
    test_strip_ir_if_0_header_len_gt_p_len_tv005();
    test_strip_ir_if_0_false_header_len_le_p_len_tv001();
    test_strip_ir_if_0_false_header_len_le_p_len_tv002();
    test_strip_ir_if_0_false_header_len_le_p_len_tv003();
    test_strip_ir_if_0_false_header_len_le_p_len_tv004();
    test_strip_ir_if_0_false_header_len_le_p_len_tv005();
    test_strip_ir_diversity_header_len_zero_tv001();
    test_strip_ir_diversity_header_len_one_tv001();
    test_strip_ir_diversity_header_len_two_tv001();
    test_clone_valid_tv001();
    test_clone_ir_callee_packet_create_zero_failure_tv001();
    test_clone_ir_callee_packet_create_zero_success_tv001();
    test_checksum_valid_tv001();
    test_checksum_ir_diversity_len_one_tv001();
    test_checksum_ir_diversity_len_two_tv001();

    printf("\nAll unit tests passed.\n");
    return 0;
}
